// Generated by Frozen Sand Particle Studio
// Tue Dec 22 03:36:35 2020
// Use on a 64x64 unit brush face

textures/aadel_pipeline/sparkie
{
	qer_editorimage textures/aadel_pipeline/spark1.tga
	q3map_cloneshader textures/aadel_pipeline/zzsparkie_1
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 172 inversesawtooth 0 1 1 0.82
	deformvertexes move 69.0836 295.142 0 sawtooth 0 1 1 0.82
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/aadel_pipeline/spark1.tga
		blendfunc GL_ONE GL_ONE
		rgbgen wave sawtooth 1 -5.3334 1 0.82
		alphagen const 1
		tcMod stretch sawtooth 0.36 0.64 1 0.82
	}
}

textures/aadel_pipeline/zzsparkie_1
{
	qer_editorimage textures/aadel_pipeline/spark1.tga
	q3map_cloneshader textures/aadel_pipeline/zzsparkie_2
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 153 inversesawtooth 0 1 1 0.82
	deformvertexes move -239.758 -124.821 0 sawtooth 0 1 1 0.82
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/aadel_pipeline/spark2.tga
		blendfunc GL_ONE GL_ONE
		rgbgen wave sawtooth 1 -5.3334 1 0.82
		alphagen const 1
		tcMod stretch sawtooth 0.36 0.64 1 0.82
	}
}

textures/aadel_pipeline/zzsparkie_2
{
	qer_editorimage textures/aadel_pipeline/spark1.tga
	q3map_cloneshader textures/aadel_pipeline/zzsparkie_3
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 169 inversesawtooth 0 1 1 0.82
	deformvertexes move -301.603 -86.5632 0 sawtooth 0 1 1 0.82
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/aadel_pipeline/spark3.tga
		blendfunc GL_ONE GL_ONE
		rgbgen wave sawtooth 1 -5.3334 1 0.82
		alphagen const 1
		tcMod stretch sawtooth 0.36 0.64 1 0.82
	}
}

textures/aadel_pipeline/zzsparkie_3
{
	qer_editorimage textures/aadel_pipeline/spark1.tga
	q3map_cloneshader textures/aadel_pipeline/zzsparkie_4
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 173 inversesawtooth 0 1 1 0.82
	deformvertexes move -292.062 -122.982 0 sawtooth 0 1 1 0.82
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/aadel_pipeline/spark1.tga
		blendfunc GL_ONE GL_ONE
		rgbgen wave sawtooth 1 -5.3334 1 0.82
		alphagen const 1
		tcMod stretch sawtooth 0.36 0.64 1 0.82
	}
}

textures/aadel_pipeline/zzsparkie_4
{
	qer_editorimage textures/aadel_pipeline/spark1.tga
	q3map_cloneshader textures/aadel_pipeline/zzsparkie_5
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 175 inversesawtooth 0 1 1 0.82
	deformvertexes move -298.873 -112.821 0 sawtooth 0 1 1 0.82
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/aadel_pipeline/spark2.tga
		blendfunc GL_ONE GL_ONE
		rgbgen wave sawtooth 1 -5.3334 1 0.82
		alphagen const 1
		tcMod stretch sawtooth 0.36 0.64 1 0.82
	}
}

textures/aadel_pipeline/zzsparkie_5
{
	qer_editorimage textures/aadel_pipeline/spark1.tga
	q3map_cloneshader textures/aadel_pipeline/zzsparkie_6
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 155 inversesawtooth 0 1 1 0.82
	deformvertexes move -211.039 168.193 0 sawtooth 0 1 1 0.82
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/aadel_pipeline/spark3.tga
		blendfunc GL_ONE GL_ONE
		rgbgen wave sawtooth 1 -5.3334 1 0.82
		alphagen const 1
		tcMod stretch sawtooth 0.36 0.64 1 0.82
	}
}

textures/aadel_pipeline/zzsparkie_6
{
	qer_editorimage textures/aadel_pipeline/spark1.tga
	q3map_cloneshader textures/aadel_pipeline/zzsparkie_7
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 169 inversesawtooth 0 1 1 0.82
	deformvertexes move -281.878 96.0085 0 sawtooth 0 1 1 0.82
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/aadel_pipeline/spark1.tga
		blendfunc GL_ONE GL_ONE
		rgbgen wave sawtooth 1 -5.3334 1 0.82
		alphagen const 1
		tcMod stretch sawtooth 0.36 0.64 1 0.82
	}
}

textures/aadel_pipeline/zzsparkie_7
{
	qer_editorimage textures/aadel_pipeline/spark1.tga
	q3map_cloneshader textures/aadel_pipeline/zzsparkie_8
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 171 inversesawtooth 0 1 1 0.82
	deformvertexes move 103.842 -295.632 0 sawtooth 0 1 1 0.82
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/aadel_pipeline/spark2.tga
		blendfunc GL_ONE GL_ONE
		rgbgen wave sawtooth 1 -5.3334 1 0.82
		alphagen const 1
		tcMod stretch sawtooth 0.36 0.64 1 0.82
	}
}

textures/aadel_pipeline/zzsparkie_8
{
	qer_editorimage textures/aadel_pipeline/spark1.tga
	q3map_cloneshader textures/aadel_pipeline/zzsparkie_9
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 183 inversesawtooth 0 1 1 0.82
	deformvertexes move -119.754 291.02 0 sawtooth 0 1 1 0.82
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/aadel_pipeline/spark3.tga
		blendfunc GL_ONE GL_ONE
		rgbgen wave sawtooth 1 -5.3334 1 0.82
		alphagen const 1
		tcMod stretch sawtooth 0.36 0.64 1 0.82
	}
}

textures/aadel_pipeline/zzsparkie_9
{
	qer_editorimage textures/aadel_pipeline/spark1.tga
	q3map_cloneshader textures/aadel_pipeline/zzsparkie_10
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 154 inversesawtooth 0 1 1 0.82
	deformvertexes move 55.2685 -256.19 0 sawtooth 0 1 1 0.82
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/aadel_pipeline/spark1.tga
		blendfunc GL_ONE GL_ONE
		rgbgen wave sawtooth 1 -5.3334 1 0.82
		alphagen const 1
		tcMod stretch sawtooth 0.36 0.64 1 0.82
	}
}

textures/aadel_pipeline/zzsparkie_10
{
	qer_editorimage textures/aadel_pipeline/spark1.tga
	q3map_cloneshader textures/aadel_pipeline/zzsparkie_11
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 168 inversesawtooth 0 1 1 0.82
	deformvertexes move -30.5653 -284.362 0 sawtooth 0 1 1 0.82
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/aadel_pipeline/spark2.tga
		blendfunc GL_ONE GL_ONE
		rgbgen wave sawtooth 1 -5.3334 1 0.82
		alphagen const 1
		tcMod stretch sawtooth 0.36 0.64 1 0.82
	}
}

textures/aadel_pipeline/zzsparkie_11
{
	qer_editorimage textures/aadel_pipeline/spark1.tga
	q3map_cloneshader textures/aadel_pipeline/zzsparkie_12
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 163 inversesawtooth 0 1 1 0.82
	deformvertexes move 273.208 -46.2881 0 sawtooth 0 1 1 0.82
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/aadel_pipeline/spark3.tga
		blendfunc GL_ONE GL_ONE
		rgbgen wave sawtooth 1 -5.3334 1 0.82
		alphagen const 1
		tcMod stretch sawtooth 0.36 0.64 1 0.82
	}
}

textures/aadel_pipeline/zzsparkie_12
{
	qer_editorimage textures/aadel_pipeline/spark1.tga
	q3map_cloneshader textures/aadel_pipeline/zzsparkie_13
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 183 inversesawtooth 0 1 1 0.82
	deformvertexes move -308.237 -114.155 0 sawtooth 0 1 1 0.82
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/aadel_pipeline/spark1.tga
		blendfunc GL_ONE GL_ONE
		rgbgen wave sawtooth 1 -5.3334 1 0.82
		alphagen const 1
		tcMod stretch sawtooth 0.36 0.64 1 0.82
	}
}

textures/aadel_pipeline/zzsparkie_13
{
	qer_editorimage textures/aadel_pipeline/spark1.tga
	q3map_cloneshader textures/aadel_pipeline/zzsparkie_14
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 156 inversesawtooth 0 1 1 0.82
	deformvertexes move -126.438 251.667 0 sawtooth 0 1 1 0.82
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/aadel_pipeline/spark2.tga
		blendfunc GL_ONE GL_ONE
		rgbgen wave sawtooth 1 -5.3334 1 0.82
		alphagen const 1
		tcMod stretch sawtooth 0.36 0.64 1 0.82
	}
}

textures/aadel_pipeline/zzsparkie_14
{
	qer_editorimage textures/aadel_pipeline/spark1.tga
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 174 inversesawtooth 0 1 1 0.82
	deformvertexes move -134.232 275.742 0 sawtooth 0 1 1 0.82
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/aadel_pipeline/spark3.tga
		blendfunc GL_ONE GL_ONE
		rgbgen wave sawtooth 1 -5.3334 1 0.82
		alphagen const 1
		tcMod stretch sawtooth 0.36 0.64 1 0.82
	}
}

