// Generated by Frozen Sand Particle Studio
// Wed Nov 18 20:53:58 2009


textures/runy9/fallssplashcote
{
	qer_editorimage textures/runy9/raiderssplash01.tga
	q3map_cloneshader textures/runy9/zzfallssplashcote_1
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 330 triangle 0 1 0 0.244
	deformvertexes move -3.09206e-015 4.36707e-016 0 sawtooth 1.28092e+015 1 0 0.244
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raiderssplash01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0 0.244
		alphagen wave square 0 1 0 0.244
		tcMod rotate 47
		tcMod stretch sin 0.7 0.7466 0.7066 0.244
	}
}

textures/runy9/zzfallssplashcote_1
{
	qer_editorimage textures/runy9/raiderssplash01.tga
	q3map_cloneshader textures/runy9/zzfallssplashcote_2
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 330 triangle 0 1 0.0156024 0.244
	deformvertexes move -3.05464e-015 6.48616e-016 0 sawtooth 2.24162e+015 1 0.0156024 0.244
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raiderssplash01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.0156024 0.244
		alphagen wave square 0 1 0.0156024 0.244
		tcMod rotate -108
		tcMod stretch sin 0.7 0.7466 0.722202 0.244
	}
}

textures/runy9/zzfallssplashcote_2
{
	qer_editorimage textures/runy9/raiderssplash01.tga
	q3map_cloneshader textures/runy9/zzfallssplashcote_3
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 330 triangle 0 1 0.0304273 0.244
	deformvertexes move -1.3138e-015 2.83293e-015 0 sawtooth 3.20231e+014 1 0.0304273 0.244
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raiderssplash01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.0304273 0.244
		alphagen wave square 0 1 0.0304273 0.244
		tcMod rotate 43
		tcMod stretch sin 0.7 0.7466 0.737027 0.244
	}
}

textures/runy9/zzfallssplashcote_3
{
	qer_editorimage textures/runy9/raiderssplash01.tga
	q3map_cloneshader textures/runy9/zzfallssplashcote_4
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 330 triangle 0 1 0.0449723 0.244
	deformvertexes move 2.25685e-015 -2.15828e-015 0 sawtooth 1.28092e+015 1 0.0449723 0.244
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raiderssplash01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.0449723 0.244
		alphagen wave square 0 1 0.0449723 0.244
		tcMod rotate 157
		tcMod stretch sin 0.7 0.7466 0.751572 0.244
	}
}

textures/runy9/zzfallssplashcote_4
{
	qer_editorimage textures/runy9/raiderssplash01.tga
	q3map_cloneshader textures/runy9/zzfallssplashcote_5
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 330 triangle 0 1 0.0593384 0.244
	deformvertexes move 1.98454e-015 -2.41104e-015 0 sawtooth -1.92139e+015 1 0.0593384 0.244
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raiderssplash01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.0593384 0.244
		alphagen wave square 0 1 0.0593384 0.244
		tcMod rotate -191
		tcMod stretch sin 0.7 0.7466 0.765938 0.244
	}
}

textures/runy9/zzfallssplashcote_5
{
	qer_editorimage textures/runy9/raiderssplash01.tga
	q3map_cloneshader textures/runy9/zzfallssplashcote_6
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 330 triangle 0 1 0.073573 0.244
	deformvertexes move 3.11562e-015 -2.10872e-016 0 sawtooth -2.56185e+015 1 0.073573 0.244
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raiderssplash01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.073573 0.244
		alphagen wave square 0 1 0.073573 0.244
		tcMod rotate -104
		tcMod stretch sin 0.7 0.7466 0.780173 0.244
	}
}

textures/runy9/zzfallssplashcote_6
{
	qer_editorimage textures/runy9/raiderssplash01.tga
	q3map_cloneshader textures/runy9/zzfallssplashcote_7
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 330 triangle 0 1 0.0877036 0.244
	deformvertexes move -3.12263e-015 2.72508e-017 0 sawtooth -3.20231e+014 1 0.0877036 0.244
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raiderssplash01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.0877036 0.244
		alphagen wave square 0 1 0.0877036 0.244
		tcMod rotate 210
		tcMod stretch sin 0.7 0.7466 0.794304 0.244
	}
}

textures/runy9/zzfallssplashcote_7
{
	qer_editorimage textures/runy9/raiderssplash01.tga
	q3map_cloneshader textures/runy9/zzfallssplashcote_8
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 330 triangle 0 1 0.101748 0.244
	deformvertexes move -2.73488e-015 1.50731e-015 0 sawtooth -2.56185e+015 1 0.101748 0.244
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raiderssplash01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.101748 0.244
		alphagen wave square 0 1 0.101748 0.244
		tcMod rotate 316
		tcMod stretch sin 0.7 0.7466 0.808348 0.244
	}
}

textures/runy9/zzfallssplashcote_8
{
	qer_editorimage textures/runy9/raiderssplash01.tga
	q3map_cloneshader textures/runy9/zzfallssplashcote_9
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 330 triangle 0 1 0.11572 0.244
	deformvertexes move 1.17733e-015 2.89231e-015 0 sawtooth -1.92139e+015 1 0.11572 0.244
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raiderssplash01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.11572 0.244
		alphagen wave square 0 1 0.11572 0.244
		tcMod rotate -79
		tcMod stretch sin 0.7 0.7466 0.82232 0.244
	}
}

textures/runy9/zzfallssplashcote_9
{
	qer_editorimage textures/runy9/raiderssplash01.tga
	q3map_cloneshader textures/runy9/zzfallssplashcote_10
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 330 triangle 0 1 0.129628 0.244
	deformvertexes move -5.50899e-016 3.07377e-015 0 sawtooth -2.24162e+015 1 0.129628 0.244
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raiderssplash01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.129628 0.244
		alphagen wave square 0 1 0.129628 0.244
		tcMod rotate -123
		tcMod stretch sin 0.7 0.7466 0.836228 0.244
	}
}

textures/runy9/zzfallssplashcote_10
{
	qer_editorimage textures/runy9/raiderssplash01.tga
	q3map_cloneshader textures/runy9/zzfallssplashcote_11
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 330 triangle 0 1 0.14348 0.244
	deformvertexes move -2.42981e-015 1.96152e-015 0 sawtooth 1.28092e+015 1 0.14348 0.244
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raiderssplash01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.14348 0.244
		alphagen wave square 0 1 0.14348 0.244
		tcMod rotate -73
		tcMod stretch sin 0.7 0.7466 0.85008 0.244
	}
}

textures/runy9/zzfallssplashcote_11
{
	qer_editorimage textures/runy9/raiderssplash01.tga
	q3map_cloneshader textures/runy9/zzfallssplashcote_12
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 330 triangle 0 1 0.157281 0.244
	deformvertexes move 2.97204e-015 -9.58396e-016 0 sawtooth 0 1 0.157281 0.244
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raiderssplash01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.157281 0.244
		alphagen wave square 0 1 0.157281 0.244
		tcMod rotate -144
		tcMod stretch sin 0.7 0.7466 0.863881 0.244
	}
}

textures/runy9/zzfallssplashcote_12
{
	qer_editorimage textures/runy9/raiderssplash01.tga
	q3map_cloneshader textures/runy9/zzfallssplashcote_13
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 330 triangle 0 1 0.171037 0.244
	deformvertexes move 2.73858e-015 1.50057e-015 0 sawtooth -3.20231e+014 1 0.171037 0.244
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raiderssplash01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.171037 0.244
		alphagen wave square 0 1 0.171037 0.244
		tcMod rotate 335
		tcMod stretch sin 0.7 0.7466 0.877637 0.244
	}
}

textures/runy9/zzfallssplashcote_13
{
	qer_editorimage textures/runy9/raiderssplash01.tga
	q3map_cloneshader textures/runy9/zzfallssplashcote_14
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 330 triangle 0 1 0.184751 0.244
	deformvertexes move 3.01524e-015 8.12332e-016 0 sawtooth -9.60693e+014 1 0.184751 0.244
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raiderssplash01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.184751 0.244
		alphagen wave square 0 1 0.184751 0.244
		tcMod rotate 274
		tcMod stretch sin 0.7 0.7466 0.891351 0.244
	}
}

textures/runy9/zzfallssplashcote_14
{
	qer_editorimage textures/runy9/raiderssplash01.tga
	q3map_cloneshader textures/runy9/zzfallssplashcote_15
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 330 triangle 0 1 0.198427 0.244
	deformvertexes move 1.36255e-017 3.12272e-015 0 sawtooth -9.60693e+014 1 0.198427 0.244
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raiderssplash01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.198427 0.244
		alphagen wave square 0 1 0.198427 0.244
		tcMod rotate 279
		tcMod stretch sin 0.7 0.7466 0.905027 0.244
	}
}

textures/runy9/zzfallssplashcote_15
{
	qer_editorimage textures/runy9/raiderssplash01.tga
	q3map_cloneshader textures/runy9/zzfallssplashcote_16
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 330 triangle 0 1 0.212067 0.244
	deformvertexes move 3.09098e-015 -4.44315e-016 0 sawtooth -1.92139e+015 1 0.212067 0.244
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raiderssplash01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.212067 0.244
		alphagen wave square 0 1 0.212067 0.244
		tcMod rotate 238
		tcMod stretch sin 0.7 0.7466 0.918667 0.244
	}
}

textures/runy9/zzfallssplashcote_16
{
	qer_editorimage textures/runy9/raiderssplash01.tga
	q3map_cloneshader textures/runy9/zzfallssplashcote_17
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 330 triangle 0 1 0.225674 0.244
	deformvertexes move -2.94173e-015 -1.04774e-015 0 sawtooth -1.28092e+015 1 0.225674 0.244
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raiderssplash01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.225674 0.244
		alphagen wave square 0 1 0.225674 0.244
		tcMod rotate 324
		tcMod stretch sin 0.7 0.7466 0.932274 0.244
	}
}

textures/runy9/zzfallssplashcote_17
{
	qer_editorimage textures/runy9/raiderssplash01.tga
	q3map_cloneshader textures/runy9/zzfallssplashcote_18
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 330 triangle 0 1 0.23925 0.244
	deformvertexes move -2.02047e-015 2.38102e-015 0 sawtooth -6.40462e+014 1 0.23925 0.244
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raiderssplash01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.23925 0.244
		alphagen wave square 0 1 0.23925 0.244
		tcMod rotate 196
		tcMod stretch sin 0.7 0.7466 0.94585 0.244
	}
}

textures/runy9/zzfallssplashcote_18
{
	qer_editorimage textures/runy9/raiderssplash01.tga
	q3map_cloneshader textures/runy9/zzfallssplashcote_19
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 330 triangle 0 1 0.252797 0.244
	deformvertexes move -3.10823e-015 3.00713e-016 0 sawtooth -3.20231e+014 1 0.252797 0.244
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raiderssplash01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.252797 0.244
		alphagen wave square 0 1 0.252797 0.244
		tcMod rotate 239
		tcMod stretch sin 0.7 0.7466 0.959397 0.244
	}
}

textures/runy9/zzfallssplashcote_19
{
	qer_editorimage textures/runy9/raiderssplash01.tga
	q3map_cloneshader textures/runy9/zzfallssplashcote_20
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 330 triangle 0 1 0.266316 0.244
	deformvertexes move -5.70147e-016 3.07026e-015 0 sawtooth 1.28092e+015 1 0.266316 0.244
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raiderssplash01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.266316 0.244
		alphagen wave square 0 1 0.266316 0.244
		tcMod rotate -163
		tcMod stretch sin 0.7 0.7466 0.972916 0.244
	}
}

textures/runy9/zzfallssplashcote_20
{
	qer_editorimage textures/runy9/raiderssplash01.tga
	q3map_cloneshader textures/runy9/zzfallssplashcote_21
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 330 triangle 0 1 0.27981 0.244
	deformvertexes move -4.15596e-016 3.09497e-015 0 sawtooth -6.40462e+014 1 0.27981 0.244
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raiderssplash01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.27981 0.244
		alphagen wave square 0 1 0.27981 0.244
		tcMod rotate 133
		tcMod stretch sin 0.7 0.7466 0.98641 0.244
	}
}

textures/runy9/zzfallssplashcote_21
{
	qer_editorimage textures/runy9/raiderssplash01.tga
	q3map_cloneshader textures/runy9/zzfallssplashcote_22
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 330 triangle 0 1 0.293279 0.244
	deformvertexes move 3.02133e-015 -7.89364e-016 0 sawtooth -6.40462e+014 1 0.293279 0.244
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raiderssplash01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.293279 0.244
		alphagen wave square 0 1 0.293279 0.244
		tcMod rotate -113
		tcMod stretch sin 0.7 0.7466 0.999879 0.244
	}
}

textures/runy9/zzfallssplashcote_22
{
	qer_editorimage textures/runy9/raiderssplash01.tga
	q3map_cloneshader textures/runy9/zzfallssplashcote_23
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 330 triangle 0 1 0.306725 0.244
	deformvertexes move -1.74479e-018 -3.12275e-015 0 sawtooth -6.40462e+014 1 0.306725 0.244
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raiderssplash01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.306725 0.244
		alphagen wave square 0 1 0.306725 0.244
		tcMod rotate -184
		tcMod stretch sin 0.7 0.7466 1.01333 0.244
	}
}

textures/runy9/zzfallssplashcote_23
{
	qer_editorimage textures/runy9/raiderssplash01.tga
	q3map_cloneshader textures/runy9/zzfallssplashcote_24
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 330 triangle 0 1 0.320149 0.244
	deformvertexes move -3.07272e-015 -5.56745e-016 0 sawtooth 0 1 0.320149 0.244
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raiderssplash01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.320149 0.244
		alphagen wave square 0 1 0.320149 0.244
		tcMod rotate -250
		tcMod stretch sin 0.7 0.7466 1.02675 0.244
	}
}

textures/runy9/zzfallssplashcote_24
{
	qer_editorimage textures/runy9/raiderssplash01.tga
	q3map_cloneshader textures/runy9/zzfallssplashcote_25
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 330 triangle 0 1 0.333551 0.244
	deformvertexes move 2.93915e-015 1.05497e-015 0 sawtooth 6.40462e+014 1 0.333551 0.244
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raiderssplash01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.333551 0.244
		alphagen wave square 0 1 0.333551 0.244
		tcMod rotate 269
		tcMod stretch sin 0.7 0.7466 1.04015 0.244
	}
}

textures/runy9/zzfallssplashcote_25
{
	qer_editorimage textures/runy9/raiderssplash01.tga
	q3map_cloneshader textures/runy9/zzfallssplashcote_26
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 330 triangle 0 1 0.346933 0.244
	deformvertexes move 3.03564e-015 -7.32435e-016 0 sawtooth 0 1 0.346933 0.244
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raiderssplash01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.346933 0.244
		alphagen wave square 0 1 0.346933 0.244
		tcMod rotate -275
		tcMod stretch sin 0.7 0.7466 1.05353 0.244
	}
}

textures/runy9/zzfallssplashcote_26
{
	qer_editorimage textures/runy9/raiderssplash01.tga
	q3map_cloneshader textures/runy9/zzfallssplashcote_27
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 330 triangle 0 1 0.360296 0.244
	deformvertexes move 2.47096e-015 1.90943e-015 0 sawtooth -1.28092e+015 1 0.360296 0.244
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raiderssplash01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.360296 0.244
		alphagen wave square 0 1 0.360296 0.244
		tcMod rotate -218
		tcMod stretch sin 0.7 0.7466 1.0669 0.244
	}
}

textures/runy9/zzfallssplashcote_27
{
	qer_editorimage textures/runy9/raiderssplash01.tga
	q3map_cloneshader textures/runy9/zzfallssplashcote_28
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 330 triangle 0 1 0.37364 0.244
	deformvertexes move -6.81046e-016 -3.04758e-015 0 sawtooth -2.24162e+015 1 0.37364 0.244
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raiderssplash01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.37364 0.244
		alphagen wave square 0 1 0.37364 0.244
		tcMod rotate 57
		tcMod stretch sin 0.7 0.7466 1.08024 0.244
	}
}

textures/runy9/zzfallssplashcote_28
{
	qer_editorimage textures/runy9/raiderssplash01.tga
	q3map_cloneshader textures/runy9/zzfallssplashcote_29
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 330 triangle 0 1 0.386966 0.244
	deformvertexes move 2.52051e-015 -1.84352e-015 0 sawtooth -2.24162e+015 1 0.386966 0.244
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raiderssplash01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.386966 0.244
		alphagen wave square 0 1 0.386966 0.244
		tcMod rotate 378
		tcMod stretch sin 0.7 0.7466 1.09357 0.244
	}
}

textures/runy9/zzfallssplashcote_29
{
	qer_editorimage textures/runy9/raiderssplash01.tga
	q3map_cloneshader textures/runy9/zzfallssplashcote_30
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 330 triangle 0 1 0.400274 0.244
	deformvertexes move 2.93248e-015 1.07337e-015 0 sawtooth -2.56185e+015 1 0.400274 0.244
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raiderssplash01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.400274 0.244
		alphagen wave square 0 1 0.400274 0.244
		tcMod rotate 371
		tcMod stretch sin 0.7 0.7466 1.10687 0.244
	}
}

textures/runy9/zzfallssplashcote_30
{
	qer_editorimage textures/runy9/raiderssplash01.tga
	q3map_cloneshader textures/runy9/zzfallssplashcote_31
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 330 triangle 0 1 0.413566 0.244
	deformvertexes move -2.76077e-015 -1.45935e-015 0 sawtooth 1.28092e+015 1 0.413566 0.244
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raiderssplash01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.413566 0.244
		alphagen wave square 0 1 0.413566 0.244
		tcMod rotate 124
		tcMod stretch sin 0.7 0.7466 1.12017 0.244
	}
}

textures/runy9/zzfallssplashcote_31
{
	qer_editorimage textures/runy9/raiderssplash01.tga
	q3map_cloneshader textures/runy9/zzfallssplashcote_32
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 330 triangle 0 1 0.426842 0.244
	deformvertexes move 2.37491e-015 -2.02765e-015 0 sawtooth 1.92139e+015 1 0.426842 0.244
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raiderssplash01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.426842 0.244
		alphagen wave square 0 1 0.426842 0.244
		tcMod rotate 403
		tcMod stretch sin 0.7 0.7466 1.13344 0.244
	}
}

textures/runy9/zzfallssplashcote_32
{
	qer_editorimage textures/runy9/raiderssplash01.tga
	q3map_cloneshader textures/runy9/zzfallssplashcote_33
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 330 triangle 0 1 0.440102 0.244
	deformvertexes move 3.10505e-015 3.31998e-016 0 sawtooth -1.92139e+015 1 0.440102 0.244
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raiderssplash01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.440102 0.244
		alphagen wave square 0 1 0.440102 0.244
		tcMod rotate -25
		tcMod stretch sin 0.7 0.7466 1.1467 0.244
	}
}

textures/runy9/zzfallssplashcote_33
{
	qer_editorimage textures/runy9/raiderssplash01.tga
	q3map_cloneshader textures/runy9/zzfallssplashcote_34
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 330 triangle 0 1 0.453347 0.244
	deformvertexes move 1.08615e-015 2.92777e-015 0 sawtooth 0 1 0.453347 0.244
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raiderssplash01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.453347 0.244
		alphagen wave square 0 1 0.453347 0.244
		tcMod rotate 112
		tcMod stretch sin 0.7 0.7466 1.15995 0.244
	}
}

textures/runy9/zzfallssplashcote_34
{
	qer_editorimage textures/runy9/raiderssplash01.tga
	q3map_cloneshader textures/runy9/zzfallssplashcote_35
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 330 triangle 0 1 0.466578 0.244
	deformvertexes move 1.93558e-015 2.45052e-015 0 sawtooth -2.56185e+015 1 0.466578 0.244
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raiderssplash01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.466578 0.244
		alphagen wave square 0 1 0.466578 0.244
		tcMod rotate 115
		tcMod stretch sin 0.7 0.7466 1.17318 0.244
	}
}

textures/runy9/zzfallssplashcote_35
{
	qer_editorimage textures/runy9/raiderssplash01.tga
	q3map_cloneshader textures/runy9/zzfallssplashcote_36
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 330 triangle 0 1 0.479794 0.244
	deformvertexes move -7.19183e-016 -3.0388e-015 0 sawtooth -6.40462e+014 1 0.479794 0.244
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raiderssplash01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.479794 0.244
		alphagen wave square 0 1 0.479794 0.244
		tcMod rotate -146
		tcMod stretch sin 0.7 0.7466 1.18639 0.244
	}
}

textures/runy9/zzfallssplashcote_36
{
	qer_editorimage textures/runy9/raiderssplash01.tga
	q3map_cloneshader textures/runy9/zzfallssplashcote_37
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 330 triangle 0 1 0.492997 0.244
	deformvertexes move -1.07894e-015 2.93043e-015 0 sawtooth 2.24162e+015 1 0.492997 0.244
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raiderssplash01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.492997 0.244
		alphagen wave square 0 1 0.492997 0.244
		tcMod rotate 59
		tcMod stretch sin 0.7 0.7466 1.1996 0.244
	}
}

textures/runy9/zzfallssplashcote_37
{
	qer_editorimage textures/runy9/raiderssplash01.tga
	q3map_cloneshader textures/runy9/zzfallssplashcote_38
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 330 triangle 0 1 0.506186 0.244
	deformvertexes move 2.86732e-015 1.23694e-015 0 sawtooth -9.60693e+014 1 0.506186 0.244
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raiderssplash01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.506186 0.244
		alphagen wave square 0 1 0.506186 0.244
		tcMod rotate 120
		tcMod stretch sin 0.7 0.7466 1.21279 0.244
	}
}

textures/runy9/zzfallssplashcote_38
{
	qer_editorimage textures/runy9/raiderssplash01.tga
	q3map_cloneshader textures/runy9/zzfallssplashcote_39
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 330 triangle 0 1 0.519362 0.244
	deformvertexes move -2.63513e-015 1.6756e-015 0 sawtooth -2.24162e+015 1 0.519362 0.244
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raiderssplash01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.519362 0.244
		alphagen wave square 0 1 0.519362 0.244
		tcMod rotate 331
		tcMod stretch sin 0.7 0.7466 1.22596 0.244
	}
}

textures/runy9/zzfallssplashcote_39
{
	qer_editorimage textures/runy9/raiderssplash01.tga
	q3map_cloneshader textures/runy9/zzfallssplashcote_40
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 330 triangle 0 1 0.532526 0.244
	deformvertexes move 3.45544e-016 3.10357e-015 0 sawtooth -1.60115e+015 1 0.532526 0.244
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raiderssplash01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.532526 0.244
		alphagen wave square 0 1 0.532526 0.244
		tcMod rotate -216
		tcMod stretch sin 0.7 0.7466 1.23913 0.244
	}
}

textures/runy9/zzfallssplashcote_40
{
	qer_editorimage textures/runy9/raiderssplash01.tga
	q3map_cloneshader textures/runy9/zzfallssplashcote_41
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 330 triangle 0 1 0.545677 0.244
	deformvertexes move -1.2782e-015 2.84917e-015 0 sawtooth 9.60693e+014 1 0.545677 0.244
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raiderssplash01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.545677 0.244
		alphagen wave square 0 1 0.545677 0.244
		tcMod rotate 48
		tcMod stretch sin 0.7 0.7466 1.25228 0.244
	}
}

textures/runy9/zzfallssplashcote_41
{
	qer_editorimage textures/runy9/raiderssplash01.tga
	q3map_cloneshader textures/runy9/zzfallssplashcote_42
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 330 triangle 0 1 0.558817 0.244
	deformvertexes move 6.01036e-016 -3.06436e-015 0 sawtooth 9.60693e+014 1 0.558817 0.244
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raiderssplash01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.558817 0.244
		alphagen wave square 0 1 0.558817 0.244
		tcMod rotate -255
		tcMod stretch sin 0.7 0.7466 1.26542 0.244
	}
}

textures/runy9/zzfallssplashcote_42
{
	qer_editorimage textures/runy9/raiderssplash01.tga
	q3map_cloneshader textures/runy9/zzfallssplashcote_43
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 330 triangle 0 1 0.571945 0.244
	deformvertexes move 2.83718e-015 -1.3046e-015 0 sawtooth 1.92139e+015 1 0.571945 0.244
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raiderssplash01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.571945 0.244
		alphagen wave square 0 1 0.571945 0.244
		tcMod rotate 65
		tcMod stretch sin 0.7 0.7466 1.27854 0.244
	}
}

textures/runy9/zzfallssplashcote_43
{
	qer_editorimage textures/runy9/raiderssplash01.tga
	q3map_cloneshader textures/runy9/zzfallssplashcote_44
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 330 triangle 0 1 0.585061 0.244
	deformvertexes move 2.28372e-015 -2.12983e-015 0 sawtooth 6.40462e+014 1 0.585061 0.244
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raiderssplash01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.585061 0.244
		alphagen wave square 0 1 0.585061 0.244
		tcMod rotate 39
		tcMod stretch sin 0.7 0.7466 1.29166 0.244
	}
}

textures/runy9/zzfallssplashcote_44
{
	qer_editorimage textures/runy9/raiderssplash01.tga
	q3map_cloneshader textures/runy9/zzfallssplashcote_45
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 330 triangle 0 1 0.598166 0.244
	deformvertexes move 1.79439e-015 2.55572e-015 0 sawtooth 9.60693e+014 1 0.598166 0.244
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raiderssplash01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.598166 0.244
		alphagen wave square 0 1 0.598166 0.244
		tcMod rotate 87
		tcMod stretch sin 0.7 0.7466 1.30477 0.244
	}
}

textures/runy9/zzfallssplashcote_45
{
	qer_editorimage textures/runy9/raiderssplash01.tga
	q3map_cloneshader textures/runy9/zzfallssplashcote_46
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 330 triangle 0 1 0.611261 0.244
	deformvertexes move 2.50641e-015 1.86265e-015 0 sawtooth 1.60115e+015 1 0.611261 0.244
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raiderssplash01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.611261 0.244
		alphagen wave square 0 1 0.611261 0.244
		tcMod rotate 60
		tcMod stretch sin 0.7 0.7466 1.31786 0.244
	}
}

textures/runy9/zzfallssplashcote_46
{
	qer_editorimage textures/runy9/raiderssplash01.tga
	q3map_cloneshader textures/runy9/zzfallssplashcote_47
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 330 triangle 0 1 0.624345 0.244
	deformvertexes move 3.10936e-015 -2.88885e-016 0 sawtooth 1.92139e+015 1 0.624345 0.244
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raiderssplash01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.624345 0.244
		alphagen wave square 0 1 0.624345 0.244
		tcMod rotate -175
		tcMod stretch sin 0.7 0.7466 1.33094 0.244
	}
}

textures/runy9/zzfallssplashcote_47
{
	qer_editorimage textures/runy9/raiderssplash01.tga
	q3map_cloneshader textures/runy9/zzfallssplashcote_48
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 330 triangle 0 1 0.637418 0.244
	deformvertexes move -1.6207e-015 -2.66925e-015 0 sawtooth 6.40462e+014 1 0.637418 0.244
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raiderssplash01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.637418 0.244
		alphagen wave square 0 1 0.637418 0.244
		tcMod rotate 187
		tcMod stretch sin 0.7 0.7466 1.34402 0.244
	}
}

textures/runy9/zzfallssplashcote_48
{
	qer_editorimage textures/runy9/raiderssplash01.tga
	q3map_cloneshader textures/runy9/zzfallssplashcote_49
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 330 triangle 0 1 0.650482 0.244
	deformvertexes move 9.23422e-016 -2.98309e-015 0 sawtooth 6.40462e+014 1 0.650482 0.244
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raiderssplash01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.650482 0.244
		alphagen wave square 0 1 0.650482 0.244
		tcMod rotate -278
		tcMod stretch sin 0.7 0.7466 1.35708 0.244
	}
}

textures/runy9/zzfallssplashcote_49
{
	qer_editorimage textures/runy9/raiderssplash01.tga
	q3map_cloneshader textures/runy9/zzfallssplashcote_50
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 330 triangle 0 1 0.663535 0.244
	deformvertexes move -2.83219e-015 1.31538e-015 0 sawtooth -3.20231e+014 1 0.663535 0.244
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raiderssplash01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.663535 0.244
		alphagen wave square 0 1 0.663535 0.244
		tcMod rotate 231
		tcMod stretch sin 0.7 0.7466 1.37014 0.244
	}
}

textures/runy9/zzfallssplashcote_50
{
	qer_editorimage textures/runy9/raiderssplash01.tga
	q3map_cloneshader textures/runy9/zzfallssplashcote_51
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 330 triangle 0 1 0.676579 0.244
	deformvertexes move -3.01213e-015 -8.23799e-016 0 sawtooth -2.24162e+015 1 0.676579 0.244
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raiderssplash01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.676579 0.244
		alphagen wave square 0 1 0.676579 0.244
		tcMod rotate 79
		tcMod stretch sin 0.7 0.7466 1.38318 0.244
	}
}

textures/runy9/zzfallssplashcote_51
{
	qer_editorimage textures/runy9/raiderssplash01.tga
	q3map_cloneshader textures/runy9/zzfallssplashcote_52
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 330 triangle 0 1 0.689613 0.244
	deformvertexes move -2.78771e-015 -1.4072e-015 0 sawtooth -1.60115e+015 1 0.689613 0.244
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raiderssplash01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.689613 0.244
		alphagen wave square 0 1 0.689613 0.244
		tcMod rotate -155
		tcMod stretch sin 0.7 0.7466 1.39621 0.244
	}
}

textures/runy9/zzfallssplashcote_52
{
	qer_editorimage textures/runy9/raiderssplash01.tga
	q3map_cloneshader textures/runy9/zzfallssplashcote_53
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 330 triangle 0 1 0.702638 0.244
	deformvertexes move 2.24329e-015 -2.17238e-015 0 sawtooth -1.92139e+015 1 0.702638 0.244
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raiderssplash01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.702638 0.244
		alphagen wave square 0 1 0.702638 0.244
		tcMod rotate 339
		tcMod stretch sin 0.7 0.7466 1.40924 0.244
	}
}

textures/runy9/zzfallssplashcote_53
{
	qer_editorimage textures/runy9/raiderssplash01.tga
	q3map_cloneshader textures/runy9/zzfallssplashcote_54
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 330 triangle 0 1 0.715654 0.244
	deformvertexes move -3.07272e-015 -5.56745e-016 0 sawtooth -2.56185e+015 1 0.715654 0.244
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raiderssplash01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.715654 0.244
		alphagen wave square 0 1 0.715654 0.244
		tcMod rotate 33
		tcMod stretch sin 0.7 0.7466 1.42225 0.244
	}
}

textures/runy9/zzfallssplashcote_54
{
	qer_editorimage textures/runy9/raiderssplash01.tga
	q3map_cloneshader textures/runy9/zzfallssplashcote_55
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 330 triangle 0 1 0.728661 0.244
	deformvertexes move -2.47565e-015 -1.90334e-015 0 sawtooth -9.60693e+014 1 0.728661 0.244
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raiderssplash01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.728661 0.244
		alphagen wave square 0 1 0.728661 0.244
		tcMod rotate -190
		tcMod stretch sin 0.7 0.7466 1.43526 0.244
	}
}

textures/runy9/zzfallssplashcote_55
{
	qer_editorimage textures/runy9/raiderssplash01.tga
	q3map_cloneshader textures/runy9/zzfallssplashcote_56
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 330 triangle 0 1 0.741659 0.244
	deformvertexes move -3.11709e-015 -1.87864e-016 0 sawtooth 3.20231e+014 1 0.741659 0.244
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raiderssplash01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.741659 0.244
		alphagen wave square 0 1 0.741659 0.244
		tcMod rotate 359
		tcMod stretch sin 0.7 0.7466 1.44826 0.244
	}
}

textures/runy9/zzfallssplashcote_56
{
	qer_editorimage textures/runy9/raiderssplash01.tga
	q3map_cloneshader textures/runy9/zzfallssplashcote_57
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 330 triangle 0 1 0.754649 0.244
	deformvertexes move -2.36718e-015 2.03667e-015 0 sawtooth 3.20231e+014 1 0.754649 0.244
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raiderssplash01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.754649 0.244
		alphagen wave square 0 1 0.754649 0.244
		tcMod rotate -84
		tcMod stretch sin 0.7 0.7466 1.46125 0.244
	}
}

textures/runy9/zzfallssplashcote_57
{
	qer_editorimage textures/runy9/raiderssplash01.tga
	q3map_cloneshader textures/runy9/zzfallssplashcote_58
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 330 triangle 0 1 0.76763 0.244
	deformvertexes move 1.76222e-015 2.578e-015 0 sawtooth 9.60693e+014 1 0.76763 0.244
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raiderssplash01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.76763 0.244
		alphagen wave square 0 1 0.76763 0.244
		tcMod rotate -162
		tcMod stretch sin 0.7 0.7466 1.47423 0.244
	}
}

textures/runy9/zzfallssplashcote_58
{
	qer_editorimage textures/runy9/raiderssplash01.tga
	q3map_cloneshader textures/runy9/zzfallssplashcote_59
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 330 triangle 0 1 0.780603 0.244
	deformvertexes move 3.0875e-015 4.67823e-016 0 sawtooth -9.60693e+014 1 0.780603 0.244
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raiderssplash01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.780603 0.244
		alphagen wave square 0 1 0.780603 0.244
		tcMod rotate 240
		tcMod stretch sin 0.7 0.7466 1.4872 0.244
	}
}

textures/runy9/zzfallssplashcote_59
{
	qer_editorimage textures/runy9/raiderssplash01.tga
	q3map_cloneshader textures/runy9/zzfallssplashcote_60
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 330 triangle 0 1 0.793568 0.244
	deformvertexes move -4.3498e-016 3.0923e-015 0 sawtooth 6.40462e+014 1 0.793568 0.244
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raiderssplash01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.793568 0.244
		alphagen wave square 0 1 0.793568 0.244
		tcMod rotate -35
		tcMod stretch sin 0.7 0.7466 1.50017 0.244
	}
}

textures/runy9/zzfallssplashcote_60
{
	qer_editorimage textures/runy9/raiderssplash01.tga
	q3map_cloneshader textures/runy9/zzfallssplashcote_61
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 330 triangle 0 1 0.806524 0.244
	deformvertexes move 1.08615e-015 2.92777e-015 0 sawtooth 3.20231e+014 1 0.806524 0.244
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raiderssplash01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.806524 0.244
		alphagen wave square 0 1 0.806524 0.244
		tcMod rotate -282
		tcMod stretch sin 0.7 0.7466 1.51312 0.244
	}
}

textures/runy9/zzfallssplashcote_61
{
	qer_editorimage textures/runy9/raiderssplash01.tga
	q3map_cloneshader textures/runy9/zzfallssplashcote_62
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 330 triangle 0 1 0.819473 0.244
	deformvertexes move -2.92152e-015 -1.10284e-015 0 sawtooth 1.60115e+015 1 0.819473 0.244
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raiderssplash01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.819473 0.244
		alphagen wave square 0 1 0.819473 0.244
		tcMod rotate 171
		tcMod stretch sin 0.7 0.7466 1.52607 0.244
	}
}

textures/runy9/zzfallssplashcote_62
{
	qer_editorimage textures/runy9/raiderssplash01.tga
	q3map_cloneshader textures/runy9/zzfallssplashcote_63
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 330 triangle 0 1 0.832414 0.244
	deformvertexes move -2.01464e-016 3.11624e-015 0 sawtooth 0 1 0.832414 0.244
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raiderssplash01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.832414 0.244
		alphagen wave square 0 1 0.832414 0.244
		tcMod rotate 304
		tcMod stretch sin 0.7 0.7466 1.53901 0.244
	}
}

textures/runy9/zzfallssplashcote_63
{
	qer_editorimage textures/runy9/raiderssplash01.tga
	q3map_cloneshader textures/runy9/zzfallssplashcote_64
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 330 triangle 0 1 0.845348 0.244
	deformvertexes move -1.26032e-015 2.85712e-015 0 sawtooth 1.60115e+015 1 0.845348 0.244
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raiderssplash01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.845348 0.244
		alphagen wave square 0 1 0.845348 0.244
		tcMod rotate 139
		tcMod stretch sin 0.7 0.7466 1.55195 0.244
	}
}

textures/runy9/zzfallssplashcote_64
{
	qer_editorimage textures/runy9/raiderssplash01.tga
	q3map_cloneshader textures/runy9/zzfallssplashcote_65
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 330 triangle 0 1 0.858274 0.244
	deformvertexes move 3.49714e-016 -3.1031e-015 0 sawtooth -1.60115e+015 1 0.858274 0.244
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raiderssplash01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.858274 0.244
		alphagen wave square 0 1 0.858274 0.244
		tcMod rotate 286
		tcMod stretch sin 0.7 0.7466 1.56487 0.244
	}
}

textures/runy9/zzfallssplashcote_65
{
	qer_editorimage textures/runy9/raiderssplash01.tga
	q3map_cloneshader textures/runy9/zzfallssplashcote_66
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 330 triangle 0 1 0.871193 0.244
	deformvertexes move -1.75587e-015 2.58233e-015 0 sawtooth -1.28092e+015 1 0.871193 0.244
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raiderssplash01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.871193 0.244
		alphagen wave square 0 1 0.871193 0.244
		tcMod rotate 261
		tcMod stretch sin 0.7 0.7466 1.57779 0.244
	}
}

textures/runy9/zzfallssplashcote_66
{
	qer_editorimage textures/runy9/raiderssplash01.tga
	q3map_cloneshader textures/runy9/zzfallssplashcote_67
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 330 triangle 0 1 0.884104 0.244
	deformvertexes move 2.08523e-015 2.32451e-015 0 sawtooth -3.20231e+014 1 0.884104 0.244
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raiderssplash01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.884104 0.244
		alphagen wave square 0 1 0.884104 0.244
		tcMod rotate 156
		tcMod stretch sin 0.7 0.7466 1.5907 0.244
	}
}

textures/runy9/zzfallssplashcote_67
{
	qer_editorimage textures/runy9/raiderssplash01.tga
	q3map_cloneshader textures/runy9/zzfallssplashcote_68
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 330 triangle 0 1 0.897009 0.244
	deformvertexes move 3.06102e-015 -6.1782e-016 0 sawtooth 1.28092e+015 1 0.897009 0.244
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raiderssplash01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.897009 0.244
		alphagen wave square 0 1 0.897009 0.244
		tcMod rotate 199
		tcMod stretch sin 0.7 0.7466 1.60361 0.244
	}
}

textures/runy9/zzfallssplashcote_68
{
	qer_editorimage textures/runy9/raiderssplash01.tga
	q3map_cloneshader textures/runy9/zzfallssplashcote_69
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 330 triangle 0 1 0.909906 0.244
	deformvertexes move 1.5296e-015 2.72248e-015 0 sawtooth -1.28092e+015 1 0.909906 0.244
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raiderssplash01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.909906 0.244
		alphagen wave square 0 1 0.909906 0.244
		tcMod rotate 302
		tcMod stretch sin 0.7 0.7466 1.61651 0.244
	}
}

textures/runy9/zzfallssplashcote_69
{
	qer_editorimage textures/runy9/raiderssplash01.tga
	q3map_cloneshader textures/runy9/zzfallssplashcote_70
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 330 triangle 0 1 0.922797 0.244
	deformvertexes move -3.00157e-015 -8.61479e-016 0 sawtooth -6.40462e+014 1 0.922797 0.244
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raiderssplash01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.922797 0.244
		alphagen wave square 0 1 0.922797 0.244
		tcMod rotate 406
		tcMod stretch sin 0.7 0.7466 1.6294 0.244
	}
}

textures/runy9/zzfallssplashcote_70
{
	qer_editorimage textures/runy9/raiderssplash01.tga
	q3map_cloneshader textures/runy9/zzfallssplashcote_71
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 330 triangle 0 1 0.93568 0.244
	deformvertexes move 3.05215e-015 6.60233e-016 0 sawtooth 2.24162e+015 1 0.93568 0.244
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raiderssplash01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.93568 0.244
		alphagen wave square 0 1 0.93568 0.244
		tcMod rotate -233
		tcMod stretch sin 0.7 0.7466 1.64228 0.244
	}
}

textures/runy9/zzfallssplashcote_71
{
	qer_editorimage textures/runy9/raiderssplash01.tga
	q3map_cloneshader textures/runy9/zzfallssplashcote_72
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 330 triangle 0 1 0.948557 0.244
	deformvertexes move -3.11176e-015 2.61739e-016 0 sawtooth -1.28092e+015 1 0.948557 0.244
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raiderssplash01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.948557 0.244
		alphagen wave square 0 1 0.948557 0.244
		tcMod rotate 377
		tcMod stretch sin 0.7 0.7466 1.65516 0.244
	}
}

textures/runy9/zzfallssplashcote_72
{
	qer_editorimage textures/runy9/raiderssplash01.tga
	q3map_cloneshader textures/runy9/zzfallssplashcote_73
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 330 triangle 0 1 0.961428 0.244
	deformvertexes move 9.42094e-016 -2.97725e-015 0 sawtooth 3.20231e+014 1 0.961428 0.244
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raiderssplash01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.961428 0.244
		alphagen wave square 0 1 0.961428 0.244
		tcMod rotate 49
		tcMod stretch sin 0.7 0.7466 1.66803 0.244
	}
}

textures/runy9/zzfallssplashcote_73
{
	qer_editorimage textures/runy9/raiderssplash01.tga
	q3map_cloneshader textures/runy9/zzfallssplashcote_74
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 330 triangle 0 1 0.974291 0.244
	deformvertexes move 1.61412e-015 2.67323e-015 0 sawtooth 3.20231e+014 1 0.974291 0.244
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raiderssplash01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.974291 0.244
		alphagen wave square 0 1 0.974291 0.244
		tcMod rotate 32
		tcMod stretch sin 0.7 0.7466 1.68089 0.244
	}
}

textures/runy9/zzfallssplashcote_74
{
	qer_editorimage textures/runy9/raiderssplash01.tga
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 330 triangle 0 1 0.987149 0.244
	deformvertexes move 3.1225e-015 3.91316e-017 0 sawtooth 3.20231e+014 1 0.987149 0.244
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raiderssplash01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.987149 0.244
		alphagen wave square 0 1 0.987149 0.244
		tcMod rotate -194
		tcMod stretch sin 0.7 0.7466 1.69375 0.244
	}
}

