// Generated by Frozen Sand Particle Studio
// Mon Nov 16 23:21:40 2009


textures/runy9/fallssplash
{
	qer_editorimage textures/runy9/raiderssplash01.tga
	q3map_cloneshader textures/runy9/zzfallssplash_1
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 45 sawtooth 0 1 0 0.946
	deformvertexes move -10.8697 -40.5691 0 square 0 1 0 0.946
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raiderssplash01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0 0.946
		alphagen wave square 0 1 0 0.946
		tcMod rotate 16
		tcMod stretch sin 0.7 0.7466 0 0.946
	}
}

textures/runy9/zzfallssplash_1
{
	qer_editorimage textures/runy9/raiderssplash01.tga
	q3map_cloneshader textures/runy9/zzfallssplash_2
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 45 sawtooth 0 1 0.0285927 0.946
	deformvertexes move 36.2493 -7.41521 0 square 0 1 0.0285927 0.946
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raiderssplash01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.0285927 0.946
		alphagen wave square 0 1 0.0285927 0.946
		tcMod rotate -19
		tcMod stretch sin 0.7 0.7466 0.0285927 0.946
	}
}

textures/runy9/zzfallssplash_2
{
	qer_editorimage textures/runy9/raiderssplash01.tga
	q3map_cloneshader textures/runy9/zzfallssplash_3
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 45 sawtooth 0 1 0.0557606 0.946
	deformvertexes move -3.47723 -33.8217 0 square 0 1 0.0557606 0.946
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raiderssplash01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.0557606 0.946
		alphagen wave square 0 1 0.0557606 0.946
		tcMod rotate 13
		tcMod stretch sin 0.7 0.7466 0.0557606 0.946
	}
}

textures/runy9/zzfallssplash_3
{
	qer_editorimage textures/runy9/raiderssplash01.tga
	q3map_cloneshader textures/runy9/zzfallssplash_4
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 45 sawtooth 0 1 0.0824155 0.946
	deformvertexes move 3.21436 -31.8382 0 square 0 1 0.0824155 0.946
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raiderssplash01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.0824155 0.946
		alphagen wave square 0 1 0.0824155 0.946
		tcMod rotate 18
		tcMod stretch sin 0.7 0.7466 0.0824155 0.946
	}
}

textures/runy9/zzfallssplash_4
{
	qer_editorimage textures/runy9/raiderssplash01.tga
	q3map_cloneshader textures/runy9/zzfallssplash_5
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 45 sawtooth 0 1 0.108743 0.946
	deformvertexes move -23.8815 -32.0885 0 square 0 1 0.108743 0.946
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raiderssplash01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.108743 0.946
		alphagen wave square 0 1 0.108743 0.946
		tcMod rotate 3
		tcMod stretch sin 0.7 0.7466 0.108743 0.946
	}
}

textures/runy9/zzfallssplash_5
{
	qer_editorimage textures/runy9/raiderssplash01.tga
	q3map_cloneshader textures/runy9/zzfallssplash_6
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 45 sawtooth 0 1 0.134829 0.946
	deformvertexes move -25.9734 -69.292 0 square 0 1 0.134829 0.946
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raiderssplash01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.134829 0.946
		alphagen wave square 0 1 0.134829 0.946
		tcMod rotate 14
		tcMod stretch sin 0.7 0.7466 0.134829 0.946
	}
}

textures/runy9/zzfallssplash_6
{
	qer_editorimage textures/runy9/raiderssplash01.tga
	q3map_cloneshader textures/runy9/zzfallssplash_7
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 45 sawtooth 0 1 0.160724 0.946
	deformvertexes move -36.1969 -11.5665 0 square 0 1 0.160724 0.946
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raiderssplash01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.160724 0.946
		alphagen wave square 0 1 0.160724 0.946
		tcMod rotate 22
		tcMod stretch sin 0.7 0.7466 0.160724 0.946
	}
}

textures/runy9/zzfallssplash_7
{
	qer_editorimage textures/runy9/raiderssplash01.tga
	q3map_cloneshader textures/runy9/zzfallssplash_8
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 45 sawtooth 0 1 0.186462 0.946
	deformvertexes move 61.4553 -29.1075 0 square 0 1 0.186462 0.946
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raiderssplash01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.186462 0.946
		alphagen wave square 0 1 0.186462 0.946
		tcMod rotate -19
		tcMod stretch sin 0.7 0.7466 0.186462 0.946
	}
}

textures/runy9/zzfallssplash_8
{
	qer_editorimage textures/runy9/raiderssplash01.tga
	q3map_cloneshader textures/runy9/zzfallssplash_9
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 45 sawtooth 0 1 0.212067 0.946
	deformvertexes move -24.9333 -24.5627 0 square 0 1 0.212067 0.946
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raiderssplash01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.212067 0.946
		alphagen wave square 0 1 0.212067 0.946
		tcMod rotate 16
		tcMod stretch sin 0.7 0.7466 0.212067 0.946
	}
}

textures/runy9/zzfallssplash_9
{
	qer_editorimage textures/runy9/raiderssplash01.tga
	q3map_cloneshader textures/runy9/zzfallssplash_10
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 45 sawtooth 0 1 0.237554 0.946
	deformvertexes move -71.2115 -16.06 0 square 0 1 0.237554 0.946
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raiderssplash01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.237554 0.946
		alphagen wave square 0 1 0.237554 0.946
		tcMod rotate -5
		tcMod stretch sin 0.7 0.7466 0.237554 0.946
	}
}

textures/runy9/zzfallssplash_10
{
	qer_editorimage textures/runy9/raiderssplash01.tga
	q3map_cloneshader textures/runy9/zzfallssplash_11
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 45 sawtooth 0 1 0.262939 0.946
	deformvertexes move -3.06815 -29.8427 0 square 0 1 0.262939 0.946
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raiderssplash01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.262939 0.946
		alphagen wave square 0 1 0.262939 0.946
		tcMod rotate -10
		tcMod stretch sin 0.7 0.7466 0.262939 0.946
	}
}

textures/runy9/zzfallssplash_11
{
	qer_editorimage textures/runy9/raiderssplash01.tga
	q3map_cloneshader textures/runy9/zzfallssplash_12
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 45 sawtooth 0 1 0.288231 0.946
	deformvertexes move -61.9914 -34.6132 0 square 0 1 0.288231 0.946
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raiderssplash01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.288231 0.946
		alphagen wave square 0 1 0.288231 0.946
		tcMod rotate 17
		tcMod stretch sin 0.7 0.7466 0.288231 0.946
	}
}

textures/runy9/zzfallssplash_12
{
	qer_editorimage textures/runy9/raiderssplash01.tga
	q3map_cloneshader textures/runy9/zzfallssplash_13
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 45 sawtooth 0 1 0.31344 0.946
	deformvertexes move 15.3725 -25.7621 0 square 0 1 0.31344 0.946
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raiderssplash01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.31344 0.946
		alphagen wave square 0 1 0.31344 0.946
		tcMod rotate 18
		tcMod stretch sin 0.7 0.7466 0.31344 0.946
	}
}

textures/runy9/zzfallssplash_13
{
	qer_editorimage textures/runy9/raiderssplash01.tga
	q3map_cloneshader textures/runy9/zzfallssplash_14
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 45 sawtooth 0 1 0.338572 0.946
	deformvertexes move -44.4931 -57.8737 0 square 0 1 0.338572 0.946
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raiderssplash01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.338572 0.946
		alphagen wave square 0 1 0.338572 0.946
		tcMod rotate -15
		tcMod stretch sin 0.7 0.7466 0.338572 0.946
	}
}

textures/runy9/zzfallssplash_14
{
	qer_editorimage textures/runy9/raiderssplash01.tga
	q3map_cloneshader textures/runy9/zzfallssplash_15
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 45 sawtooth 0 1 0.363634 0.946
	deformvertexes move 22.7888 -46.7405 0 square 0 1 0.363634 0.946
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raiderssplash01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.363634 0.946
		alphagen wave square 0 1 0.363634 0.946
		tcMod rotate 16
		tcMod stretch sin 0.7 0.7466 0.363634 0.946
	}
}

textures/runy9/zzfallssplash_15
{
	qer_editorimage textures/runy9/raiderssplash01.tga
	q3map_cloneshader textures/runy9/zzfallssplash_16
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 45 sawtooth 0 1 0.38863 0.946
	deformvertexes move -57.9975 -0.543595 0 square 0 1 0.38863 0.946
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raiderssplash01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.38863 0.946
		alphagen wave square 0 1 0.38863 0.946
		tcMod stretch sin 0.7 0.7466 0.38863 0.946
	}
}

textures/runy9/zzfallssplash_16
{
	qer_editorimage textures/runy9/raiderssplash01.tga
	q3map_cloneshader textures/runy9/zzfallssplash_17
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 45 sawtooth 0 1 0.413566 0.946
	deformvertexes move 70.9556 -12.2192 0 square 0 1 0.413566 0.946
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raiderssplash01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.413566 0.946
		alphagen wave square 0 1 0.413566 0.946
		tcMod rotate -24
		tcMod stretch sin 0.7 0.7466 0.413566 0.946
	}
}

textures/runy9/zzfallssplash_17
{
	qer_editorimage textures/runy9/raiderssplash01.tga
	q3map_cloneshader textures/runy9/zzfallssplash_18
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 45 sawtooth 0 1 0.438445 0.946
	deformvertexes move 58.2354 -9.46756 0 square 0 1 0.438445 0.946
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raiderssplash01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.438445 0.946
		alphagen wave square 0 1 0.438445 0.946
		tcMod rotate -3
		tcMod stretch sin 0.7 0.7466 0.438445 0.946
	}
}

textures/runy9/zzfallssplash_18
{
	qer_editorimage textures/runy9/raiderssplash01.tga
	q3map_cloneshader textures/runy9/zzfallssplash_19
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 45 sawtooth 0 1 0.463271 0.946
	deformvertexes move -53.0411 -20.8721 0 square 0 1 0.463271 0.946
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raiderssplash01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.463271 0.946
		alphagen wave square 0 1 0.463271 0.946
		tcMod rotate -14
		tcMod stretch sin 0.7 0.7466 0.463271 0.946
	}
}

textures/runy9/zzfallssplash_19
{
	qer_editorimage textures/runy9/raiderssplash01.tga
	q3map_cloneshader textures/runy9/zzfallssplash_20
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 45 sawtooth 0 1 0.488047 0.946
	deformvertexes move -50.3782 -52.8303 0 square 0 1 0.488047 0.946
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raiderssplash01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.488047 0.946
		alphagen wave square 0 1 0.488047 0.946
		tcMod rotate 20
		tcMod stretch sin 0.7 0.7466 0.488047 0.946
	}
}

textures/runy9/zzfallssplash_20
{
	qer_editorimage textures/runy9/raiderssplash01.tga
	q3map_cloneshader textures/runy9/zzfallssplash_21
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 45 sawtooth 0 1 0.512776 0.946
	deformvertexes move 53.4818 -27.1974 0 square 0 1 0.512776 0.946
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raiderssplash01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.512776 0.946
		alphagen wave square 0 1 0.512776 0.946
		tcMod rotate 15
		tcMod stretch sin 0.7 0.7466 0.512776 0.946
	}
}

textures/runy9/zzfallssplash_21
{
	qer_editorimage textures/runy9/raiderssplash01.tga
	q3map_cloneshader textures/runy9/zzfallssplash_22
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 45 sawtooth 0 1 0.537459 0.946
	deformvertexes move 28.1639 -25.5106 0 square 0 1 0.537459 0.946
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raiderssplash01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.537459 0.946
		alphagen wave square 0 1 0.537459 0.946
		tcMod rotate -17
		tcMod stretch sin 0.7 0.7466 0.537459 0.946
	}
}

textures/runy9/zzfallssplash_22
{
	qer_editorimage textures/runy9/raiderssplash01.tga
	q3map_cloneshader textures/runy9/zzfallssplash_23
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 45 sawtooth 0 1 0.5621 0.946
	deformvertexes move 18.5468 -33.1665 0 square 0 1 0.5621 0.946
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raiderssplash01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.5621 0.946
		alphagen wave square 0 1 0.5621 0.946
		tcMod rotate -25
		tcMod stretch sin 0.7 0.7466 0.5621 0.946
	}
}

textures/runy9/zzfallssplash_23
{
	qer_editorimage textures/runy9/raiderssplash01.tga
	q3map_cloneshader textures/runy9/zzfallssplash_24
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 45 sawtooth 0 1 0.5867 0.946
	deformvertexes move 68.1774 -31.2544 0 square 0 1 0.5867 0.946
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raiderssplash01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.5867 0.946
		alphagen wave square 0 1 0.5867 0.946
		tcMod rotate -9
		tcMod stretch sin 0.7 0.7466 0.5867 0.946
	}
}

textures/runy9/zzfallssplash_24
{
	qer_editorimage textures/runy9/raiderssplash01.tga
	q3map_cloneshader textures/runy9/zzfallssplash_25
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 45 sawtooth 0 1 0.611261 0.946
	deformvertexes move -17.8812 -42.3823 0 square 0 1 0.611261 0.946
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raiderssplash01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.611261 0.946
		alphagen wave square 0 1 0.611261 0.946
		tcMod rotate 14
		tcMod stretch sin 0.7 0.7466 0.611261 0.946
	}
}

textures/runy9/zzfallssplash_25
{
	qer_editorimage textures/runy9/raiderssplash01.tga
	q3map_cloneshader textures/runy9/zzfallssplash_26
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 45 sawtooth 0 1 0.635785 0.946
	deformvertexes move 4.38484 -34.7242 0 square 0 1 0.635785 0.946
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raiderssplash01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.635785 0.946
		alphagen wave square 0 1 0.635785 0.946
		tcMod rotate 13
		tcMod stretch sin 0.7 0.7466 0.635785 0.946
	}
}

textures/runy9/zzfallssplash_26
{
	qer_editorimage textures/runy9/raiderssplash01.tga
	q3map_cloneshader textures/runy9/zzfallssplash_27
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 45 sawtooth 0 1 0.660273 0.946
	deformvertexes move 52.8286 -30.4981 0 square 0 1 0.660273 0.946
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raiderssplash01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.660273 0.946
		alphagen wave square 0 1 0.660273 0.946
		tcMod rotate 15
		tcMod stretch sin 0.7 0.7466 0.660273 0.946
	}
}

textures/runy9/zzfallssplash_27
{
	qer_editorimage textures/runy9/raiderssplash01.tga
	q3map_cloneshader textures/runy9/zzfallssplash_28
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 45 sawtooth 0 1 0.684726 0.946
	deformvertexes move -7.26894 -45.4221 0 square 0 1 0.684726 0.946
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raiderssplash01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.684726 0.946
		alphagen wave square 0 1 0.684726 0.946
		tcMod rotate -18
		tcMod stretch sin 0.7 0.7466 0.684726 0.946
	}
}

textures/runy9/zzfallssplash_28
{
	qer_editorimage textures/runy9/raiderssplash01.tga
	q3map_cloneshader textures/runy9/zzfallssplash_29
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 45 sawtooth 0 1 0.709147 0.946
	deformvertexes move -57.6461 -54.0179 0 square 0 1 0.709147 0.946
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raiderssplash01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.709147 0.946
		alphagen wave square 0 1 0.709147 0.946
		tcMod rotate 21
		tcMod stretch sin 0.7 0.7466 0.709147 0.946
	}
}

textures/runy9/zzfallssplash_29
{
	qer_editorimage textures/runy9/raiderssplash01.tga
	q3map_cloneshader textures/runy9/zzfallssplash_30
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 45 sawtooth 0 1 0.733536 0.946
	deformvertexes move 73.391 -26.4152 0 square 0 1 0.733536 0.946
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raiderssplash01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.733536 0.946
		alphagen wave square 0 1 0.733536 0.946
		tcMod rotate -3
		tcMod stretch sin 0.7 0.7466 0.733536 0.946
	}
}

textures/runy9/zzfallssplash_30
{
	qer_editorimage textures/runy9/raiderssplash01.tga
	q3map_cloneshader textures/runy9/zzfallssplash_31
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 45 sawtooth 0 1 0.757895 0.946
	deformvertexes move 35.035 -17.1332 0 square 0 1 0.757895 0.946
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raiderssplash01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.757895 0.946
		alphagen wave square 0 1 0.757895 0.946
		tcMod rotate 12
		tcMod stretch sin 0.7 0.7466 0.757895 0.946
	}
}

textures/runy9/zzfallssplash_31
{
	qer_editorimage textures/runy9/raiderssplash01.tga
	q3map_cloneshader textures/runy9/zzfallssplash_32
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 45 sawtooth 0 1 0.782224 0.946
	deformvertexes move -16.7016 -48.1877 0 square 0 1 0.782224 0.946
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raiderssplash01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.782224 0.946
		alphagen wave square 0 1 0.782224 0.946
		tcMod rotate 7
		tcMod stretch sin 0.7 0.7466 0.782224 0.946
	}
}

textures/runy9/zzfallssplash_32
{
	qer_editorimage textures/runy9/raiderssplash01.tga
	q3map_cloneshader textures/runy9/zzfallssplash_33
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 45 sawtooth 0 1 0.806524 0.946
	deformvertexes move 68.8166 -17.4721 0 square 0 1 0.806524 0.946
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raiderssplash01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.806524 0.946
		alphagen wave square 0 1 0.806524 0.946
		tcMod rotate -4
		tcMod stretch sin 0.7 0.7466 0.806524 0.946
	}
}

textures/runy9/zzfallssplash_33
{
	qer_editorimage textures/runy9/raiderssplash01.tga
	q3map_cloneshader textures/runy9/zzfallssplash_34
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 45 sawtooth 0 1 0.830797 0.946
	deformvertexes move 38.614 -28.5124 0 square 0 1 0.830797 0.946
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raiderssplash01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.830797 0.946
		alphagen wave square 0 1 0.830797 0.946
		tcMod rotate 21
		tcMod stretch sin 0.7 0.7466 0.830797 0.946
	}
}

textures/runy9/zzfallssplash_34
{
	qer_editorimage textures/runy9/raiderssplash01.tga
	q3map_cloneshader textures/runy9/zzfallssplash_35
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 45 sawtooth 0 1 0.855043 0.946
	deformvertexes move -47.1497 -32.0297 0 square 0 1 0.855043 0.946
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raiderssplash01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.855043 0.946
		alphagen wave square 0 1 0.855043 0.946
		tcMod rotate 13
		tcMod stretch sin 0.7 0.7466 0.855043 0.946
	}
}

textures/runy9/zzfallssplash_35
{
	qer_editorimage textures/runy9/raiderssplash01.tga
	q3map_cloneshader textures/runy9/zzfallssplash_36
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 45 sawtooth 0 1 0.879263 0.946
	deformvertexes move -52.6917 -49.0671 0 square 0 1 0.879263 0.946
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raiderssplash01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.879263 0.946
		alphagen wave square 0 1 0.879263 0.946
		tcMod rotate -15
		tcMod stretch sin 0.7 0.7466 0.879263 0.946
	}
}

textures/runy9/zzfallssplash_36
{
	qer_editorimage textures/runy9/raiderssplash01.tga
	q3map_cloneshader textures/runy9/zzfallssplash_37
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 45 sawtooth 0 1 0.903458 0.946
	deformvertexes move -45.357 -23.3183 0 square 0 1 0.903458 0.946
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raiderssplash01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.903458 0.946
		alphagen wave square 0 1 0.903458 0.946
		tcMod rotate -3
		tcMod stretch sin 0.7 0.7466 0.903458 0.946
	}
}

textures/runy9/zzfallssplash_37
{
	qer_editorimage textures/runy9/raiderssplash01.tga
	q3map_cloneshader textures/runy9/zzfallssplash_38
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 45 sawtooth 0 1 0.927629 0.946
	deformvertexes move -35.9787 -1.23691 0 square 0 1 0.927629 0.946
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raiderssplash01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.927629 0.946
		alphagen wave square 0 1 0.927629 0.946
		tcMod rotate 8
		tcMod stretch sin 0.7 0.7466 0.927629 0.946
	}
}

textures/runy9/zzfallssplash_38
{
	qer_editorimage textures/runy9/raiderssplash01.tga
	q3map_cloneshader textures/runy9/zzfallssplash_39
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 45 sawtooth 0 1 0.951775 0.946
	deformvertexes move 45.626 -11.2812 0 square 0 1 0.951775 0.946
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raiderssplash01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.951775 0.946
		alphagen wave square 0 1 0.951775 0.946
		tcMod rotate 16
		tcMod stretch sin 0.7 0.7466 0.951775 0.946
	}
}

textures/runy9/zzfallssplash_39
{
	qer_editorimage textures/runy9/raiderssplash01.tga
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 45 sawtooth 0 1 0.975899 0.946
	deformvertexes move 42.5056 -6.50198 0 square 0 1 0.975899 0.946
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raiderssplash01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.975899 0.946
		alphagen wave square 0 1 0.975899 0.946
		tcMod rotate 4
		tcMod stretch sin 0.7 0.7466 0.975899 0.946
	}
}

