// Generated by Frozen Sand Particle Studio
// Thu Dec 24 04:12:21 2020


textures/dim_fx/embers1_dim
{
	qer_editorimage textures/dimstar_fx/fire.tga
	q3map_cloneshader textures/dim_fx/zzps_test_1
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 1137 sawtooth 0 1 1 0.01
	deformvertexes move -19.5515 -26.9776 0 inversesawtooth 0 1 1 0.01
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/dimstar_fx/fire.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_COLOR
		rgbgen wave square -0.3667 0.6333 1.04 0.01
		alphagen wave sawtooth 1 -2 1 0.01
	}
}

textures/dim_fx/zzps_test_1
{
	qer_editorimage textures/dimstar_fx/fire.tga
	q3map_cloneshader textures/dim_fx/zzps_test_2
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 699 sawtooth 0 1 1.01 0.01
	deformvertexes move -15.0809 16.4747 0 inversesawtooth 0 1 1.01 0.01
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/dimstar_fx/fire.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_COLOR
		rgbgen wave square -0.3667 0.6333 1.05 0.01
		alphagen wave sawtooth 1 -2 1.01 0.01
	}
}

textures/dim_fx/zzps_test_2
{
	qer_editorimage textures/dimstar_fx/fire.tga
	q3map_cloneshader textures/dim_fx/zzps_test_3
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 1351 sawtooth 0 1 1.02 0.01
	deformvertexes move 13.3561 -13.097 0 inversesawtooth -0.0534586 1 1.02 0.01
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/dimstar_fx/fire.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_COLOR
		rgbgen wave square -0.3667 0.6333 1.06 0.01
		alphagen wave sawtooth 1 -2 1.02 0.01
	}
}

textures/dim_fx/zzps_test_3
{
	qer_editorimage textures/dimstar_fx/fire.tga
	q3map_cloneshader textures/dim_fx/zzps_test_4
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 742 sawtooth 0 1 1.03 0.01
	deformvertexes move 20.6279 12.6864 0 inversesawtooth 0 1 1.03 0.01
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/dimstar_fx/fire.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_COLOR
		rgbgen wave square -0.3667 0.6333 1.07 0.01
		alphagen wave sawtooth 1 -2 1.03 0.01
	}
}

textures/dim_fx/zzps_test_4
{
	qer_editorimage textures/dimstar_fx/fire.tga
	q3map_cloneshader textures/dim_fx/zzps_test_5
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 871 sawtooth 0 1 1.04 0.01
	deformvertexes move 12.5457 -11.2669 0 inversesawtooth 0 1 1.04 0.01
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/dimstar_fx/fire.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_COLOR
		rgbgen wave square -0.3667 0.6333 1.08 0.01
		alphagen wave sawtooth 1 -2 1.04 0.01
	}
}

textures/dim_fx/zzps_test_5
{
	qer_editorimage textures/dimstar_fx/fire.tga
	q3map_cloneshader textures/dim_fx/zzps_test_6
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 1261 sawtooth 0 1 1.05 0.01
	deformvertexes move -16.7603 1.83378 0 inversesawtooth -0.0593107 1 1.05 0.01
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/dimstar_fx/fire.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_COLOR
		rgbgen wave square -0.3667 0.6333 1.09 0.01
		alphagen wave sawtooth 1 -2 1.05 0.01
	}
}

textures/dim_fx/zzps_test_6
{
	qer_editorimage textures/dimstar_fx/fire.tga
	q3map_cloneshader textures/dim_fx/zzps_test_7
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 934 sawtooth 0 1 1.06 0.01
	deformvertexes move 25.563 5.52973 0 inversesawtooth -0.0382346 1 1.06 0.01
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/dimstar_fx/fire.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_COLOR
		rgbgen wave square -0.3667 0.6333 1.1 0.01
		alphagen wave sawtooth 1 -2 1.06 0.01
	}
}

textures/dim_fx/zzps_test_7
{
	qer_editorimage textures/dimstar_fx/fire.tga
	q3map_cloneshader textures/dim_fx/zzps_test_8
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 947 sawtooth 0 1 1.07 0.01
	deformvertexes move 23.0472 -8.07508 0 inversesawtooth 0 1 1.07 0.01
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/dimstar_fx/fire.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_COLOR
		rgbgen wave square -0.3667 0.6333 1.11 0.01
		alphagen wave sawtooth 1 -2 1.07 0.01
	}
}

textures/dim_fx/zzps_test_8
{
	qer_editorimage textures/dimstar_fx/fire.tga
	q3map_cloneshader textures/dim_fx/zzps_test_9
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 974 sawtooth 0 1 1.08 0.01
	deformvertexes move -13.5952 23.2981 0 inversesawtooth 0 1 1.08 0.01
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/dimstar_fx/fire.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_COLOR
		rgbgen wave square -0.3667 0.6333 1.12 0.01
		alphagen wave sawtooth 1 -2 1.08 0.01
	}
}

textures/dim_fx/zzps_test_9
{
	qer_editorimage textures/dimstar_fx/fire.tga
	q3map_cloneshader textures/dim_fx/zzps_test_10
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 1107 sawtooth 0 1 1.09 0.01
	deformvertexes move -2.09681 -16.57 0 inversesawtooth 0 1 1.09 0.01
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/dimstar_fx/fire.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_COLOR
		rgbgen wave square -0.3667 0.6333 1.13 0.01
		alphagen wave sawtooth 1 -2 1.09 0.01
	}
}

textures/dim_fx/zzps_test_10
{
	qer_editorimage textures/dimstar_fx/fire.tga
	q3map_cloneshader textures/dim_fx/zzps_test_11
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 1124 sawtooth 0 1 1.1 0.01
	deformvertexes move 16.406 -14.7337 0 inversesawtooth -0.0453499 1 1.1 0.01
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/dimstar_fx/fire.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_COLOR
		rgbgen wave square -0.3667 0.6333 1.14 0.01
		alphagen wave sawtooth 1 -2 1.1 0.01
	}
}

textures/dim_fx/zzps_test_11
{
	qer_editorimage textures/dimstar_fx/fire.tga
	q3map_cloneshader textures/dim_fx/zzps_test_12
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 838 sawtooth 0 1 1.11 0.01
	deformvertexes move 5.42909 4.70713 0 inversesawtooth -0.139168 1 1.11 0.01
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/dimstar_fx/fire.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_COLOR
		rgbgen wave square -0.3667 0.6333 1.15 0.01
		alphagen wave sawtooth 1 -2 1.11 0.01
	}
}

textures/dim_fx/zzps_test_12
{
	qer_editorimage textures/dimstar_fx/fire.tga
	q3map_cloneshader textures/dim_fx/zzps_test_13
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 714 sawtooth 0 1 1.12 0.01
	deformvertexes move -12.9081 -4.41592 0 inversesawtooth 0 1 1.12 0.01
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/dimstar_fx/fire.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_COLOR
		rgbgen wave square -0.3667 0.6333 1.16 0.01
		alphagen wave sawtooth 1 -2 1.12 0.01
	}
}

textures/dim_fx/zzps_test_13
{
	qer_editorimage textures/dimstar_fx/fire.tga
	q3map_cloneshader textures/dim_fx/zzps_test_14
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 925 sawtooth 0 1 1.13 0.01
	deformvertexes move -5.52692 5.74192 0 inversesawtooth 0 1 1.13 0.01
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/dimstar_fx/fire.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_COLOR
		rgbgen wave square -0.3667 0.6333 1.17 0.01
		alphagen wave sawtooth 1 -2 1.13 0.01
	}
}

textures/dim_fx/zzps_test_14
{
	qer_editorimage textures/dimstar_fx/fire.tga
	q3map_cloneshader textures/dim_fx/zzps_test_15
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 980 sawtooth 0 1 1.14 0.01
	deformvertexes move 7.09299 -0.257237 0 inversesawtooth -0.140892 1 1.14 0.01
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/dimstar_fx/fire.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_COLOR
		rgbgen wave square -0.3667 0.6333 1.18 0.01
		alphagen wave sawtooth 1 -2 1.14 0.01
	}
}

textures/dim_fx/zzps_test_15
{
	qer_editorimage textures/dimstar_fx/fire.tga
	q3map_cloneshader textures/dim_fx/zzps_test_16
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 1044 sawtooth 0 1 1.15 0.01
	deformvertexes move 27.4102 0 0 inversesawtooth -0.0364828 1 1.15 0.01
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/dimstar_fx/fire.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_COLOR
		rgbgen wave square -0.3667 0.6333 1.19 0.01
		alphagen wave sawtooth 1 -2 1.15 0.01
	}
}

textures/dim_fx/zzps_test_16
{
	qer_editorimage textures/dimstar_fx/fire.tga
	q3map_cloneshader textures/dim_fx/zzps_test_17
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 742 sawtooth 0 1 1.16 0.01
	deformvertexes move 2.25189 -3.56516 0 inversesawtooth 0 1 1.16 0.01
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/dimstar_fx/fire.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_COLOR
		rgbgen wave square -0.3667 0.6333 1.2 0.01
		alphagen wave sawtooth 1 -2 1.16 0.01
	}
}

textures/dim_fx/zzps_test_17
{
	qer_editorimage textures/dimstar_fx/fire.tga
	q3map_cloneshader textures/dim_fx/zzps_test_18
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 995 sawtooth 0 1 1.17 0.01
	deformvertexes move 8.52552 15.1743 0 inversesawtooth -0.0574539 1 1.17 0.01
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/dimstar_fx/fire.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_COLOR
		rgbgen wave square -0.3667 0.6333 1.21 0.01
		alphagen wave sawtooth 1 -2 1.17 0.01
	}
}

textures/dim_fx/zzps_test_18
{
	qer_editorimage textures/dimstar_fx/fire.tga
	q3map_cloneshader textures/dim_fx/zzps_test_19
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 1007 sawtooth 0 1 1.18 0.01
	deformvertexes move -4.44361 -7.42297 0 inversesawtooth -0.115589 1 1.18 0.01
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/dimstar_fx/fire.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_COLOR
		rgbgen wave square -0.3667 0.6333 1.22 0.01
		alphagen wave sawtooth 1 -2 1.18 0.01
	}
}

textures/dim_fx/zzps_test_19
{
	qer_editorimage textures/dimstar_fx/fire.tga
	q3map_cloneshader textures/dim_fx/zzps_test_20
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 1199 sawtooth 0 1 1.19 0.01
	deformvertexes move 16.5078 -1.63809 0 inversesawtooth 0 1 1.19 0.01
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/dimstar_fx/fire.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_COLOR
		rgbgen wave square -0.3667 0.6333 1.23 0.01
		alphagen wave sawtooth 1 -2 1.19 0.01
	}
}

textures/dim_fx/zzps_test_20
{
	qer_editorimage textures/dimstar_fx/fire.tga
	q3map_cloneshader textures/dim_fx/zzps_test_21
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 914 sawtooth 0 1 1.2 0.01
	deformvertexes move 1.15761 -20.7118 0 inversesawtooth -0.0482064 1 1.2 0.01
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/dimstar_fx/fire.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_COLOR
		rgbgen wave square -0.3667 0.6333 1.24 0.01
		alphagen wave sawtooth 1 -2 1.2 0.01
	}
}

textures/dim_fx/zzps_test_21
{
	qer_editorimage textures/dimstar_fx/fire.tga
	q3map_cloneshader textures/dim_fx/zzps_test_22
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 1277 sawtooth 0 1 1.21 0.01
	deformvertexes move 37.1549 -1.58064 0 inversesawtooth -0.0268901 1 1.21 0.01
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/dimstar_fx/fire.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_COLOR
		rgbgen wave square -0.3667 0.6333 1.25 0.01
		alphagen wave sawtooth 1 -2 1.21 0.01
	}
}

textures/dim_fx/zzps_test_22
{
	qer_editorimage textures/dimstar_fx/fire.tga
	q3map_cloneshader textures/dim_fx/zzps_test_23
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 882 sawtooth 0 1 1.22 0.01
	deformvertexes move -3.96675 -8.17647 0 inversesawtooth -0.110037 1 1.22 0.01
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/dimstar_fx/fire.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_COLOR
		rgbgen wave square -0.3667 0.6333 1.26 0.01
		alphagen wave sawtooth 1 -2 1.22 0.01
	}
}

textures/dim_fx/zzps_test_23
{
	qer_editorimage textures/dimstar_fx/fire.tga
	q3map_cloneshader textures/dim_fx/zzps_test_24
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 1266 sawtooth 0 1 1.23 0.01
	deformvertexes move 15.4117 -7.08662 0 inversesawtooth 0 1 1.23 0.01
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/dimstar_fx/fire.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_COLOR
		rgbgen wave square -0.3667 0.6333 1.27 0.01
		alphagen wave sawtooth 1 -2 1.23 0.01
	}
}

textures/dim_fx/zzps_test_24
{
	qer_editorimage textures/dimstar_fx/fire.tga
	q3map_cloneshader textures/dim_fx/zzps_test_25
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 1164 sawtooth 0 1 1.24 0.01
	deformvertexes move -16.8407 -25.8731 0 inversesawtooth -0.0323928 1 1.24 0.01
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/dimstar_fx/fire.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_COLOR
		rgbgen wave square -0.3667 0.6333 1.28 0.01
		alphagen wave sawtooth 1 -2 1.24 0.01
	}
}

textures/dim_fx/zzps_test_25
{
	qer_editorimage textures/dimstar_fx/fire.tga
	q3map_cloneshader textures/dim_fx/zzps_test_26
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 729 sawtooth 0 1 1.25 0.01
	deformvertexes move 22.2332 5.69196 0 inversesawtooth -0.0435726 1 1.25 0.01
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/dimstar_fx/fire.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_COLOR
		rgbgen wave square -0.3667 0.6333 1.29 0.01
		alphagen wave sawtooth 1 -2 1.25 0.01
	}
}

textures/dim_fx/zzps_test_26
{
	qer_editorimage textures/dimstar_fx/fire.tga
	q3map_cloneshader textures/dim_fx/zzps_test_27
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 1007 sawtooth 0 1 1.26 0.01
	deformvertexes move 14.489 -2.17547 0 inversesawtooth -0.068253 1 1.26 0.01
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/dimstar_fx/fire.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_COLOR
		rgbgen wave square -0.3667 0.6333 1.3 0.01
		alphagen wave sawtooth 1 -2 1.26 0.01
	}
}

textures/dim_fx/zzps_test_27
{
	qer_editorimage textures/dimstar_fx/fire.tga
	q3map_cloneshader textures/dim_fx/zzps_test_28
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 788 sawtooth 0 1 1.27 0.01
	deformvertexes move 1.81369 21.0823 0 inversesawtooth -0.0472586 1 1.27 0.01
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/dimstar_fx/fire.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_COLOR
		rgbgen wave square -0.3667 0.6333 1.31 0.01
		alphagen wave sawtooth 1 -2 1.27 0.01
	}
}

textures/dim_fx/zzps_test_28
{
	qer_editorimage textures/dimstar_fx/fire.tga
	q3map_cloneshader textures/dim_fx/zzps_test_29
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 1337 sawtooth 0 1 1.28 0.01
	deformvertexes move -4.27556 -24.0417 0 inversesawtooth 0 1 1.28 0.01
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/dimstar_fx/fire.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_COLOR
		rgbgen wave square -0.3667 0.6333 1.32 0.01
		alphagen wave sawtooth 1 -2 1.28 0.01
	}
}

textures/dim_fx/zzps_test_29
{
	qer_editorimage textures/dimstar_fx/fire.tga
	q3map_cloneshader textures/dim_fx/zzps_test_30
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 1199 sawtooth 0 1 1.29 0.01
	deformvertexes move 2.37285 -11.3433 0 inversesawtooth -0.0862897 1 1.29 0.01
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/dimstar_fx/fire.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_COLOR
		rgbgen wave square -0.3667 0.6333 1.33 0.01
		alphagen wave sawtooth 1 -2 1.29 0.01
	}
}

textures/dim_fx/zzps_test_30
{
	qer_editorimage textures/dimstar_fx/fire.tga
	q3map_cloneshader textures/dim_fx/zzps_test_31
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 1074 sawtooth 0 1 1.3 0.01
	deformvertexes move 8.8768 1.63096 0 inversesawtooth 0 1 1.3 0.01
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/dimstar_fx/fire.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_COLOR
		rgbgen wave square -0.3667 0.6333 1.34 0.01
		alphagen wave sawtooth 1 -2 1.3 0.01
	}
}

textures/dim_fx/zzps_test_31
{
	qer_editorimage textures/dimstar_fx/fire.tga
	q3map_cloneshader textures/dim_fx/zzps_test_32
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 1026 sawtooth 0 1 1.31 0.01
	deformvertexes move -2.23442 15.8846 0 inversesawtooth 0 1 1.31 0.01
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/dimstar_fx/fire.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_COLOR
		rgbgen wave square -0.3667 0.6333 1.35 0.01
		alphagen wave sawtooth 1 -2 1.31 0.01
	}
}

textures/dim_fx/zzps_test_32
{
	qer_editorimage textures/dimstar_fx/fire.tga
	q3map_cloneshader textures/dim_fx/zzps_test_33
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 1281 sawtooth 0 1 1.32 0.01
	deformvertexes move -2.08522 19.1574 0 inversesawtooth -0.0518928 1 1.32 0.01
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/dimstar_fx/fire.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_COLOR
		rgbgen wave square -0.3667 0.6333 1.36 0.01
		alphagen wave sawtooth 1 -2 1.32 0.01
	}
}

textures/dim_fx/zzps_test_33
{
	qer_editorimage textures/dimstar_fx/fire.tga
	q3map_cloneshader textures/dim_fx/zzps_test_34
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 956 sawtooth 0 1 1.33 0.01
	deformvertexes move -29.4812 8.2191 0 inversesawtooth 0 1 1.33 0.01
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/dimstar_fx/fire.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_COLOR
		rgbgen wave square -0.3667 0.6333 1.37 0.01
		alphagen wave sawtooth 1 -2 1.33 0.01
	}
}

textures/dim_fx/zzps_test_34
{
	qer_editorimage textures/dimstar_fx/fire.tga
	q3map_cloneshader textures/dim_fx/zzps_test_35
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 777 sawtooth 0 1 1.34 0.01
	deformvertexes move -18.8775 1.46879 0 inversesawtooth -0.0528135 1 1.34 0.01
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/dimstar_fx/fire.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_COLOR
		rgbgen wave square -0.3667 0.6333 1.38 0.01
		alphagen wave sawtooth 1 -2 1.34 0.01
	}
}

textures/dim_fx/zzps_test_35
{
	qer_editorimage textures/dimstar_fx/fire.tga
	q3map_cloneshader textures/dim_fx/zzps_test_36
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 830 sawtooth 0 1 1.35 0.01
	deformvertexes move 15.4103 7.22857 0 inversesawtooth -0.0587493 1 1.35 0.01
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/dimstar_fx/fire.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_COLOR
		rgbgen wave square -0.3667 0.6333 1.39 0.01
		alphagen wave sawtooth 1 -2 1.35 0.01
	}
}

textures/dim_fx/zzps_test_36
{
	qer_editorimage textures/dimstar_fx/fire.tga
	q3map_cloneshader textures/dim_fx/zzps_test_37
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 847 sawtooth 0 1 1.36 0.01
	deformvertexes move -0.567426 14.3589 0 inversesawtooth 0 1 1.36 0.01
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/dimstar_fx/fire.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_COLOR
		rgbgen wave square -0.3667 0.6333 1.4 0.01
		alphagen wave sawtooth 1 -2 1.36 0.01
	}
}

textures/dim_fx/zzps_test_37
{
	qer_editorimage textures/dimstar_fx/fire.tga
	q3map_cloneshader textures/dim_fx/zzps_test_38
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 1218 sawtooth 0 1 1.37 0.01
	deformvertexes move -12.6565 -32.6084 0 inversesawtooth -0.028589 1 1.37 0.01
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/dimstar_fx/fire.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_COLOR
		rgbgen wave square -0.3667 0.6333 1.41 0.01
		alphagen wave sawtooth 1 -2 1.37 0.01
	}
}

textures/dim_fx/zzps_test_38
{
	qer_editorimage textures/dimstar_fx/fire.tga
	q3map_cloneshader textures/dim_fx/zzps_test_39
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 1048 sawtooth 0 1 1.38 0.01
	deformvertexes move 19.7238 19.1518 0 inversesawtooth 0 1 1.38 0.01
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/dimstar_fx/fire.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_COLOR
		rgbgen wave square -0.3667 0.6333 1.42 0.01
		alphagen wave sawtooth 1 -2 1.38 0.01
	}
}

textures/dim_fx/zzps_test_39
{
	qer_editorimage textures/dimstar_fx/fire.tga
	q3map_cloneshader textures/dim_fx/zzps_test_40
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 731 sawtooth 0 1 1.39 0.01
	deformvertexes move 1.99429 8.76725 0 inversesawtooth 0 1 1.39 0.01
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/dimstar_fx/fire.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_COLOR
		rgbgen wave square -0.3667 0.6333 1.43 0.01
		alphagen wave sawtooth 1 -2 1.39 0.01
	}
}

textures/dim_fx/zzps_test_40
{
	qer_editorimage textures/dimstar_fx/fire.tga
	q3map_cloneshader textures/dim_fx/zzps_test_41
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 1145 sawtooth 0 1 1.4 0.01
	deformvertexes move 6.80332 -15.0118 0 inversesawtooth -0.0606743 1 1.4 0.01
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/dimstar_fx/fire.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_COLOR
		rgbgen wave square -0.3667 0.6333 1.44 0.01
		alphagen wave sawtooth 1 -2 1.4 0.01
	}
}

textures/dim_fx/zzps_test_41
{
	qer_editorimage textures/dimstar_fx/fire.tga
	q3map_cloneshader textures/dim_fx/zzps_test_42
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 754 sawtooth 0 1 1.41 0.01
	deformvertexes move -3.24896 1.19828 0 inversesawtooth -0.288776 1 1.41 0.01
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/dimstar_fx/fire.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_COLOR
		rgbgen wave square -0.3667 0.6333 1.45 0.01
		alphagen wave sawtooth 1 -2 1.41 0.01
	}
}

textures/dim_fx/zzps_test_42
{
	qer_editorimage textures/dimstar_fx/fire.tga
	q3map_cloneshader textures/dim_fx/zzps_test_43
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 921 sawtooth 0 1 1.42 0.01
	deformvertexes move 6.0857 -3.22561 0 inversesawtooth -0.145186 1 1.42 0.01
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/dimstar_fx/fire.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_COLOR
		rgbgen wave square -0.3667 0.6333 1.46 0.01
		alphagen wave sawtooth 1 -2 1.42 0.01
	}
}

textures/dim_fx/zzps_test_43
{
	qer_editorimage textures/dimstar_fx/fire.tga
	q3map_cloneshader textures/dim_fx/zzps_test_44
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 949 sawtooth 0 1 1.43 0.01
	deformvertexes move -24.0503 8.36014 0 inversesawtooth -0.0392743 1 1.43 0.01
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/dimstar_fx/fire.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_COLOR
		rgbgen wave square -0.3667 0.6333 1.47 0.01
		alphagen wave sawtooth 1 -2 1.43 0.01
	}
}

textures/dim_fx/zzps_test_44
{
	qer_editorimage textures/dimstar_fx/fire.tga
	q3map_cloneshader textures/dim_fx/zzps_test_45
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 683 sawtooth 0 1 1.44 0.01
	deformvertexes move -14.4501 -4.04951 0 inversesawtooth -0.0666363 1 1.44 0.01
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/dimstar_fx/fire.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_COLOR
		rgbgen wave square -0.3667 0.6333 1.48 0.01
		alphagen wave sawtooth 1 -2 1.44 0.01
	}
}

textures/dim_fx/zzps_test_45
{
	qer_editorimage textures/dimstar_fx/fire.tga
	q3map_cloneshader textures/dim_fx/zzps_test_46
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 782 sawtooth 0 1 1.45 0.01
	deformvertexes move -7.01562 9.78126 0 inversesawtooth 0 1 1.45 0.01
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/dimstar_fx/fire.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_COLOR
		rgbgen wave square -0.3667 0.6333 1.49 0.01
		alphagen wave sawtooth 1 -2 1.45 0.01
	}
}

textures/dim_fx/zzps_test_46
{
	qer_editorimage textures/dimstar_fx/fire.tga
	q3map_cloneshader textures/dim_fx/zzps_test_47
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 1279 sawtooth 0 1 1.46 0.01
	deformvertexes move 29.3156 22.9484 0 inversesawtooth -0.0268604 1 1.46 0.01
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/dimstar_fx/fire.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_COLOR
		rgbgen wave square -0.3667 0.6333 1.5 0.01
		alphagen wave sawtooth 1 -2 1.46 0.01
	}
}

textures/dim_fx/zzps_test_47
{
	qer_editorimage textures/dimstar_fx/fire.tga
	q3map_cloneshader textures/dim_fx/zzps_test_48
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 1233 sawtooth 0 1 1.47 0.01
	deformvertexes move 6.28458 12.8296 0 inversesawtooth 0 1 1.47 0.01
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/dimstar_fx/fire.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_COLOR
		rgbgen wave square -0.3667 0.6333 1.51 0.01
		alphagen wave sawtooth 1 -2 1.47 0.01
	}
}

textures/dim_fx/zzps_test_48
{
	qer_editorimage textures/dimstar_fx/fire.tga
	q3map_cloneshader textures/dim_fx/zzps_test_49
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 1170 sawtooth 0 1 1.48 0.01
	deformvertexes move 1.02427 -14.9591 0 inversesawtooth 0 1 1.48 0.01
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/dimstar_fx/fire.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_COLOR
		rgbgen wave square -0.3667 0.6333 1.52 0.01
		alphagen wave sawtooth 1 -2 1.48 0.01
	}
}

textures/dim_fx/zzps_test_49
{
	qer_editorimage textures/dimstar_fx/fire.tga
	q3map_cloneshader textures/dim_fx/zzps_test_50
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 747 sawtooth 0 1 1.49 0.01
	deformvertexes move 0.642056 13.3039 0 inversesawtooth -0.0750788 1 1.49 0.01
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/dimstar_fx/fire.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_COLOR
		rgbgen wave square -0.3667 0.6333 1.53 0.01
		alphagen wave sawtooth 1 -2 1.49 0.01
	}
}

textures/dim_fx/zzps_test_50
{
	qer_editorimage textures/dimstar_fx/fire.tga
	q3map_cloneshader textures/dim_fx/zzps_test_51
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 1069 sawtooth 0 1 1.5 0.01
	deformvertexes move -15.2468 -12.824 0 inversesawtooth -0.0501936 1 1.5 0.01
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/dimstar_fx/fire.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_COLOR
		rgbgen wave square -0.3667 0.6333 1.54 0.01
		alphagen wave sawtooth 1 -2 1.5 0.01
	}
}

textures/dim_fx/zzps_test_51
{
	qer_editorimage textures/dimstar_fx/fire.tga
	q3map_cloneshader textures/dim_fx/zzps_test_52
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 1079 sawtooth 0 1 1.51 0.01
	deformvertexes move 9.11342 0.514466 0 inversesawtooth -0.109554 1 1.51 0.01
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/dimstar_fx/fire.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_COLOR
		rgbgen wave square -0.3667 0.6333 1.55 0.01
		alphagen wave sawtooth 1 -2 1.51 0.01
	}
}

textures/dim_fx/zzps_test_52
{
	qer_editorimage textures/dimstar_fx/fire.tga
	q3map_cloneshader textures/dim_fx/zzps_test_53
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 1084 sawtooth 0 1 1.52 0.01
	deformvertexes move 28.3569 13.0853 0 inversesawtooth -0.03202 1 1.52 0.01
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/dimstar_fx/fire.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_COLOR
		rgbgen wave square -0.3667 0.6333 1.56 0.01
		alphagen wave sawtooth 1 -2 1.52 0.01
	}
}

textures/dim_fx/zzps_test_53
{
	qer_editorimage textures/dimstar_fx/fire.tga
	q3map_cloneshader textures/dim_fx/zzps_test_54
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 1109 sawtooth 0 1 1.53 0.01
	deformvertexes move 6.81626 8.30386 0 inversesawtooth 0 1 1.53 0.01
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/dimstar_fx/fire.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_COLOR
		rgbgen wave square -0.3667 0.6333 1.57 0.01
		alphagen wave sawtooth 1 -2 1.53 0.01
	}
}

textures/dim_fx/zzps_test_54
{
	qer_editorimage textures/dimstar_fx/fire.tga
	q3map_cloneshader textures/dim_fx/zzps_test_55
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 1206 sawtooth 0 1 1.54 0.01
	deformvertexes move -4.82266 -25.2765 0 inversesawtooth 0 1 1.54 0.01
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/dimstar_fx/fire.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_COLOR
		rgbgen wave square -0.3667 0.6333 1.58 0.01
		alphagen wave sawtooth 1 -2 1.54 0.01
	}
}

textures/dim_fx/zzps_test_55
{
	qer_editorimage textures/dimstar_fx/fire.tga
	q3map_cloneshader textures/dim_fx/zzps_test_56
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 870 sawtooth 0 1 1.55 0.01
	deformvertexes move 5.79127 -22.0955 0 inversesawtooth 0 1 1.55 0.01
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/dimstar_fx/fire.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_COLOR
		rgbgen wave square -0.3667 0.6333 1.59 0.01
		alphagen wave sawtooth 1 -2 1.55 0.01
	}
}

textures/dim_fx/zzps_test_56
{
	qer_editorimage textures/dimstar_fx/fire.tga
	q3map_cloneshader textures/dim_fx/zzps_test_57
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 736 sawtooth 0 1 1.56 0.01
	deformvertexes move -6.46863 6.39164 0 inversesawtooth 0 1 1.56 0.01
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/dimstar_fx/fire.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_COLOR
		rgbgen wave square -0.3667 0.6333 1.6 0.01
		alphagen wave sawtooth 1 -2 1.56 0.01
	}
}

textures/dim_fx/zzps_test_57
{
	qer_editorimage textures/dimstar_fx/fire.tga
	q3map_cloneshader textures/dim_fx/zzps_test_58
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 1322 sawtooth 0 1 1.57 0.01
	deformvertexes move 31.4043 15.7028 0 inversesawtooth -0.0284808 1 1.57 0.01
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/dimstar_fx/fire.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_COLOR
		rgbgen wave square -0.3667 0.6333 1.61 0.01
		alphagen wave sawtooth 1 -2 1.57 0.01
	}
}

textures/dim_fx/zzps_test_58
{
	qer_editorimage textures/dimstar_fx/fire.tga
	q3map_cloneshader textures/dim_fx/zzps_test_59
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 1248 sawtooth 0 1 1.58 0.01
	deformvertexes move -3.59131 -15.1746 0 inversesawtooth -0.0641283 1 1.58 0.01
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/dimstar_fx/fire.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_COLOR
		rgbgen wave square -0.3667 0.6333 1.62 0.01
		alphagen wave sawtooth 1 -2 1.58 0.01
	}
}

textures/dim_fx/zzps_test_59
{
	qer_editorimage textures/dimstar_fx/fire.tga
	q3map_cloneshader textures/dim_fx/zzps_test_60
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 758 sawtooth 0 1 1.59 0.01
	deformvertexes move -12.0209 -9.85614 0 inversesawtooth 0 1 1.59 0.01
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/dimstar_fx/fire.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_COLOR
		rgbgen wave square -0.3667 0.6333 1.63 0.01
		alphagen wave sawtooth 1 -2 1.59 0.01
	}
}

textures/dim_fx/zzps_test_60
{
	qer_editorimage textures/dimstar_fx/fire.tga
	q3map_cloneshader textures/dim_fx/zzps_test_61
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 1222 sawtooth 0 1 1.6 0.01
	deformvertexes move 23.982 -16.4128 0 inversesawtooth -0.0344109 1 1.6 0.01
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/dimstar_fx/fire.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_COLOR
		rgbgen wave square -0.3667 0.6333 1.64 0.01
		alphagen wave sawtooth 1 -2 1.6 0.01
	}
}

textures/dim_fx/zzps_test_61
{
	qer_editorimage textures/dimstar_fx/fire.tga
	q3map_cloneshader textures/dim_fx/zzps_test_62
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 1070 sawtooth 0 1 1.61 0.01
	deformvertexes move -8.37456 9.86901 0 inversesawtooth -0.0772597 1 1.61 0.01
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/dimstar_fx/fire.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_COLOR
		rgbgen wave square -0.3667 0.6333 1.65 0.01
		alphagen wave sawtooth 1 -2 1.61 0.01
	}
}

textures/dim_fx/zzps_test_62
{
	qer_editorimage textures/dimstar_fx/fire.tga
	q3map_cloneshader textures/dim_fx/zzps_test_63
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 1347 sawtooth 0 1 1.62 0.01
	deformvertexes move 5.13926 -30.1897 0 inversesawtooth 0 1 1.62 0.01
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/dimstar_fx/fire.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_COLOR
		rgbgen wave square -0.3667 0.6333 1.66 0.01
		alphagen wave sawtooth 1 -2 1.62 0.01
	}
}

textures/dim_fx/zzps_test_63
{
	qer_editorimage textures/dimstar_fx/fire.tga
	q3map_cloneshader textures/dim_fx/zzps_test_64
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 1121 sawtooth 0 1 1.63 0.01
	deformvertexes move 20.4509 24.5982 0 inversesawtooth -0.0312605 1 1.63 0.01
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/dimstar_fx/fire.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_COLOR
		rgbgen wave square -0.3667 0.6333 1.67 0.01
		alphagen wave sawtooth 1 -2 1.63 0.01
	}
}

textures/dim_fx/zzps_test_64
{
	qer_editorimage textures/dimstar_fx/fire.tga
	q3map_cloneshader textures/dim_fx/zzps_test_65
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 885 sawtooth 0 1 1.64 0.01
	deformvertexes move -15.6295 -4.06477 0 inversesawtooth 0 1 1.64 0.01
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/dimstar_fx/fire.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_COLOR
		rgbgen wave square -0.3667 0.6333 1.68 0.01
		alphagen wave sawtooth 1 -2 1.64 0.01
	}
}

textures/dim_fx/zzps_test_65
{
	qer_editorimage textures/dimstar_fx/fire.tga
	q3map_cloneshader textures/dim_fx/zzps_test_66
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 1101 sawtooth 0 1 1.65 0.01
	deformvertexes move -25.0634 -20.814 0 inversesawtooth -0.0306945 1 1.65 0.01
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/dimstar_fx/fire.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_COLOR
		rgbgen wave square -0.3667 0.6333 1.69 0.01
		alphagen wave sawtooth 1 -2 1.65 0.01
	}
}

textures/dim_fx/zzps_test_66
{
	qer_editorimage textures/dimstar_fx/fire.tga
	q3map_cloneshader textures/dim_fx/zzps_test_67
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 1036 sawtooth 0 1 1.66 0.01
	deformvertexes move -5.40562 -12.0929 0 inversesawtooth -0.075494 1 1.66 0.01
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/dimstar_fx/fire.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_COLOR
		rgbgen wave square -0.3667 0.6333 1.7 0.01
		alphagen wave sawtooth 1 -2 1.66 0.01
	}
}

textures/dim_fx/zzps_test_67
{
	qer_editorimage textures/dimstar_fx/fire.tga
	q3map_cloneshader textures/dim_fx/zzps_test_68
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 1358 sawtooth 0 1 1.67 0.01
	deformvertexes move -17.4407 34.7147 0 inversesawtooth -0.0257403 1 1.67 0.01
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/dimstar_fx/fire.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_COLOR
		rgbgen wave square -0.3667 0.6333 1.71 0.01
		alphagen wave sawtooth 1 -2 1.67 0.01
	}
}

textures/dim_fx/zzps_test_68
{
	qer_editorimage textures/dimstar_fx/fire.tga
	q3map_cloneshader textures/dim_fx/zzps_test_69
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 695 sawtooth 0 1 1.68 0.01
	deformvertexes move -0.225836 -3.24508 0 inversesawtooth -0.307415 1 1.68 0.01
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/dimstar_fx/fire.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_COLOR
		rgbgen wave square -0.3667 0.6333 1.72 0.01
		alphagen wave sawtooth 1 -2 1.68 0.01
	}
}

textures/dim_fx/zzps_test_69
{
	qer_editorimage textures/dimstar_fx/fire.tga
	q3map_cloneshader textures/dim_fx/zzps_test_70
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 1116 sawtooth 0 1 1.69 0.01
	deformvertexes move 20.2035 8.41696 0 inversesawtooth -0.0456898 1 1.69 0.01
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/dimstar_fx/fire.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_COLOR
		rgbgen wave square -0.3667 0.6333 1.73 0.01
		alphagen wave sawtooth 1 -2 1.69 0.01
	}
}

textures/dim_fx/zzps_test_70
{
	qer_editorimage textures/dimstar_fx/fire.tga
	q3map_cloneshader textures/dim_fx/zzps_test_71
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 1118 sawtooth 0 1 1.7 0.01
	deformvertexes move -9.35662 -20.9317 0 inversesawtooth -0.0436153 1 1.7 0.01
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/dimstar_fx/fire.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_COLOR
		rgbgen wave square -0.3667 0.6333 1.74 0.01
		alphagen wave sawtooth 1 -2 1.7 0.01
	}
}

textures/dim_fx/zzps_test_71
{
	qer_editorimage textures/dimstar_fx/fire.tga
	q3map_cloneshader textures/dim_fx/zzps_test_72
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 1082 sawtooth 0 1 1.71 0.01
	deformvertexes move -34.0653 -2.91144 0 inversesawtooth 0 1 1.71 0.01
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/dimstar_fx/fire.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_COLOR
		rgbgen wave square -0.3667 0.6333 1.75 0.01
		alphagen wave sawtooth 1 -2 1.71 0.01
	}
}

textures/dim_fx/zzps_test_72
{
	qer_editorimage textures/dimstar_fx/fire.tga
	q3map_cloneshader textures/dim_fx/zzps_test_73
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 1006 sawtooth 0 1 1.72 0.01
	deformvertexes move 30.9658 -6.45217 0 inversesawtooth -0.0316147 1 1.72 0.01
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/dimstar_fx/fire.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_COLOR
		rgbgen wave square -0.3667 0.6333 1.76 0.01
		alphagen wave sawtooth 1 -2 1.72 0.01
	}
}

textures/dim_fx/zzps_test_73
{
	qer_editorimage textures/dimstar_fx/fire.tga
	q3map_cloneshader textures/dim_fx/zzps_test_74
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 1129 sawtooth 0 1 1.73 0.01
	deformvertexes move -12.1313 -0.731142 0 inversesawtooth 0 1 1.73 0.01
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/dimstar_fx/fire.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_COLOR
		rgbgen wave square -0.3667 0.6333 1.77 0.01
		alphagen wave sawtooth 1 -2 1.73 0.01
	}
}

textures/dim_fx/zzps_test_74
{
	qer_editorimage textures/dimstar_fx/fire.tga
	q3map_cloneshader textures/dim_fx/zzps_test_75
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 1087 sawtooth 0 1 1.74 0.01
	deformvertexes move 6.87428 -6.25183 0 inversesawtooth -0.10762 1 1.74 0.01
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/dimstar_fx/fire.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_COLOR
		rgbgen wave square -0.3667 0.6333 1.78 0.01
		alphagen wave sawtooth 1 -2 1.74 0.01
	}
}

textures/dim_fx/zzps_test_75
{
	qer_editorimage textures/dimstar_fx/fire.tga
	q3map_cloneshader textures/dim_fx/zzps_test_76
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 1029 sawtooth 0 1 1.75 0.01
	deformvertexes move -7.49122 3.08751 0 inversesawtooth 0 1 1.75 0.01
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/dimstar_fx/fire.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_COLOR
		rgbgen wave square -0.3667 0.6333 1.79 0.01
		alphagen wave sawtooth 1 -2 1.75 0.01
	}
}

textures/dim_fx/zzps_test_76
{
	qer_editorimage textures/dimstar_fx/fire.tga
	q3map_cloneshader textures/dim_fx/zzps_test_77
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 731 sawtooth 0 1 1.76 0.01
	deformvertexes move -9.89064 24.0358 0 inversesawtooth -0.0384745 1 1.76 0.01
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/dimstar_fx/fire.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_COLOR
		rgbgen wave square -0.3667 0.6333 1.8 0.01
		alphagen wave sawtooth 1 -2 1.76 0.01
	}
}

textures/dim_fx/zzps_test_77
{
	qer_editorimage textures/dimstar_fx/fire.tga
	q3map_cloneshader textures/dim_fx/zzps_test_78
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 811 sawtooth 0 1 1.77 0.01
	deformvertexes move 26.9781 -5.97498 0 inversesawtooth 0 1 1.77 0.01
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/dimstar_fx/fire.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_COLOR
		rgbgen wave square -0.3667 0.6333 1.81 0.01
		alphagen wave sawtooth 1 -2 1.77 0.01
	}
}

textures/dim_fx/zzps_test_78
{
	qer_editorimage textures/dimstar_fx/fire.tga
	q3map_cloneshader textures/dim_fx/zzps_test_79
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 1046 sawtooth 0 1 1.78 0.01
	deformvertexes move -24.9847 8.68496 0 inversesawtooth 0 1 1.78 0.01
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/dimstar_fx/fire.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_COLOR
		rgbgen wave square -0.3667 0.6333 1.82 0.01
		alphagen wave sawtooth 1 -2 1.78 0.01
	}
}

textures/dim_fx/zzps_test_79
{
	qer_editorimage textures/dimstar_fx/fire.tga
	q3map_cloneshader textures/dim_fx/zzps_test_80
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 813 sawtooth 0 1 1.79 0.01
	deformvertexes move 17.1799 -4.14514 0 inversesawtooth 0 1 1.79 0.01
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/dimstar_fx/fire.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_COLOR
		rgbgen wave square -0.3667 0.6333 1.83 0.01
		alphagen wave sawtooth 1 -2 1.79 0.01
	}
}

textures/dim_fx/zzps_test_80
{
	qer_editorimage textures/dimstar_fx/fire.tga
	q3map_cloneshader textures/dim_fx/zzps_test_81
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 820 sawtooth 0 1 1.8 0.01
	deformvertexes move -6.26908 2.67619 0 inversesawtooth -0.146705 1 1.8 0.01
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/dimstar_fx/fire.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_COLOR
		rgbgen wave square -0.3667 0.6333 1.84 0.01
		alphagen wave sawtooth 1 -2 1.8 0.01
	}
}

textures/dim_fx/zzps_test_81
{
	qer_editorimage textures/dimstar_fx/fire.tga
	q3map_cloneshader textures/dim_fx/zzps_test_82
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 786 sawtooth 0 1 1.81 0.01
	deformvertexes move -14.5388 22.8926 0 inversesawtooth 0 1 1.81 0.01
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/dimstar_fx/fire.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_COLOR
		rgbgen wave square -0.3667 0.6333 1.85 0.01
		alphagen wave sawtooth 1 -2 1.81 0.01
	}
}

textures/dim_fx/zzps_test_82
{
	qer_editorimage textures/dimstar_fx/fire.tga
	q3map_cloneshader textures/dim_fx/zzps_test_83
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 1085 sawtooth 0 1 1.82 0.01
	deformvertexes move 27.6203 -5.93591 0 inversesawtooth -0.035397 1 1.82 0.01
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/dimstar_fx/fire.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_COLOR
		rgbgen wave square -0.3667 0.6333 1.86 0.01
		alphagen wave sawtooth 1 -2 1.82 0.01
	}
}

textures/dim_fx/zzps_test_83
{
	qer_editorimage textures/dimstar_fx/fire.tga
	q3map_cloneshader textures/dim_fx/zzps_test_84
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 1093 sawtooth 0 1 1.83 0.01
	deformvertexes move -5.55101 -13.3034 0 inversesawtooth 0 1 1.83 0.01
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/dimstar_fx/fire.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_COLOR
		rgbgen wave square -0.3667 0.6333 1.87 0.01
		alphagen wave sawtooth 1 -2 1.83 0.01
	}
}

textures/dim_fx/zzps_test_84
{
	qer_editorimage textures/dimstar_fx/fire.tga
	q3map_cloneshader textures/dim_fx/zzps_test_85
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 874 sawtooth 0 1 1.84 0.01
	deformvertexes move 6.76927 -1.45479 0 inversesawtooth -0.144429 1 1.84 0.01
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/dimstar_fx/fire.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_COLOR
		rgbgen wave square -0.3667 0.6333 1.88 0.01
		alphagen wave sawtooth 1 -2 1.84 0.01
	}
}

textures/dim_fx/zzps_test_85
{
	qer_editorimage textures/dimstar_fx/fire.tga
	q3map_cloneshader textures/dim_fx/zzps_test_86
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 1329 sawtooth 0 1 1.85 0.01
	deformvertexes move 16.0714 2.43517 0 inversesawtooth 0 1 1.85 0.01
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/dimstar_fx/fire.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_COLOR
		rgbgen wave square -0.3667 0.6333 1.89 0.01
		alphagen wave sawtooth 1 -2 1.85 0.01
	}
}

textures/dim_fx/zzps_test_86
{
	qer_editorimage textures/dimstar_fx/fire.tga
	q3map_cloneshader textures/dim_fx/zzps_test_87
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 1241 sawtooth 0 1 1.86 0.01
	deformvertexes move 20.1063 24.1837 0 inversesawtooth 0 1 1.86 0.01
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/dimstar_fx/fire.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_COLOR
		rgbgen wave square -0.3667 0.6333 1.9 0.01
		alphagen wave sawtooth 1 -2 1.86 0.01
	}
}

textures/dim_fx/zzps_test_87
{
	qer_editorimage textures/dimstar_fx/fire.tga
	q3map_cloneshader textures/dim_fx/zzps_test_88
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 783 sawtooth 0 1 1.87 0.01
	deformvertexes move -6.2309 -13.7079 0 inversesawtooth 0 1 1.87 0.01
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/dimstar_fx/fire.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_COLOR
		rgbgen wave square -0.3667 0.6333 1.91 0.01
		alphagen wave sawtooth 1 -2 1.87 0.01
	}
}

textures/dim_fx/zzps_test_88
{
	qer_editorimage textures/dimstar_fx/fire.tga
	q3map_cloneshader textures/dim_fx/zzps_test_89
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 1059 sawtooth 0 1 1.88 0.01
	deformvertexes move -13.542 -12.9216 0 inversesawtooth 0 1 1.88 0.01
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/dimstar_fx/fire.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_COLOR
		rgbgen wave square -0.3667 0.6333 1.92 0.01
		alphagen wave sawtooth 1 -2 1.88 0.01
	}
}

textures/dim_fx/zzps_test_89
{
	qer_editorimage textures/dimstar_fx/fire.tga
	q3map_cloneshader textures/dim_fx/zzps_test_90
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 1030 sawtooth 0 1 1.89 0.01
	deformvertexes move -14.9963 8.26506 0 inversesawtooth -0.0584008 1 1.89 0.01
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/dimstar_fx/fire.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_COLOR
		rgbgen wave square -0.3667 0.6333 1.93 0.01
		alphagen wave sawtooth 1 -2 1.89 0.01
	}
}

textures/dim_fx/zzps_test_90
{
	qer_editorimage textures/dimstar_fx/fire.tga
	q3map_cloneshader textures/dim_fx/zzps_test_91
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 915 sawtooth 0 1 1.9 0.01
	deformvertexes move -18.5494 9.33222 0 inversesawtooth -0.0481588 1 1.9 0.01
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/dimstar_fx/fire.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_COLOR
		rgbgen wave square -0.3667 0.6333 1.94 0.01
		alphagen wave sawtooth 1 -2 1.9 0.01
	}
}

textures/dim_fx/zzps_test_91
{
	qer_editorimage textures/dimstar_fx/fire.tga
	q3map_cloneshader textures/dim_fx/zzps_test_92
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 1136 sawtooth 0 1 1.91 0.01
	deformvertexes move 33.8073 5.77453 0 inversesawtooth 0 1 1.91 0.01
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/dimstar_fx/fire.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_COLOR
		rgbgen wave square -0.3667 0.6333 1.95 0.01
		alphagen wave sawtooth 1 -2 1.91 0.01
	}
}

textures/dim_fx/zzps_test_92
{
	qer_editorimage textures/dimstar_fx/fire.tga
	q3map_cloneshader textures/dim_fx/zzps_test_93
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 997 sawtooth 0 1 1.92 0.01
	deformvertexes move 14.3042 -13.1737 0 inversesawtooth 0 1 1.92 0.01
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/dimstar_fx/fire.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_COLOR
		rgbgen wave square -0.3667 0.6333 1.96 0.01
		alphagen wave sawtooth 1 -2 1.92 0.01
	}
}

textures/dim_fx/zzps_test_93
{
	qer_editorimage textures/dimstar_fx/fire.tga
	q3map_cloneshader textures/dim_fx/zzps_test_94
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 815 sawtooth 0 1 1.93 0.01
	deformvertexes move 18.3624 -9.58576 0 inversesawtooth -0.0482768 1 1.93 0.01
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/dimstar_fx/fire.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_COLOR
		rgbgen wave square -0.3667 0.6333 1.97 0.01
		alphagen wave sawtooth 1 -2 1.93 0.01
	}
}

textures/dim_fx/zzps_test_94
{
	qer_editorimage textures/dimstar_fx/fire.tga
	q3map_cloneshader textures/dim_fx/zzps_test_95
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 843 sawtooth 0 1 1.94 0.01
	deformvertexes move -12.0864 -19.9061 0 inversesawtooth -0.0429404 1 1.94 0.01
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/dimstar_fx/fire.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_COLOR
		rgbgen wave square -0.3667 0.6333 1.98 0.01
		alphagen wave sawtooth 1 -2 1.94 0.01
	}
}

textures/dim_fx/zzps_test_95
{
	qer_editorimage textures/dimstar_fx/fire.tga
	q3map_cloneshader textures/dim_fx/zzps_test_96
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 1064 sawtooth 0 1 1.95 0.01
	deformvertexes move 9.51067 -13.8734 0 inversesawtooth 0 1 1.95 0.01
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/dimstar_fx/fire.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_COLOR
		rgbgen wave square -0.3667 0.6333 1.99 0.01
		alphagen wave sawtooth 1 -2 1.95 0.01
	}
}

textures/dim_fx/zzps_test_96
{
	qer_editorimage textures/dimstar_fx/fire.tga
	q3map_cloneshader textures/dim_fx/zzps_test_97
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 771 sawtooth 0 1 1.96 0.01
	deformvertexes move -22.568 10.31 0 inversesawtooth -0.0403039 1 1.96 0.01
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/dimstar_fx/fire.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_COLOR
		rgbgen wave square -0.3667 0.6333 2 0.01
		alphagen wave sawtooth 1 -2 1.96 0.01
	}
}

textures/dim_fx/zzps_test_97
{
	qer_editorimage textures/dimstar_fx/fire.tga
	q3map_cloneshader textures/dim_fx/zzps_test_98
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 1250 sawtooth 0 1 1.97 0.01
	deformvertexes move -27.4853 -2.87039 0 inversesawtooth -0.0361863 1 1.97 0.01
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/dimstar_fx/fire.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_COLOR
		rgbgen wave square -0.3667 0.6333 2.01 0.01
		alphagen wave sawtooth 1 -2 1.97 0.01
	}
}

textures/dim_fx/zzps_test_98
{
	qer_editorimage textures/dimstar_fx/fire.tga
	q3map_cloneshader textures/dim_fx/zzps_test_99
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 986 sawtooth 0 1 1.98 0.01
	deformvertexes move -5.74695 8.45194 0 inversesawtooth -0.0978406 1 1.98 0.01
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/dimstar_fx/fire.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_COLOR
		rgbgen wave square -0.3667 0.6333 2.02 0.01
		alphagen wave sawtooth 1 -2 1.98 0.01
	}
}

textures/dim_fx/zzps_test_99
{
	qer_editorimage textures/dimstar_fx/fire.tga
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 1094 sawtooth 0 1 1.99 0.01
	deformvertexes move -15.6925 -14.6023 0 inversesawtooth 0 1 1.99 0.01
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/dimstar_fx/fire.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_COLOR
		rgbgen wave square -0.3667 0.6333 2.03 0.01
		alphagen wave sawtooth 1 -2 1.99 0.01
	}
}

