
textures/hos_misc2/bulb
{
	qer_editorimage textures/hos_models/bulb.tga
	surfaceparm nolightmap
	surfaceparm nomarks
	surfaceparm nonsolid
	surfaceparm trans
	q3map_nonplanar
	q3map_noTJunc

	{
		map $lightmap
		rgbgen identity
	}
	{
		map textures/hos_models/bulb.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen identity
	}
}

textures/hos_misc2/door11
{ 
qer_editorimage textures/hos_models/door11.tga
surfaceparm mat_wood
implicitMap textures/hos_models/door11.tga
}

textures/hos_misc2/smallbox_ends
{ 
qer_editorimage textures/hos_models/smallbox_ends.tga
surfaceparm mat_wood
implicitMap textures/hos_models/smallbox_ends.tga
}

textures/hos_misc2/smallbox_sides
{ 
qer_editorimage textures/hos_models/smallbox_sides.tga
surfaceparm mat_wood
implicitMap textures/hos_models/smallbox_sides.tga
}

textures/hos_misc2/smallbox_top_bottom
{ 
qer_editorimage textures/hos_models/smallbox_top_bottom.tga
surfaceparm mat_wood
implicitMap textures/hos_models/smallbox_top_bottom.tga
}

textures/hos_misc2/brownboard
{ 
qer_editorimage textures/hos_models/brownboard.tga
surfaceparm mat_wood
implicitMap textures/hos_models/brownboard.tga
}

textures/hos_misc2/brownboardb
{ 
qer_editorimage textures/hos_models/brownboardb.tga
surfaceparm mat_wood
implicitMap textures/hos_models/brownboardb.tga
}

textures/hos_misc2/brownboardc
{ 
qer_editorimage textures/hos_models/brownboardc.tga
surfaceparm mat_wood
implicitMap textures/hos_models/brownboardc.tga
}

textures/hos_misc2/wood1
{ 
qer_editorimage textures/hos_models/wood1.tga
surfaceparm mat_wood
implicitMap textures/hos_models/wood1.tga
}

textures/hos_misc2/metal10
{ 
qer_editorimage textures/hos_models/metal10.tga
surfaceparm mat_metal
implicitMap textures/hos_models/metal10.tga
}

textures/hos_misc2/pipemetal4
{ 
qer_editorimage textures/hos_models/pipemetal4.tga
surfaceparm mat_metal
implicitMap textures/hos_models/pipemetal4.tga
}

///barrels

textures/hos_misc2/barrel1
{ 
qer_editorimage textures/hos_models/barrel1.tga
surfaceparm mat_tin
implicitMap textures/hos_models/barrel1.tga
}

textures/hos_misc2/barrel2
{ 
qer_editorimage textures/hos_models/barrel2.tga
surfaceparm mat_tin
implicitMap textures/hos_models/barrel2.tga
}

textures/hos_misc2/barrel3
{ 
qer_editorimage textures/hos_models/barrel3.tga
surfaceparm mat_tin
implicitMap textures/hos_models/barrel3.tga
}

textures/hos_misc2/barrel4
{ 
qer_editorimage textures/hos_models/barrel4.tga
surfaceparm mat_tin
implicitMap textures/hos_models/barrel4.tga
}

textures/hos_misc2/barrel5
{ 
qer_editorimage textures/hos_models/barrel5.tga
surfaceparm mat_tin
implicitMap textures/hos_models/barrel5.tga
}

textures/hos_misc2/barrel6
{ 
qer_editorimage textures/hos_models/barrel6.tga
surfaceparm mat_tin
implicitMap textures/hos_models/barrel6.tga
}

textures/hos_misc2/barrel7
{ 
qer_editorimage textures/hos_models/barrel7.tga
surfaceparm mat_tin
implicitMap textures/hos_models/barrel7.tga
}

textures/hos_misc2/barrel8
{ 
qer_editorimage textures/hos_models/barrel8.tga
surfaceparm mat_tin
implicitMap textures/hos_models/barrel8.tga
}

textures/hos_misc2/barrel9
{ 
qer_editorimage textures/hos_models/barrel9.tga
surfaceparm mat_tin
implicitMap textures/hos_models/barrel9.tga
}


textures/hos_misc2/barrel10
{ 
qer_editorimage textures/hos_models/barrel10.tga
surfaceparm mat_tin
implicitMap textures/hos_models/barrel10.tga
}

textures/hos_misc2/barrel11
{ 
qer_editorimage textures/hos_models/barrel11.tga
surfaceparm mat_tin
implicitMap textures/hos_models/barrel11.tga
}

textures/hos_misc2/LIDC2
{ 
qer_editorimage textures/hos_models/LIDC2.tga
surfaceparm mat_tin
implicitMap textures/hos_models/LIDC2.tga
}

textures/hos_misc2/LIDD2
{ 
qer_editorimage textures/hos_models/LIDD2.tga
surfaceparm mat_metal
implicitMap textures/hos_models/LIDD2.tga
}

textures/hos_misc2/lidc2
{ 
qer_editorimage textures/hos_models/lidc2.tga
surfaceparm mat_tin
implicitMap textures/hos_models/lidc2.tga
}

textures/hos_misc2/lidd2
{ 
qer_editorimage textures/hos_models/lidd2.tga
surfaceparm mat_metal
implicitMap textures/hos_models/lidd2.tga
}

textures/hos_misc2/lid2
{ 
qer_editorimage textures/hos_models/lid2.tga
surfaceparm mat_metal
implicitMap textures/hos_models/lid2.tga
}


textures/hos_misc2/LIDC3
{ 
qer_editorimage textures/hos_models/LIDC3.tga
surfaceparm mat_metal
implicitMap textures/hos_models/LIDC3.tga
}

//////////////

textures/hos_misc2/filecabinet
{ 
qer_editorimage textures/hos_models/filecabinet.tga
surfaceparm mat_wood
implicitMap textures/hos_models/filecabinet.tga
}

textures/hos_misc2/porcelain
{ 
qer_editorimage textures/hos_models/porcelain.tga
surfaceparm mat_glass
implicitMap textures/hos_models/porcelain.tga
}

textures/hos_misc2/oscilloscope
{ 
qer_editorimage textures/hos_models/oscilloscope.tga
surfaceparm mat_metal
implicitMap textures/hos_models/oscilloscope.tga
}


textures/hos_misc2/coke
{ 
qer_editorimage textures/hos_models/coke.tga
surfaceparm mat_glass
implicitMap textures/hos_models/coke.tga
}


textures/hos_misc2/metal18
{ 
qer_editorimage textures/hos_models/metal18.tga
surfaceparm mat_metal
implicitMap textures/hos_models/metal18.tga
}

textures/hos_misc2/boxwood1
{ 
qer_editorimage textures/hos_models/boxwood1.tga
surfaceparm mat_wood
implicitMap textures/hos_models/boxwood1.tga
}

textures/hos_misc2/boxwood2
{ 
qer_editorimage textures/hos_models/boxwood2.tga
surfaceparm mat_wood
implicitMap textures/hos_models/boxwood2.tga
}


textures/hos_misc2/blackplastic
{ 
qer_editorimage textures/hos_models/blackplastic.tga
surfaceparm mat_carpet
implicitMap textures/hos_models/blackplastic.tga
}

textures/hos_misc2/blackplastic_offset_nolm
{ 
qer_editorimage textures/hos_models/blackplastic.tga
q3map_forceMeta 
q3map_nonplanar
q3map_noTjunc
surfaceparm trans
surfaceparm nomarks
surfaceparm nolightmap
surfaceparm nonsolid
cull none
polygonOffset
implicitMap textures/hos_models/blackplastic.tga
}

textures/hos_misc2/radiator1
{ 
qer_editorimage textures/hos_models/radiator1.tga
surfaceparm mat_metal
implicitMap textures/hos_models/radiator1.tga
}

textures/hos_misc2/radiator1_side
{ 
qer_editorimage textures/hos_models/radiator1_side.tga
surfaceparm mat_metal
implicitMap textures/hos_models/radiator1_side.tga
}


textures/hos_misc2/metal17
{ 
qer_editorimage textures/hos_models/metal17.tga
surfaceparm mat_metal
implicitMap textures/hos_models/metal17.tga
}


textures/hos_misc2/trash
{ 
qer_editorimage textures/hos_models/trash.tga
surfaceparm nomarks
implicitMap textures/hos_models/trash.tga
}

textures/hos_misc2/switch2
{ 
qer_editorimage textures/hos_models/switch2.tga
surfaceparm nomarks
implicitMap textures/hos_models/switch2.tga
}


textures/hos_misc2/switch2_1
{ 
qer_editorimage textures/hos_models/switch2_1.tga
surfaceparm nomarks
implicitMap textures/hos_models/switch2_1.tga
}

textures/hos_misc2/handrailmetal
{ 
qer_editorimage textures/hos_models/handrailmetal.tga
surfaceparm mat_tin
implicitMap textures/hos_models/handrailmetal.tga
}

textures/hos_misc2/switch
{ 
qer_editorimage textures/hos_models/switch.tga
surfaceparm mat_metal
implicitMap textures/hos_models/switch.tga
}

textures/hos_misc2/fins
{ 
qer_editorimage textures/hos_models/pipemetal4.tga
surfaceparm nolightmap
surfaceparm nonsolid
cull none
implicitMap textures/hos_models/pipemetal4.tga
}

textures/hos_misc2/fins2
{ 
qer_editorimage textures/hos_models/radiator1_side.tga
surfaceparm nolightmap
surfaceparm nonsolid
cull none
implicitMap textures/hos_models/radiator1_side.tga
}

textures/hos_misc2/radiator1
{ 
qer_editorimage textures/hos_models/radiator1.tga
surfaceparm mat_metal
q3map_forceMeta 
q3map_nonplanar 
implicitMap textures/hos_models/radiator1.tga
}

textures/hos_misc2/radiator1_side
{ 
qer_editorimage textures/hos_models/radiator1_side.tga
surfaceparm mat_metal
q3map_forceMeta 
q3map_nonplanar 
implicitMap textures/hos_models/radiator1_side.tga
}

textures/hos_misc2/01
{ 
qer_editorimage textures/hos_models/01.tga
surfaceparm mat_tin
implicitMap textures/hos_models/01.tga
}

textures/hos_misc2/aluminum1
{ 
qer_editorimage textures/hos_models/aluminum1.tga
surfaceparm mat_tin
implicitMap textures/hos_models/aluminum1.tga
}

textures/hos_misc2/ammobox_bottom
{ 
qer_editorimage textures/hos_models/ammobox_bottom.tga
surfaceparm mat_wood
implicitMap textures/hos_models/ammobox_bottom.tga
}

textures/hos_misc2/ammobox_ends
{ 
qer_editorimage textures/hos_models/ammobox_ends.tga
surfaceparm mat_wood
implicitMap textures/hos_models/ammobox_ends.tga
}

textures/hos_misc2/ammobox_sides
{ 
qer_editorimage textures/hos_models/ammobox_sides.tga
surfaceparm mat_wood
implicitMap textures/hos_models/ammobox_sides.tga
}

textures/hos_misc2/ammobox_top
{ 
qer_editorimage textures/hos_models/ammobox_top.tga
surfaceparm mat_wood
implicitMap textures/hos_models/ammobox_top.tga
}

textures/hos_misc2/bookside
{ 
qer_editorimage textures/hos_models/bookside.tga
surfaceparm mat_wood
implicitMap textures/hos_models/bookside.tga
}

textures/hos_misc2/can1
{ 
qer_editorimage textures/hos_models/can1.tga
surfaceparm mat_metal
implicitMap textures/hos_models/can1.tga
}

textures/hos_misc2/can_bottom
{ 
qer_editorimage textures/hos_models/can_bottom.tga
surfaceparm mat_metal
implicitMap textures/hos_models/can_bottom.tga
}

textures/hos_misc2/can_top
{ 
qer_editorimage textures/hos_models/can_top.tga
surfaceparm mat_metal
implicitMap textures/hos_models/can_top.tga
}

textures/hos_misc2/cargobox1_end
{ 
qer_editorimage textures/hos_models/cargobox1_end.tga
surfaceparm mat_metal
implicitMap textures/hos_models/cargobox1_end.tga
}

textures/hos_misc2/cargobox1_side
{ 
qer_editorimage textures/hos_models/cargobox1_side.tga
surfaceparm mat_metal
implicitMap textures/hos_models/cargobox1_side.tga
}

textures/hos_misc2/cargobox2_end
{ 
qer_editorimage textures/hos_models/cargobox2_end.tga
surfaceparm mat_metal
implicitMap textures/hos_models/cargobox2_end.tga
}

textures/hos_misc2/cargobox2_side
{ 
qer_editorimage textures/hos_models/cargobox2_side.tga
surfaceparm mat_metal
implicitMap textures/hos_models/cargobox2_side.tga
}

textures/hos_misc2/ch1
{ 
qer_editorimage textures/hos_models/ch1.tga
surfaceparm mat_metal
implicitMap textures/hos_models/ch1.tga
}

textures/hos_misc2/ch2
{ 
qer_editorimage textures/hos_models/ch2.tga
surfaceparm mat_metal
implicitMap textures/hos_models/ch2.tga
}

textures/hos_misc2/door3
{ 
qer_editorimage textures/hos_models/door3.tga
surfaceparm mat_wood
implicitMap textures/hos_models/door3.tga
}

textures/hos_misc2/duct_b
{ 
qer_editorimage textures/hos_models/duct_b.tga
surfaceparm mat_tin
implicitMap textures/hos_models/duct_b.tga
}

textures/hos_misc2/fanmetal
{ 
qer_editorimage textures/hos_models/fanmetal.tga
surfaceparm mat_tin
implicitMap textures/hos_models/fanmetal.tga
}

textures/hos_misc2/fans
{ 
qer_editorimage textures/hos_models/fans.tga
surfaceparm mat_tin
implicitMap textures/hos_models/fans.tga
}

textures/hos_misc2/fusebox3
{ 
qer_editorimage textures/hos_models/fusebox3.tga
surfaceparm mat_tin
implicitMap textures/hos_models/fusebox3.tga
}

textures/hos_misc2/highvoltage
{ 
qer_editorimage textures/hos_models/highvoltage.tga
surfaceparm mat_tin
implicitMap textures/hos_models/highvoltage.tga
}

textures/hos_misc2/lidc2
{ 
qer_editorimage textures/hos_models/lidc2.tga
surfaceparm mat_tin
implicitMap textures/hos_models/lidc2.tga
}

textures/hos_misc2/lidc2
{ 
qer_editorimage textures/hos_models/lidc2.tga
surfaceparm mat_tin
implicitMap textures/hos_models/lidc2.tga
}


textures/hos_misc2/seal
{ 
qer_editorimage textures/hos_models/seal.tga
surfaceparm mat_tin
implicitMap textures/hos_models/seal.tga
}

textures/hos_misc2/trash2
{ 
qer_editorimage textures/hos_models/trash2.tga
surfaceparm mat_tin
implicitMap textures/hos_models/trash2.tga
}

textures/hos_misc2/tv
{ 
qer_editorimage textures/hos_models/tv.tga
surfaceparm mat_tin
implicitMap textures/hos_models/tv.tga
}

textures/hos_misc2/plywood2
{ 
qer_editorimage textures/hos_models/plywood2.tga
surfaceparm mat_wood
implicitMap textures/hos_models/plywood2.tga
}

textures/hos_misc2/plywood2b
{ 
qer_editorimage textures/hos_models/plywood2b.tga
surfaceparm mat_wood
implicitMap textures/hos_models/plywood2b.tga
}

textures/hos_misc2/plywood2c
{ 
qer_editorimage textures/hos_models/plywood2c.tga
surfaceparm mat_wood
implicitMap textures/hos_models/plywood2c.tga
}

textures/hos_misc2/platform
{ 
qer_editorimage textures/hos_models/platform.tga
surfaceparm mat_tin
implicitMap textures/hos_models/platform.tga
}

textures/hos_misc2/nailedboards
{ 
qer_editorimage textures/hos_models/nailedboards.tga
surfaceparm mat_wood
implicitMap textures/hos_models/nailedboards.tga
}

textures/hos_misc2/metal49
{ 
qer_editorimage textures/hos_models/metal49.tga
surfaceparm mat_tin
implicitMap textures/hos_models/metal49.tga
}

textures/hos_misc2/metal45
{ 
qer_editorimage textures/hos_models/metal45.tga
surfaceparm mat_tin
implicitMap textures/hos_models/metal45.tga
}

textures/hos_misc2/metal44
{ 
qer_editorimage textures/hos_models/metal44.tga
surfaceparm mat_tin
implicitMap textures/hos_models/metal44.tga
}

textures/hos_misc2/metal19
{ 
qer_editorimage textures/hos_models/metal19.tga
surfaceparm mat_tin
implicitMap textures/hos_models/metal19.tga
}

textures/hos_misc2/metal18_s
{ 
qer_editorimage textures/hos_models/metal18_s.tga
surfaceparm mat_tin
implicitMap textures/hos_models/metal18_s.tga
}

textures/hos_misc2/manual
{ 
qer_editorimage textures/hos_models/manual.tga
surfaceparm mat_wood
implicitMap textures/hos_models/manual.tga
}

textures/hos_misc2/light01
{ 
qer_editorimage textures/hos_models/light01.tga
surfaceparm mat_tin
implicitMap textures/hos_models/light01.tga
}

//// From Max Payne (1) Texture Pack (1)

textures/hos_misc2/maxpayne_lamp01
{ 
qer_editorimage textures/hos_models/maxpayne_lamp01.tga
surfaceparm mat_tin
implicitMap textures/hos_models/maxpayne_lamp01.tga
}

textures/hos_misc2/maxpayne_desk01a
{ 
qer_editorimage textures/hos_models/maxpayne_desk01a.tga
surfaceparm mat_wood
implicitMap textures/hos_models/maxpayne_desk01a.tga
}

textures/hos_misc2/maxpayne_desk01a_b
{ 
qer_editorimage textures/hos_models/maxpayne_desk01b.tga
surfaceparm mat_wood
implicitMap textures/hos_models/maxpayne_desk01b.tga
}

textures/hos_misc2/maxpayne_desk01b
{ 
qer_editorimage textures/hos_models/maxpayne_desk01b.tga
surfaceparm mat_wood
implicitMap textures/hos_models/maxpayne_desk01b.tga
}

textures/hos_misc2/maxpayne_cardboard09a2
{ 
qer_editorimage textures/hos_models/maxpayne_cardboard09a2.tga
surfaceparm mat_wood
implicitMap textures/hos_models/maxpayne_cardboard09a2.tga
}

textures/hos_misc2/canvas1
{ 
qer_editorimage textures/hos_models/canvas1.tga
surfaceparm mat_wood
implicitMap textures/hos_models/canvas1.tga
}

textures/hos_misc2/canvas2
{ 
qer_editorimage textures/hos_models/canvas2.tga
surfaceparm mat_wood
implicitMap textures/hos_models/canvas2.tga
}

textures/hos_misc2/canvas3
{ 
qer_editorimage textures/hos_models/canvas3.tga
surfaceparm mat_wood
implicitMap textures/hos_models/canvas3.tga
}


textures/hos_misc2/container_k1
{ 
qer_editorimage textures/hos_models/container_k1.tga
surfaceparm mat_metal
implicitMap textures/hos_models/container_k1.tga
}

textures/hos_misc2/container_k2
{ 
qer_editorimage textures/hos_models/container_k2.tga
surfaceparm mat_metal
implicitMap textures/hos_models/container_k2.tga
}

textures/hos_misc2/container_k3
{ 
qer_editorimage textures/hos_models/container_k3.tga
surfaceparm mat_metal
implicitMap textures/hos_models/container_k3.tga
}

textures/hos_misc2/oilcan
{ 
qer_editorimage textures/hos_models/oilcan.tga
surfaceparm mat_tin
implicitMap textures/hos_models/oilcan.tga
}

textures/hos_misc2/oilcan2
{ 
qer_editorimage textures/hos_models/oilcan2.tga
surfaceparm mat_tin
implicitMap textures/hos_models/oilcan2.tga
}

textures/hos_misc2/roll
{ 
qer_editorimage textures/hos_models/roll.tga
surfaceparm mat_wood
implicitMap textures/hos_models/roll.tga
}

















