// Custom shader file for obj_alcatraz_b3.bsp
// Generated by Q3Map2 (ydnar)
// Do not edit! This file is overwritten on recompiles.

obj_alcatraz_b3/D91E1CE8C0A7675AF6376C9037BCF238
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/obj_alcatraz_b3/lm_0007.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 2
		tcGen lightmap
	}

	{
		map textures/re_concrete/concrete_sss.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

obj_alcatraz_b3/FAF34375D1D75C7EAC2E40E629667AC9
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/obj_alcatraz_b3/lm_0007.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 2
		tcGen lightmap
	}

	{
		map textures/re_concrete/concrete_sst.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

obj_alcatraz_b3/71E9C3681B7B0B8DFE0C181078A11206
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/obj_alcatraz_b3/lm_0006.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 2
		tcGen lightmap
	}

	{
		map textures/re_concrete/cement_ss1.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

obj_alcatraz_b3/C8F9D33D08F55B1635D208A0CF5FFFC7
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/obj_alcatraz_b3/lm_0007.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 2
		tcGen lightmap
	}

	{
		map textures/re_concrete/cement_ss1.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

obj_alcatraz_b3/D0D6A74B0CC150E7B8E676C5B2D7937D
{ // Q3Map2 defaulted (implicitMap)
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/obj_alcatraz_b3/lm_0003.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 2
		tcGen lightmap
	}

	{
		map textures/liq/bm_metal1.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

obj_alcatraz_b3/FD6D7E7B706C1581D3BD83FFE305A046
{ // Q3Map2 defaulted (implicitMap)
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/obj_alcatraz_b3/lm_0003.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 2
		tcGen lightmap
		tcMod transform 1 0 0 1 -0.50000 -0.50000
	}

	{
		map textures/liq/bm_metal1.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

obj_alcatraz_b3/8E16852D327B45E058439C1A69FB0D19
{ // Q3Map2 defaulted (implicitMap)
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 2
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 0.50000
	}

	{
		map textures/liq/bm_metal1.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

obj_alcatraz_b3/6D99789954ABCD3A230E524FC3987705
{ // Q3Map2 defaulted (implicitMap)
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 2
		tcGen lightmap
		tcMod transform 1 0 0 1 0.50000 0.00000
	}

	{
		map textures/metal_misc/metal_m04r2.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

