// Custom shader file for zp_r2_pipes.bsp
// Generated by Q3Map2 (ydnar)
// Do not edit! This file is overwritten on recompiles.

zp_r2_pipes/28638B5F05637B4733D110C188C8FE26
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/zp_r2_pipes/lm_0000.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 32
		tcGen lightmap
	}

	{
		map textures/zp_tx_1/conc.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

zp_r2_pipes/47306BC8DD0D5FE4F5501ECDFC82FFB5
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/zp_r2_pipes/lm_0000.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 32
		tcGen lightmap
	}

	{
		map textures/liquids/kc_fogcloud3_alpha.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

zp_r2_pipes/9AF1E32E3F381EFEC669A2E66CB4804B
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/zp_r2_pipes/lm_0000.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 32
		tcGen lightmap
	}

	{
		map textures/assault/awall_m02.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

zp_r2_pipes/8879A01CC3E9D13C54B4C3FD8E40978B
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/zp_r2_pipes/lm_0000.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 32
		tcGen lightmap
	}

	{
		map textures/swf/spipe_05a.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

zp_r2_pipes/803BA034EB488700B71162D461DFF5BA
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/zp_r2_pipes/lm_0000.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 32
		tcGen lightmap
	}

	{
		map textures/metal_misc/ametal_m03_bak.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

zp_r2_pipes/FD49F0E47E8F0447BF5A1E31F9BD38AD
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/zp_r2_pipes/lm_0000.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 32
		tcGen lightmap
	}

	{
		map textures/xlab_props/sign_c09.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

zp_r2_pipes/932A57054DCC67F408A261633761795D
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/zp_r2_pipes/lm_0000.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 32
		tcGen lightmap
	}

	{
		map textures/xlab_props/sign_c11.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

zp_r2_pipes/A6DC1AF84CDA9B407D3C2B1FE1DEB71E
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/zp_r2_pipes/lm_0000.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 32
		tcGen lightmap
	}

	{
		map textures/xlab_props/sign_c31a.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

zp_r2_pipes/018A98765C3D6917E1FE3FB5295879FE
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/zp_r2_pipes/lm_0000.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 32
		tcGen lightmap
	}

	{
		map textures/swf/door_m01aswf.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

zp_r2_pipes/1DEF10EF10134B0B4EFEB5CDEE14F93C
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/zp_r2_pipes/lm_0000.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 32
		tcGen lightmap
	}

	{
		map textures/assault/awall_m04.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

zp_r2_pipes/57FF594364AD7195BFF14F5A1083AF6D
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/zp_r2_pipes/lm_0000.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 32
		tcGen lightmap
	}

	{
		map textures/swf/xconcrete_m01_r.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

