// Generated by Frozen Sand Particle Studio
// Tue Nov 17 01:01:40 2009


textures/runy9/fallssplashpetit
{
	qer_editorimage textures/runy9/raiderssplash01.tga
	q3map_cloneshader textures/runy9/zzfallssplashpetit_1
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 45 sawtooth 0 1 0 0.9459
	deformvertexes move -6.84646 -24.0442 0 square 0 1 0 0.9459
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raiderssplash01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0 0.9459
		alphagen wave square 0 1 0 0.9459
		tcMod rotate -22
		tcMod stretch sin 0.7 0.7466 0 0.9459
	}
}

textures/runy9/zzfallssplashpetit_1
{
	qer_editorimage textures/runy9/raiderssplash01.tga
	q3map_cloneshader textures/runy9/zzfallssplashpetit_2
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 45 sawtooth 0 1 0.0557606 0.9459
	deformvertexes move 24.2119 -6.22781 0 square 0 1 0.0557606 0.9459
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raiderssplash01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.0557606 0.9459
		alphagen wave square 0 1 0.0557606 0.9459
		tcMod rotate 13
		tcMod stretch sin 0.7 0.7466 0.0557606 0.9459
	}
}

textures/runy9/zzfallssplashpetit_2
{
	qer_editorimage textures/runy9/raiderssplash01.tga
	q3map_cloneshader textures/runy9/zzfallssplashpetit_3
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 45 sawtooth 0 1 0.108743 0.9459
	deformvertexes move -40.8826 -9.62356 0 square 0 1 0.108743 0.9459
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raiderssplash01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.108743 0.9459
		alphagen wave square 0 1 0.108743 0.9459
		tcMod rotate -4
		tcMod stretch sin 0.7 0.7466 0.108743 0.9459
	}
}

textures/runy9/zzfallssplashpetit_3
{
	qer_editorimage textures/runy9/raiderssplash01.tga
	q3map_cloneshader textures/runy9/zzfallssplashpetit_4
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 45 sawtooth 0 1 0.160724 0.9459
	deformvertexes move -54.7617 -15.8165 0 square 0 1 0.160724 0.9459
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raiderssplash01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.160724 0.9459
		alphagen wave square 0 1 0.160724 0.9459
		tcMod rotate 4
		tcMod stretch sin 0.7 0.7466 0.160724 0.9459
	}
}

textures/runy9/zzfallssplashpetit_4
{
	qer_editorimage textures/runy9/raiderssplash01.tga
	q3map_cloneshader textures/runy9/zzfallssplashpetit_5
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 45 sawtooth 0 1 0.212067 0.9459
	deformvertexes move -31.9874 -0.899629 0 square 0 1 0.212067 0.9459
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raiderssplash01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.212067 0.9459
		alphagen wave square 0 1 0.212067 0.9459
		tcMod rotate 12
		tcMod stretch sin 0.7 0.7466 0.212067 0.9459
	}
}

textures/runy9/zzfallssplashpetit_5
{
	qer_editorimage textures/runy9/raiderssplash01.tga
	q3map_cloneshader textures/runy9/zzfallssplashpetit_6
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 45 sawtooth 0 1 0.262939 0.9459
	deformvertexes move -20.9984 -0.262422 0 square 0 1 0.262939 0.9459
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raiderssplash01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.262939 0.9459
		alphagen wave square 0 1 0.262939 0.9459
		tcMod stretch sin 0.7 0.7466 0.262939 0.9459
	}
}

textures/runy9/zzfallssplashpetit_6
{
	qer_editorimage textures/runy9/raiderssplash01.tga
	q3map_cloneshader textures/runy9/zzfallssplashpetit_7
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 45 sawtooth 0 1 0.31344 0.9459
	deformvertexes move -12.0274 -8.96333 0 square 0 1 0.31344 0.9459
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raiderssplash01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.31344 0.9459
		alphagen wave square 0 1 0.31344 0.9459
		tcMod rotate -11
		tcMod stretch sin 0.7 0.7466 0.31344 0.9459
	}
}

textures/runy9/zzfallssplashpetit_7
{
	qer_editorimage textures/runy9/raiderssplash01.tga
	q3map_cloneshader textures/runy9/zzfallssplashpetit_8
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 45 sawtooth 0 1 0.363634 0.9459
	deformvertexes move 28.3401 -14.8606 0 square 0 1 0.363634 0.9459
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raiderssplash01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.363634 0.9459
		alphagen wave square 0 1 0.363634 0.9459
		tcMod rotate -13
		tcMod stretch sin 0.7 0.7466 0.363634 0.9459
	}
}

textures/runy9/zzfallssplashpetit_8
{
	qer_editorimage textures/runy9/raiderssplash01.tga
	q3map_cloneshader textures/runy9/zzfallssplashpetit_9
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 45 sawtooth 0 1 0.413566 0.9459
	deformvertexes move 18.1146 -21.3509 0 square 0 1 0.413566 0.9459
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raiderssplash01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.413566 0.9459
		alphagen wave square 0 1 0.413566 0.9459
		tcMod rotate -16
		tcMod stretch sin 0.7 0.7466 0.413566 0.9459
	}
}

textures/runy9/zzfallssplashpetit_9
{
	qer_editorimage textures/runy9/raiderssplash01.tga
	q3map_cloneshader textures/runy9/zzfallssplashpetit_10
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 45 sawtooth 0 1 0.463271 0.9459
	deformvertexes move -42.2502 -24.8178 0 square 0 1 0.463271 0.9459
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raiderssplash01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.463271 0.9459
		alphagen wave square 0 1 0.463271 0.9459
		tcMod rotate 22
		tcMod stretch sin 0.7 0.7466 0.463271 0.9459
	}
}

textures/runy9/zzfallssplashpetit_10
{
	qer_editorimage textures/runy9/raiderssplash01.tga
	q3map_cloneshader textures/runy9/zzfallssplashpetit_11
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 45 sawtooth 0 1 0.512776 0.9459
	deformvertexes move 5.12375 -10.8511 0 square 0 1 0.512776 0.9459
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raiderssplash01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.512776 0.9459
		alphagen wave square 0 1 0.512776 0.9459
		tcMod rotate 1
		tcMod stretch sin 0.7 0.7466 0.512776 0.9459
	}
}

textures/runy9/zzfallssplashpetit_11
{
	qer_editorimage textures/runy9/raiderssplash01.tga
	q3map_cloneshader textures/runy9/zzfallssplashpetit_12
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 45 sawtooth 0 1 0.5621 0.9459
	deformvertexes move -14.238 -29.7704 0 square 0 1 0.5621 0.9459
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raiderssplash01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.5621 0.9459
		alphagen wave square 0 1 0.5621 0.9459
		tcMod rotate -13
		tcMod stretch sin 0.7 0.7466 0.5621 0.9459
	}
}

textures/runy9/zzfallssplashpetit_12
{
	qer_editorimage textures/runy9/raiderssplash01.tga
	q3map_cloneshader textures/runy9/zzfallssplashpetit_13
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 45 sawtooth 0 1 0.611261 0.9459
	deformvertexes move 23.2792 -15.5588 0 square 0 1 0.611261 0.9459
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raiderssplash01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.611261 0.9459
		alphagen wave square 0 1 0.611261 0.9459
		tcMod rotate -2
		tcMod stretch sin 0.7 0.7466 0.611261 0.9459
	}
}

textures/runy9/zzfallssplashpetit_13
{
	qer_editorimage textures/runy9/raiderssplash01.tga
	q3map_cloneshader textures/runy9/zzfallssplashpetit_14
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 45 sawtooth 0 1 0.660273 0.9459
	deformvertexes move -0.803369 -12.9752 0 square 0 1 0.660273 0.9459
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raiderssplash01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.660273 0.9459
		alphagen wave square 0 1 0.660273 0.9459
		tcMod rotate 1
		tcMod stretch sin 0.7 0.7466 0.660273 0.9459
	}
}

textures/runy9/zzfallssplashpetit_14
{
	qer_editorimage textures/runy9/raiderssplash01.tga
	q3map_cloneshader textures/runy9/zzfallssplashpetit_15
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 45 sawtooth 0 1 0.709147 0.9459
	deformvertexes move 32.7847 -3.76375 0 square 0 1 0.709147 0.9459
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raiderssplash01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.709147 0.9459
		alphagen wave square 0 1 0.709147 0.9459
		tcMod rotate -15
		tcMod stretch sin 0.7 0.7466 0.709147 0.9459
	}
}

textures/runy9/zzfallssplashpetit_15
{
	qer_editorimage textures/runy9/raiderssplash01.tga
	q3map_cloneshader textures/runy9/zzfallssplashpetit_16
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 45 sawtooth 0 1 0.757895 0.9459
	deformvertexes move 1.23143 -16.9553 0 square 0 1 0.757895 0.9459
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raiderssplash01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.757895 0.9459
		alphagen wave square 0 1 0.757895 0.9459
		tcMod rotate 5
		tcMod stretch sin 0.7 0.7466 0.757895 0.9459
	}
}

textures/runy9/zzfallssplashpetit_16
{
	qer_editorimage textures/runy9/raiderssplash01.tga
	q3map_cloneshader textures/runy9/zzfallssplashpetit_17
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 45 sawtooth 0 1 0.806524 0.9459
	deformvertexes move -44.8584 -14.026 0 square 0 1 0.806524 0.9459
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raiderssplash01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.806524 0.9459
		alphagen wave square 0 1 0.806524 0.9459
		tcMod rotate -15
		tcMod stretch sin 0.7 0.7466 0.806524 0.9459
	}
}

textures/runy9/zzfallssplashpetit_17
{
	qer_editorimage textures/runy9/raiderssplash01.tga
	q3map_cloneshader textures/runy9/zzfallssplashpetit_18
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 45 sawtooth 0 1 0.855043 0.9459
	deformvertexes move 41.0676 -20.7232 0 square 0 1 0.855043 0.9459
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raiderssplash01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.855043 0.9459
		alphagen wave square 0 1 0.855043 0.9459
		tcMod rotate 6
		tcMod stretch sin 0.7 0.7466 0.855043 0.9459
	}
}

textures/runy9/zzfallssplashpetit_18
{
	qer_editorimage textures/runy9/raiderssplash01.tga
	q3map_cloneshader textures/runy9/zzfallssplashpetit_19
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 45 sawtooth 0 1 0.903458 0.9459
	deformvertexes move 49.2488 -16.6899 0 square 0 1 0.903458 0.9459
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raiderssplash01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.903458 0.9459
		alphagen wave square 0 1 0.903458 0.9459
		tcMod rotate -1
		tcMod stretch sin 0.7 0.7466 0.903458 0.9459
	}
}

textures/runy9/zzfallssplashpetit_19
{
	qer_editorimage textures/runy9/raiderssplash01.tga
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 45 sawtooth 0 1 0.951775 0.9459
	deformvertexes move 4.59522 -19.4649 0 square 0 1 0.951775 0.9459
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raiderssplash01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.951775 0.9459
		alphagen wave square 0 1 0.951775 0.9459
		tcMod rotate -4
		tcMod stretch sin 0.7 0.7466 0.951775 0.9459
	}
}

