// Generated by Frozen Sand Particle Studio
// Tue Nov 17 00:54:11 2009


textures/runy9/fallscentrelarge
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentrelarge_1
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0 0.9639
	deformvertexes move 44.7559 -114.568 0 square 0 1 0 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0 0.9639
		alphagen wave square 0 1 0 0.9639
		tcMod rotate -22
		tcMod stretch sin 0.7533 0.7466 0 0.9639
	}
}

textures/runy9/zzfallscentrelarge_1
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentrelarge_2
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.01 0.9639
	deformvertexes move -26.9933 -83.7578 0 square 0 1 0.01 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.01 0.9639
		alphagen wave square 0 1 0.01 0.9639
		tcMod rotate -60
		tcMod stretch sin 0.7533 0.7466 0.01 0.9639
	}
}

textures/runy9/zzfallscentrelarge_2
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentrelarge_3
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.02 0.9639
	deformvertexes move -16.3968 -76.2571 0 square 0 1 0.02 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.02 0.9639
		alphagen wave square 0 1 0.02 0.9639
		tcMod rotate 55
		tcMod stretch sin 0.7533 0.7466 0.02 0.9639
	}
}

textures/runy9/zzfallscentrelarge_3
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentrelarge_4
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.03 0.9639
	deformvertexes move 111.95 -3.35389 0 square 0 1 0.03 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.03 0.9639
		alphagen wave square 0 1 0.03 0.9639
		tcMod rotate -83
		tcMod stretch sin 0.7533 0.7466 0.03 0.9639
	}
}

textures/runy9/zzfallscentrelarge_4
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentrelarge_5
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.04 0.9639
	deformvertexes move 26.17 -114.036 0 square 0 1 0.04 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.04 0.9639
		alphagen wave square 0 1 0.04 0.9639
		tcMod rotate -31
		tcMod stretch sin 0.7533 0.7466 0.04 0.9639
	}
}

textures/runy9/zzfallscentrelarge_5
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentrelarge_6
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.05 0.9639
	deformvertexes move -32.1842 -110.405 0 square 0 1 0.05 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.05 0.9639
		alphagen wave square 0 1 0.05 0.9639
		tcMod rotate 9
		tcMod stretch sin 0.7533 0.7466 0.05 0.9639
	}
}

textures/runy9/zzfallscentrelarge_6
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentrelarge_7
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.06 0.9639
	deformvertexes move 55.9398 -73.0393 0 square 0 1 0.06 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.06 0.9639
		alphagen wave square 0 1 0.06 0.9639
		tcMod rotate -26
		tcMod stretch sin 0.7533 0.7466 0.06 0.9639
	}
}

textures/runy9/zzfallscentrelarge_7
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentrelarge_8
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.07 0.9639
	deformvertexes move 90.3754 -42.8052 0 square 0 1 0.07 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.07 0.9639
		alphagen wave square 0 1 0.07 0.9639
		tcMod rotate 20
		tcMod stretch sin 0.7533 0.7466 0.07 0.9639
	}
}

textures/runy9/zzfallscentrelarge_8
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentrelarge_9
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.08 0.9639
	deformvertexes move -14.4089 -91.877 0 square 0 1 0.08 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.08 0.9639
		alphagen wave square 0 1 0.08 0.9639
		tcMod rotate -68
		tcMod stretch sin 0.7533 0.7466 0.08 0.9639
	}
}

textures/runy9/zzfallscentrelarge_9
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentrelarge_10
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.09 0.9639
	deformvertexes move -81.288 -38.6297 0 square 0 1 0.09 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.09 0.9639
		alphagen wave square 0 1 0.09 0.9639
		tcMod rotate 49
		tcMod stretch sin 0.7533 0.7466 0.09 0.9639
	}
}

textures/runy9/zzfallscentrelarge_10
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentrelarge_11
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.1 0.9639
	deformvertexes move 59.8941 -87.4568 0 square 0 1 0.1 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.1 0.9639
		alphagen wave square 0 1 0.1 0.9639
		tcMod rotate -82
		tcMod stretch sin 0.7533 0.7466 0.1 0.9639
	}
}

textures/runy9/zzfallscentrelarge_11
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentrelarge_12
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.11 0.9639
	deformvertexes move -118.234 -37.3742 0 square 0 1 0.11 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.11 0.9639
		alphagen wave square 0 1 0.11 0.9639
		tcMod rotate 28
		tcMod stretch sin 0.7533 0.7466 0.11 0.9639
	}
}

textures/runy9/zzfallscentrelarge_12
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentrelarge_13
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.12 0.9639
	deformvertexes move -111.885 -15.834 0 square 0 1 0.12 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.12 0.9639
		alphagen wave square 0 1 0.12 0.9639
		tcMod rotate -48
		tcMod stretch sin 0.7533 0.7466 0.12 0.9639
	}
}

textures/runy9/zzfallscentrelarge_13
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentrelarge_14
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.13 0.9639
	deformvertexes move -5.63641 -121.87 0 square 0 1 0.13 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.13 0.9639
		alphagen wave square 0 1 0.13 0.9639
		tcMod rotate -20
		tcMod stretch sin 0.7533 0.7466 0.13 0.9639
	}
}

textures/runy9/zzfallscentrelarge_14
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentrelarge_15
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.14 0.9639
	deformvertexes move 79.2306 -88.7891 0 square 0 1 0.14 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.14 0.9639
		alphagen wave square 0 1 0.14 0.9639
		tcMod rotate -44
		tcMod stretch sin 0.7533 0.7466 0.14 0.9639
	}
}

textures/runy9/zzfallscentrelarge_15
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentrelarge_16
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.15 0.9639
	deformvertexes move -107.966 -2.69899 0 square 0 1 0.15 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.15 0.9639
		alphagen wave square 0 1 0.15 0.9639
		tcMod rotate -73
		tcMod stretch sin 0.7533 0.7466 0.15 0.9639
	}
}

textures/runy9/zzfallscentrelarge_16
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentrelarge_17
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.16 0.9639
	deformvertexes move 115.469 -42.3769 0 square 0 1 0.16 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.16 0.9639
		alphagen wave square 0 1 0.16 0.9639
		tcMod rotate -43
		tcMod stretch sin 0.7533 0.7466 0.16 0.9639
	}
}

textures/runy9/zzfallscentrelarge_17
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentrelarge_18
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.17 0.9639
	deformvertexes move -18.5325 -103.352 0 square 0 1 0.17 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.17 0.9639
		alphagen wave square 0 1 0.17 0.9639
		tcMod rotate -26
		tcMod stretch sin 0.7533 0.7466 0.17 0.9639
	}
}

textures/runy9/zzfallscentrelarge_18
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentrelarge_19
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.18 0.9639
	deformvertexes move 27.2884 -118.909 0 square 0 1 0.18 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.18 0.9639
		alphagen wave square 0 1 0.18 0.9639
		tcMod rotate 16
		tcMod stretch sin 0.7533 0.7466 0.18 0.9639
	}
}

textures/runy9/zzfallscentrelarge_19
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentrelarge_20
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.19 0.9639
	deformvertexes move 71.7978 -47.3401 0 square 0 1 0.19 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.19 0.9639
		alphagen wave square 0 1 0.19 0.9639
		tcMod rotate 38
		tcMod stretch sin 0.7533 0.7466 0.19 0.9639
	}
}

textures/runy9/zzfallscentrelarge_20
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentrelarge_21
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.2 0.9639
	deformvertexes move -40.6417 -79.1786 0 square 0 1 0.2 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.2 0.9639
		alphagen wave square 0 1 0.2 0.9639
		tcMod rotate 21
		tcMod stretch sin 0.7533 0.7466 0.2 0.9639
	}
}

textures/runy9/zzfallscentrelarge_21
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentrelarge_22
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.21 0.9639
	deformvertexes move -49.8067 -110.274 0 square 0 1 0.21 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.21 0.9639
		alphagen wave square 0 1 0.21 0.9639
		tcMod rotate 72
		tcMod stretch sin 0.7533 0.7466 0.21 0.9639
	}
}

textures/runy9/zzfallscentrelarge_22
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentrelarge_23
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.22 0.9639
	deformvertexes move 103.646 -22.2159 0 square 0 1 0.22 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.22 0.9639
		alphagen wave square 0 1 0.22 0.9639
		tcMod rotate -27
		tcMod stretch sin 0.7533 0.7466 0.22 0.9639
	}
}

textures/runy9/zzfallscentrelarge_23
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentrelarge_24
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.23 0.9639
	deformvertexes move -46.528 -99.6752 0 square 0 1 0.23 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.23 0.9639
		alphagen wave square 0 1 0.23 0.9639
		tcMod rotate -56
		tcMod stretch sin 0.7533 0.7466 0.23 0.9639
	}
}

textures/runy9/zzfallscentrelarge_24
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentrelarge_25
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.24 0.9639
	deformvertexes move -113.182 -29.6462 0 square 0 1 0.24 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.24 0.9639
		alphagen wave square 0 1 0.24 0.9639
		tcMod rotate 14
		tcMod stretch sin 0.7533 0.7466 0.24 0.9639
	}
}

textures/runy9/zzfallscentrelarge_25
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentrelarge_26
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.25 0.9639
	deformvertexes move -75.5985 -54.1652 0 square 0 1 0.25 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.25 0.9639
		alphagen wave square 0 1 0.25 0.9639
		tcMod rotate -80
		tcMod stretch sin 0.7533 0.7466 0.25 0.9639
	}
}

textures/runy9/zzfallscentrelarge_26
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentrelarge_27
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.26 0.9639
	deformvertexes move -54.4548 -80.2725 0 square 0 1 0.26 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.26 0.9639
		alphagen wave square 0 1 0.26 0.9639
		tcMod rotate 57
		tcMod stretch sin 0.7533 0.7466 0.26 0.9639
	}
}

textures/runy9/zzfallscentrelarge_27
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentrelarge_28
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.27 0.9639
	deformvertexes move -79.0616 -25.2637 0 square 0 1 0.27 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.27 0.9639
		alphagen wave square 0 1 0.27 0.9639
		tcMod rotate -29
		tcMod stretch sin 0.7533 0.7466 0.27 0.9639
	}
}

textures/runy9/zzfallscentrelarge_28
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentrelarge_29
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.28 0.9639
	deformvertexes move 5.17311 -81.8367 0 square 0 1 0.28 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.28 0.9639
		alphagen wave square 0 1 0.28 0.9639
		tcMod rotate 24
		tcMod stretch sin 0.7533 0.7466 0.28 0.9639
	}
}

textures/runy9/zzfallscentrelarge_29
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentrelarge_30
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.29 0.9639
	deformvertexes move -53.7903 -84.3007 0 square 0 1 0.29 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.29 0.9639
		alphagen wave square 0 1 0.29 0.9639
		tcMod rotate -81
		tcMod stretch sin 0.7533 0.7466 0.29 0.9639
	}
}

textures/runy9/zzfallscentrelarge_30
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentrelarge_31
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.3 0.9639
	deformvertexes move -87.5853 -57.9121 0 square 0 1 0.3 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.3 0.9639
		alphagen wave square 0 1 0.3 0.9639
		tcMod rotate -70
		tcMod stretch sin 0.7533 0.7466 0.3 0.9639
	}
}

textures/runy9/zzfallscentrelarge_31
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentrelarge_32
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.31 0.9639
	deformvertexes move 41.5616 -112.573 0 square 0 1 0.31 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.31 0.9639
		alphagen wave square 0 1 0.31 0.9639
		tcMod rotate 31
		tcMod stretch sin 0.7533 0.7466 0.31 0.9639
	}
}

textures/runy9/zzfallscentrelarge_32
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentrelarge_33
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.32 0.9639
	deformvertexes move -85.3203 -17.0131 0 square 0 1 0.32 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.32 0.9639
		alphagen wave square 0 1 0.32 0.9639
		tcMod rotate -56
		tcMod stretch sin 0.7533 0.7466 0.32 0.9639
	}
}

textures/runy9/zzfallscentrelarge_33
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentrelarge_34
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.33 0.9639
	deformvertexes move -68.541 -32.8349 0 square 0 1 0.33 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.33 0.9639
		alphagen wave square 0 1 0.33 0.9639
		tcMod rotate 59
		tcMod stretch sin 0.7533 0.7466 0.33 0.9639
	}
}

textures/runy9/zzfallscentrelarge_34
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentrelarge_35
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.34 0.9639
	deformvertexes move 10.141 -123.585 0 square 0 1 0.34 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.34 0.9639
		alphagen wave square 0 1 0.34 0.9639
		tcMod rotate -34
		tcMod stretch sin 0.7533 0.7466 0.34 0.9639
	}
}

textures/runy9/zzfallscentrelarge_35
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentrelarge_36
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.35 0.9639
	deformvertexes move 112.639 -9.02313 0 square 0 1 0.35 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.35 0.9639
		alphagen wave square 0 1 0.35 0.9639
		tcMod rotate -65
		tcMod stretch sin 0.7533 0.7466 0.35 0.9639
	}
}

textures/runy9/zzfallscentrelarge_36
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentrelarge_37
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.36 0.9639
	deformvertexes move 16.6856 -97.5838 0 square 0 1 0.36 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.36 0.9639
		alphagen wave square 0 1 0.36 0.9639
		tcMod rotate 64
		tcMod stretch sin 0.7533 0.7466 0.36 0.9639
	}
}

textures/runy9/zzfallscentrelarge_37
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentrelarge_38
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.37 0.9639
	deformvertexes move -113.543 -28.2296 0 square 0 1 0.37 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.37 0.9639
		alphagen wave square 0 1 0.37 0.9639
		tcMod rotate -46
		tcMod stretch sin 0.7533 0.7466 0.37 0.9639
	}
}

textures/runy9/zzfallscentrelarge_38
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentrelarge_39
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.38 0.9639
	deformvertexes move 66.0772 -68.2554 0 square 0 1 0.38 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.38 0.9639
		alphagen wave square 0 1 0.38 0.9639
		tcMod rotate 11
		tcMod stretch sin 0.7533 0.7466 0.38 0.9639
	}
}

textures/runy9/zzfallscentrelarge_39
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentrelarge_40
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.39 0.9639
	deformvertexes move 80.1186 -51.0491 0 square 0 1 0.39 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.39 0.9639
		alphagen wave square 0 1 0.39 0.9639
		tcMod rotate -74
		tcMod stretch sin 0.7533 0.7466 0.39 0.9639
	}
}

textures/runy9/zzfallscentrelarge_40
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentrelarge_41
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.4 0.9639
	deformvertexes move -76.02 -30.7403 0 square 0 1 0.4 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.4 0.9639
		alphagen wave square 0 1 0.4 0.9639
		tcMod rotate -61
		tcMod stretch sin 0.7533 0.7466 0.4 0.9639
	}
}

textures/runy9/zzfallscentrelarge_41
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentrelarge_42
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.41 0.9639
	deformvertexes move 25.7804 -94.5483 0 square 0 1 0.41 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.41 0.9639
		alphagen wave square 0 1 0.41 0.9639
		tcMod rotate 48
		tcMod stretch sin 0.7533 0.7466 0.41 0.9639
	}
}

textures/runy9/zzfallscentrelarge_42
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentrelarge_43
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.42 0.9639
	deformvertexes move -49.4499 -99.3766 0 square 0 1 0.42 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.42 0.9639
		alphagen wave square 0 1 0.42 0.9639
		tcMod rotate -23
		tcMod stretch sin 0.7533 0.7466 0.42 0.9639
	}
}

textures/runy9/zzfallscentrelarge_43
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentrelarge_44
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.43 0.9639
	deformvertexes move 69.962 -70.0451 0 square 0 1 0.43 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.43 0.9639
		alphagen wave square 0 1 0.43 0.9639
		tcMod rotate -45
		tcMod stretch sin 0.7533 0.7466 0.43 0.9639
	}
}

textures/runy9/zzfallscentrelarge_44
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentrelarge_45
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.44 0.9639
	deformvertexes move 33.3118 -69.4213 0 square 0 1 0.44 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.44 0.9639
		alphagen wave square 0 1 0.44 0.9639
		tcMod rotate -64
		tcMod stretch sin 0.7533 0.7466 0.44 0.9639
	}
}

textures/runy9/zzfallscentrelarge_45
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentrelarge_46
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.45 0.9639
	deformvertexes move -91.8912 -48.7032 0 square 0 1 0.45 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.45 0.9639
		alphagen wave square 0 1 0.45 0.9639
		tcMod rotate 64
		tcMod stretch sin 0.7533 0.7466 0.45 0.9639
	}
}

textures/runy9/zzfallscentrelarge_46
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentrelarge_47
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.46 0.9639
	deformvertexes move 94.4346 -29.7171 0 square 0 1 0.46 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.46 0.9639
		alphagen wave square 0 1 0.46 0.9639
		tcMod rotate -74
		tcMod stretch sin 0.7533 0.7466 0.46 0.9639
	}
}

textures/runy9/zzfallscentrelarge_47
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentrelarge_48
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.47 0.9639
	deformvertexes move -3.35202 -90.9382 0 square 0 1 0.47 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.47 0.9639
		alphagen wave square 0 1 0.47 0.9639
		tcMod rotate 23
		tcMod stretch sin 0.7533 0.7466 0.47 0.9639
	}
}

textures/runy9/zzfallscentrelarge_48
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentrelarge_49
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.48 0.9639
	deformvertexes move -75.1135 -16.94 0 square 0 1 0.48 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.48 0.9639
		alphagen wave square 0 1 0.48 0.9639
		tcMod rotate 66
		tcMod stretch sin 0.7533 0.7466 0.48 0.9639
	}
}

textures/runy9/zzfallscentrelarge_49
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentrelarge_50
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.49 0.9639
	deformvertexes move 75.0156 -27.7968 0 square 0 1 0.49 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.49 0.9639
		alphagen wave square 0 1 0.49 0.9639
		tcMod rotate 26
		tcMod stretch sin 0.7533 0.7466 0.49 0.9639
	}
}

textures/runy9/zzfallscentrelarge_50
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentrelarge_51
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.5 0.9639
	deformvertexes move 14.3251 -80.739 0 square 0 1 0.5 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.5 0.9639
		alphagen wave square 0 1 0.5 0.9639
		tcMod rotate -59
		tcMod stretch sin 0.7533 0.7466 0.5 0.9639
	}
}

textures/runy9/zzfallscentrelarge_51
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentrelarge_52
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.51 0.9639
	deformvertexes move 108.916 -36.9104 0 square 0 1 0.51 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.51 0.9639
		alphagen wave square 0 1 0.51 0.9639
		tcMod rotate -18
		tcMod stretch sin 0.7533 0.7466 0.51 0.9639
	}
}

textures/runy9/zzfallscentrelarge_52
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentrelarge_53
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.52 0.9639
	deformvertexes move 72.6913 -25.3963 0 square 0 1 0.52 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.52 0.9639
		alphagen wave square 0 1 0.52 0.9639
		tcMod rotate 41
		tcMod stretch sin 0.7533 0.7466 0.52 0.9639
	}
}

textures/runy9/zzfallscentrelarge_53
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentrelarge_54
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.53 0.9639
	deformvertexes move 101.439 -10.6831 0 square 0 1 0.53 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.53 0.9639
		alphagen wave square 0 1 0.53 0.9639
		tcMod rotate -1
		tcMod stretch sin 0.7533 0.7466 0.53 0.9639
	}
}

textures/runy9/zzfallscentrelarge_54
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentrelarge_55
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.54 0.9639
	deformvertexes move 73.3864 -38.7742 0 square 0 1 0.54 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.54 0.9639
		alphagen wave square 0 1 0.54 0.9639
		tcMod rotate -71
		tcMod stretch sin 0.7533 0.7466 0.54 0.9639
	}
}

textures/runy9/zzfallscentrelarge_55
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentrelarge_56
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.55 0.9639
	deformvertexes move -35.1075 -75.2095 0 square 0 1 0.55 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.55 0.9639
		alphagen wave square 0 1 0.55 0.9639
		tcMod rotate 33
		tcMod stretch sin 0.7533 0.7466 0.55 0.9639
	}
}

textures/runy9/zzfallscentrelarge_56
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentrelarge_57
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.56 0.9639
	deformvertexes move 29.3391 -78.7097 0 square 0 1 0.56 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.56 0.9639
		alphagen wave square 0 1 0.56 0.9639
		tcMod rotate -81
		tcMod stretch sin 0.7533 0.7466 0.56 0.9639
	}
}

textures/runy9/zzfallscentrelarge_57
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentrelarge_58
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.57 0.9639
	deformvertexes move 32.6714 -110.261 0 square 0 1 0.57 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.57 0.9639
		alphagen wave square 0 1 0.57 0.9639
		tcMod rotate -50
		tcMod stretch sin 0.7533 0.7466 0.57 0.9639
	}
}

textures/runy9/zzfallscentrelarge_58
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentrelarge_59
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.58 0.9639
	deformvertexes move -38.676 -107.239 0 square 0 1 0.58 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.58 0.9639
		alphagen wave square 0 1 0.58 0.9639
		tcMod rotate 78
		tcMod stretch sin 0.7533 0.7466 0.58 0.9639
	}
}

textures/runy9/zzfallscentrelarge_59
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentrelarge_60
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.59 0.9639
	deformvertexes move 40.022 -71.5698 0 square 0 1 0.59 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.59 0.9639
		alphagen wave square 0 1 0.59 0.9639
		tcMod rotate 60
		tcMod stretch sin 0.7533 0.7466 0.59 0.9639
	}
}

textures/runy9/zzfallscentrelarge_60
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentrelarge_61
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.6 0.9639
	deformvertexes move -73.4113 -15.3551 0 square 0 1 0.6 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.6 0.9639
		alphagen wave square 0 1 0.6 0.9639
		tcMod rotate 3
		tcMod stretch sin 0.7533 0.7466 0.6 0.9639
	}
}

textures/runy9/zzfallscentrelarge_61
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentrelarge_62
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.61 0.9639
	deformvertexes move -46.3216 -60.252 0 square 0 1 0.61 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.61 0.9639
		alphagen wave square 0 1 0.61 0.9639
		tcMod rotate -69
		tcMod stretch sin 0.7533 0.7466 0.61 0.9639
	}
}

textures/runy9/zzfallscentrelarge_62
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentrelarge_63
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.62 0.9639
	deformvertexes move -38.9307 -102.881 0 square 0 1 0.62 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.62 0.9639
		alphagen wave square 0 1 0.62 0.9639
		tcMod rotate 6
		tcMod stretch sin 0.7533 0.7466 0.62 0.9639
	}
}

textures/runy9/zzfallscentrelarge_63
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentrelarge_64
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.63 0.9639
	deformvertexes move 18.1543 -119.63 0 square 0 1 0.63 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.63 0.9639
		alphagen wave square 0 1 0.63 0.9639
		tcMod rotate 24
		tcMod stretch sin 0.7533 0.7466 0.63 0.9639
	}
}

textures/runy9/zzfallscentrelarge_64
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentrelarge_65
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.64 0.9639
	deformvertexes move -104.992 -1.31211 0 square 0 1 0.64 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.64 0.9639
		alphagen wave square 0 1 0.64 0.9639
		tcMod rotate 39
		tcMod stretch sin 0.7533 0.7466 0.64 0.9639
	}
}

textures/runy9/zzfallscentrelarge_65
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentrelarge_66
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.65 0.9639
	deformvertexes move 67.554 -53.2209 0 square 0 1 0.65 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.65 0.9639
		alphagen wave square 0 1 0.65 0.9639
		tcMod rotate -9
		tcMod stretch sin 0.7533 0.7466 0.65 0.9639
	}
}

textures/runy9/zzfallscentrelarge_66
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentrelarge_67
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.66 0.9639
	deformvertexes move 23.9425 -73.183 0 square 0 1 0.66 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.66 0.9639
		alphagen wave square 0 1 0.66 0.9639
		tcMod rotate 67
		tcMod stretch sin 0.7533 0.7466 0.66 0.9639
	}
}

textures/runy9/zzfallscentrelarge_67
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentrelarge_68
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.67 0.9639
	deformvertexes move 68.9472 -84.4232 0 square 0 1 0.67 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.67 0.9639
		alphagen wave square 0 1 0.67 0.9639
		tcMod rotate 61
		tcMod stretch sin 0.7533 0.7466 0.67 0.9639
	}
}

textures/runy9/zzfallscentrelarge_68
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentrelarge_69
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.68 0.9639
	deformvertexes move 63.3446 -61.0857 0 square 0 1 0.68 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.68 0.9639
		alphagen wave square 0 1 0.68 0.9639
		tcMod rotate 80
		tcMod stretch sin 0.7533 0.7466 0.68 0.9639
	}
}

textures/runy9/zzfallscentrelarge_69
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentrelarge_70
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.69 0.9639
	deformvertexes move 77.3795 -70.9748 0 square 0 1 0.69 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.69 0.9639
		alphagen wave square 0 1 0.69 0.9639
		tcMod rotate -46
		tcMod stretch sin 0.7533 0.7466 0.69 0.9639
	}
}

textures/runy9/zzfallscentrelarge_70
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentrelarge_71
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.7 0.9639
	deformvertexes move -83.5266 -8.90577 0 square 0 1 0.7 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.7 0.9639
		alphagen wave square 0 1 0.7 0.9639
		tcMod rotate -51
		tcMod stretch sin 0.7533 0.7466 0.7 0.9639
	}
}

textures/runy9/zzfallscentrelarge_71
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentrelarge_72
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.71 0.9639
	deformvertexes move 37.0935 -66.333 0 square 0 1 0.71 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.71 0.9639
		alphagen wave square 0 1 0.71 0.9639
		tcMod rotate 5
		tcMod stretch sin 0.7533 0.7466 0.71 0.9639
	}
}

textures/runy9/zzfallscentrelarge_72
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentrelarge_73
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.72 0.9639
	deformvertexes move 23.3867 -103.388 0 square 0 1 0.72 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.72 0.9639
		alphagen wave square 0 1 0.72 0.9639
		tcMod rotate -8
		tcMod stretch sin 0.7533 0.7466 0.72 0.9639
	}
}

textures/runy9/zzfallscentrelarge_73
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentrelarge_74
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.73 0.9639
	deformvertexes move 119.892 -5.09205 0 square 0 1 0.73 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.73 0.9639
		alphagen wave square 0 1 0.73 0.9639
		tcMod rotate -62
		tcMod stretch sin 0.7533 0.7466 0.73 0.9639
	}
}

textures/runy9/zzfallscentrelarge_74
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentrelarge_75
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.74 0.9639
	deformvertexes move -96.7497 -6.96397 0 square 0 1 0.74 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.74 0.9639
		alphagen wave square 0 1 0.74 0.9639
		tcMod rotate -82
		tcMod stretch sin 0.7533 0.7466 0.74 0.9639
	}
}

textures/runy9/zzfallscentrelarge_75
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentrelarge_76
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.75 0.9639
	deformvertexes move 104.085 -48.9011 0 square 0 1 0.75 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.75 0.9639
		alphagen wave square 0 1 0.75 0.9639
		tcMod rotate 63
		tcMod stretch sin 0.7533 0.7466 0.75 0.9639
	}
}

textures/runy9/zzfallscentrelarge_76
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentrelarge_77
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.76 0.9639
	deformvertexes move -66.9956 -58.5883 0 square 0 1 0.76 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.76 0.9639
		alphagen wave square 0 1 0.76 0.9639
		tcMod rotate 30
		tcMod stretch sin 0.7533 0.7466 0.76 0.9639
	}
}

textures/runy9/zzfallscentrelarge_77
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentrelarge_78
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.77 0.9639
	deformvertexes move -22.346 -75.7737 0 square 0 1 0.77 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.77 0.9639
		alphagen wave square 0 1 0.77 0.9639
		tcMod rotate 6
		tcMod stretch sin 0.7533 0.7466 0.77 0.9639
	}
}

textures/runy9/zzfallscentrelarge_78
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentrelarge_79
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.78 0.9639
	deformvertexes move -74.9634 -2.34271 0 square 0 1 0.78 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.78 0.9639
		alphagen wave square 0 1 0.78 0.9639
		tcMod rotate -60
		tcMod stretch sin 0.7533 0.7466 0.78 0.9639
	}
}

textures/runy9/zzfallscentrelarge_79
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentrelarge_80
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.79 0.9639
	deformvertexes move 123.744 -7.96961 0 square 0 1 0.79 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.79 0.9639
		alphagen wave square 0 1 0.79 0.9639
		tcMod rotate -66
		tcMod stretch sin 0.7533 0.7466 0.79 0.9639
	}
}

textures/runy9/zzfallscentrelarge_80
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentrelarge_81
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.8 0.9639
	deformvertexes move 81.0987 -28.6183 0 square 0 1 0.8 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.8 0.9639
		alphagen wave square 0 1 0.8 0.9639
		tcMod rotate -57
		tcMod stretch sin 0.7533 0.7466 0.8 0.9639
	}
}

textures/runy9/zzfallscentrelarge_81
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentrelarge_82
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.81 0.9639
	deformvertexes move -87.0133 -70.5173 0 square 0 1 0.81 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.81 0.9639
		alphagen wave square 0 1 0.81 0.9639
		tcMod rotate -30
		tcMod stretch sin 0.7533 0.7466 0.81 0.9639
	}
}

textures/runy9/zzfallscentrelarge_82
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentrelarge_83
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.82 0.9639
	deformvertexes move 66.423 -63.6552 0 square 0 1 0.82 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.82 0.9639
		alphagen wave square 0 1 0.82 0.9639
		tcMod rotate -22
		tcMod stretch sin 0.7533 0.7466 0.82 0.9639
	}
}

textures/runy9/zzfallscentrelarge_83
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentrelarge_84
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.83 0.9639
	deformvertexes move 65.0604 -84.9479 0 square 0 1 0.83 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.83 0.9639
		alphagen wave square 0 1 0.83 0.9639
		tcMod rotate 68
		tcMod stretch sin 0.7533 0.7466 0.83 0.9639
	}
}

textures/runy9/zzfallscentrelarge_84
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentrelarge_85
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.84 0.9639
	deformvertexes move -41.982 -99.5064 0 square 0 1 0.84 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.84 0.9639
		alphagen wave square 0 1 0.84 0.9639
		tcMod rotate 38
		tcMod stretch sin 0.7533 0.7466 0.84 0.9639
	}
}

textures/runy9/zzfallscentrelarge_85
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentrelarge_86
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.85 0.9639
	deformvertexes move -64.7549 -41.6629 0 square 0 1 0.85 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.85 0.9639
		alphagen wave square 0 1 0.85 0.9639
		tcMod rotate -15
		tcMod stretch sin 0.7533 0.7466 0.85 0.9639
	}
}

textures/runy9/zzfallscentrelarge_86
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentrelarge_87
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.86 0.9639
	deformvertexes move 102.286 -40.4669 0 square 0 1 0.86 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.86 0.9639
		alphagen wave square 0 1 0.86 0.9639
		tcMod rotate 10
		tcMod stretch sin 0.7533 0.7466 0.86 0.9639
	}
}

textures/runy9/zzfallscentrelarge_87
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentrelarge_88
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.87 0.9639
	deformvertexes move 74.2167 -37.1601 0 square 0 1 0.87 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.87 0.9639
		alphagen wave square 0 1 0.87 0.9639
		tcMod rotate 17
		tcMod stretch sin 0.7533 0.7466 0.87 0.9639
	}
}

textures/runy9/zzfallscentrelarge_88
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentrelarge_89
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.88 0.9639
	deformvertexes move 59.3801 -56.5509 0 square 0 1 0.88 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.88 0.9639
		alphagen wave square 0 1 0.88 0.9639
		tcMod rotate 82
		tcMod stretch sin 0.7533 0.7466 0.88 0.9639
	}
}

textures/runy9/zzfallscentrelarge_89
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentrelarge_90
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.89 0.9639
	deformvertexes move 89.8139 -5.78439 0 square 0 1 0.89 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.89 0.9639
		alphagen wave square 0 1 0.89 0.9639
		tcMod rotate -36
		tcMod stretch sin 0.7533 0.7466 0.89 0.9639
	}
}

textures/runy9/zzfallscentrelarge_90
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentrelarge_91
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.9 0.9639
	deformvertexes move 119.586 -9.95578 0 square 0 1 0.9 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.9 0.9639
		alphagen wave square 0 1 0.9 0.9639
		tcMod rotate -67
		tcMod stretch sin 0.7533 0.7466 0.9 0.9639
	}
}

textures/runy9/zzfallscentrelarge_91
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentrelarge_92
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.91 0.9639
	deformvertexes move 3.46948 -90.9338 0 square 0 1 0.91 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.91 0.9639
		alphagen wave square 0 1 0.91 0.9639
		tcMod rotate 27
		tcMod stretch sin 0.7533 0.7466 0.91 0.9639
	}
}

textures/runy9/zzfallscentrelarge_92
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentrelarge_93
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.92 0.9639
	deformvertexes move -102.568 -64.1936 0 square 0 1 0.92 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.92 0.9639
		alphagen wave square 0 1 0.92 0.9639
		tcMod rotate -79
		tcMod stretch sin 0.7533 0.7466 0.92 0.9639
	}
}

textures/runy9/zzfallscentrelarge_93
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentrelarge_94
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.93 0.9639
	deformvertexes move 0.871575 -86.9956 0 square 0 1 0.93 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.93 0.9639
		alphagen wave square 0 1 0.93 0.9639
		tcMod rotate 45
		tcMod stretch sin 0.7533 0.7466 0.93 0.9639
	}
}

textures/runy9/zzfallscentrelarge_94
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentrelarge_95
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.94 0.9639
	deformvertexes move 91.1867 -79.5361 0 square 0 1 0.94 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.94 0.9639
		alphagen wave square 0 1 0.94 0.9639
		tcMod rotate 70
		tcMod stretch sin 0.7533 0.7466 0.94 0.9639
	}
}

textures/runy9/zzfallscentrelarge_95
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentrelarge_96
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.95 0.9639
	deformvertexes move -41.6901 -86.475 0 square 0 1 0.95 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.95 0.9639
		alphagen wave square 0 1 0.95 0.9639
		tcMod rotate 23
		tcMod stretch sin 0.7533 0.7466 0.95 0.9639
	}
}

textures/runy9/zzfallscentrelarge_96
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentrelarge_97
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.96 0.9639
	deformvertexes move 46.4893 -86.2714 0 square 0 1 0.96 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.96 0.9639
		alphagen wave square 0 1 0.96 0.9639
		tcMod rotate 25
		tcMod stretch sin 0.7533 0.7466 0.96 0.9639
	}
}

textures/runy9/zzfallscentrelarge_97
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentrelarge_98
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.97 0.9639
	deformvertexes move -101.415 -45.123 0 square 0 1 0.97 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.97 0.9639
		alphagen wave square 0 1 0.97 0.9639
		tcMod rotate 84
		tcMod stretch sin 0.7533 0.7466 0.97 0.9639
	}
}

textures/runy9/zzfallscentrelarge_98
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentrelarge_99
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.98 0.9639
	deformvertexes move 76.5556 -74.7545 0 square 0 1 0.98 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.98 0.9639
		alphagen wave square 0 1 0.98 0.9639
		tcMod rotate -15
		tcMod stretch sin 0.7533 0.7466 0.98 0.9639
	}
}

textures/runy9/zzfallscentrelarge_99
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.99 0.9639
	deformvertexes move -82.894 -13.5863 0 square 0 1 0.99 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.99 0.9639
		alphagen wave square 0 1 0.99 0.9639
		tcMod rotate 70
		tcMod stretch sin 0.7533 0.7466 0.99 0.9639
	}
}

