// Generated by Frozen Sand Particle Studio
// Mon Nov 16 22:11:28 2009


textures/runy9/fallscentre
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentre_1
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0 0.9639
	deformvertexes move -20.9929 -46.479 0 square 0 1 0 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0 0.9639
		alphagen wave square 0 1 0 0.9639
		tcMod rotate -52
		tcMod stretch sin 0.7533 0.7466 0 0.9639
	}
}

textures/runy9/zzfallscentre_1
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentre_2
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.0105263 0.9639
	deformvertexes move 22.6551 -23.9948 0 square 0 1 0.0105263 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.0105263 0.9639
		alphagen wave square 0 1 0.0105263 0.9639
		tcMod rotate -28
		tcMod stretch sin 0.7533 0.7466 0.0105263 0.9639
	}
}

textures/runy9/zzfallscentre_2
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentre_3
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.0210526 0.9639
	deformvertexes move 46.4682 -41.0452 0 square 0 1 0.0210526 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.0210526 0.9639
		alphagen wave square 0 1 0.0210526 0.9639
		tcMod rotate -31
		tcMod stretch sin 0.7533 0.7466 0.0210526 0.9639
	}
}

textures/runy9/zzfallscentre_3
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentre_4
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.0315789 0.9639
	deformvertexes move 11.8293 -41.3409 0 square 0 1 0.0315789 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.0315789 0.9639
		alphagen wave square 0 1 0.0315789 0.9639
		tcMod rotate -105
		tcMod stretch sin 0.7533 0.7466 0.0315789 0.9639
	}
}

textures/runy9/zzfallscentre_4
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentre_5
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.0421053 0.9639
	deformvertexes move 37.9792 -1.25658 0 square 0 1 0.0421053 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.0421053 0.9639
		alphagen wave square 0 1 0.0421053 0.9639
		tcMod rotate -21
		tcMod stretch sin 0.7533 0.7466 0.0421053 0.9639
	}
}

textures/runy9/zzfallscentre_5
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentre_6
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.0526316 0.9639
	deformvertexes move -16.2327 -59.8373 0 square 0 1 0.0526316 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.0526316 0.9639
		alphagen wave square 0 1 0.0526316 0.9639
		tcMod rotate 112
		tcMod stretch sin 0.7533 0.7466 0.0526316 0.9639
	}
}

textures/runy9/zzfallscentre_6
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentre_7
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.0631579 0.9639
	deformvertexes move -5.05779 -33.6217 0 square 0 1 0.0631579 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.0631579 0.9639
		alphagen wave square 0 1 0.0631579 0.9639
		tcMod rotate 16
		tcMod stretch sin 0.7533 0.7466 0.0631579 0.9639
	}
}

textures/runy9/zzfallscentre_7
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentre_8
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.0736842 0.9639
	deformvertexes move -62.9879 -11.3367 0 square 0 1 0.0736842 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.0736842 0.9639
		alphagen wave square 0 1 0.0736842 0.9639
		tcMod rotate -44
		tcMod stretch sin 0.7533 0.7466 0.0736842 0.9639
	}
}

textures/runy9/zzfallscentre_8
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentre_9
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.0842105 0.9639
	deformvertexes move 68.4185 -8.93944 0 square 0 1 0.0842105 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.0842105 0.9639
		alphagen wave square 0 1 0.0842105 0.9639
		tcMod rotate 52
		tcMod stretch sin 0.7533 0.7466 0.0842105 0.9639
	}
}

textures/runy9/zzfallscentre_9
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentre_10
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.0947368 0.9639
	deformvertexes move -39.8728 -26.7238 0 square 0 1 0.0947368 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.0947368 0.9639
		alphagen wave square 0 1 0.0947368 0.9639
		tcMod rotate -89
		tcMod stretch sin 0.7533 0.7466 0.0947368 0.9639
	}
}

textures/runy9/zzfallscentre_10
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentre_11
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.105263 0.9639
	deformvertexes move 61.6694 -37.1603 0 square 0 1 0.105263 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.105263 0.9639
		alphagen wave square 0 1 0.105263 0.9639
		tcMod rotate -22
		tcMod stretch sin 0.7533 0.7466 0.105263 0.9639
	}
}

textures/runy9/zzfallscentre_11
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentre_12
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.115789 0.9639
	deformvertexes move -31.118 -57.0673 0 square 0 1 0.115789 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.115789 0.9639
		alphagen wave square 0 1 0.115789 0.9639
		tcMod rotate 83
		tcMod stretch sin 0.7533 0.7466 0.115789 0.9639
	}
}

textures/runy9/zzfallscentre_12
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentre_13
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.126316 0.9639
	deformvertexes move -45.3696 -37.7174 0 square 0 1 0.126316 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.126316 0.9639
		alphagen wave square 0 1 0.126316 0.9639
		tcMod rotate -52
		tcMod stretch sin 0.7533 0.7466 0.126316 0.9639
	}
}

textures/runy9/zzfallscentre_13
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentre_14
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.136842 0.9639
	deformvertexes move -29.3202 -58.0114 0 square 0 1 0.136842 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.136842 0.9639
		alphagen wave square 0 1 0.136842 0.9639
		tcMod rotate -24
		tcMod stretch sin 0.7533 0.7466 0.136842 0.9639
	}
}

textures/runy9/zzfallscentre_14
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentre_15
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.147368 0.9639
	deformvertexes move -20.1529 -63.8973 0 square 0 1 0.147368 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.147368 0.9639
		alphagen wave square 0 1 0.147368 0.9639
		tcMod rotate 22
		tcMod stretch sin 0.7533 0.7466 0.147368 0.9639
	}
}

textures/runy9/zzfallscentre_15
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentre_16
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.157895 0.9639
	deformvertexes move -36.171 -33.0553 0 square 0 1 0.157895 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.157895 0.9639
		alphagen wave square 0 1 0.157895 0.9639
		tcMod rotate 29
		tcMod stretch sin 0.7533 0.7466 0.157895 0.9639
	}
}

textures/runy9/zzfallscentre_16
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentre_17
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.168421 0.9639
	deformvertexes move 29.4707 -41.623 0 square 0 1 0.168421 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.168421 0.9639
		alphagen wave square 0 1 0.168421 0.9639
		tcMod rotate -109
		tcMod stretch sin 0.7533 0.7466 0.168421 0.9639
	}
}

textures/runy9/zzfallscentre_17
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentre_18
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.178947 0.9639
	deformvertexes move -66.0134 -11.4559 0 square 0 1 0.178947 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.178947 0.9639
		alphagen wave square 0 1 0.178947 0.9639
		tcMod rotate 83
		tcMod stretch sin 0.7533 0.7466 0.178947 0.9639
	}
}

textures/runy9/zzfallscentre_18
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentre_19
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.189474 0.9639
	deformvertexes move -54.8033 -52.6555 0 square 0 1 0.189474 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.189474 0.9639
		alphagen wave square 0 1 0.189474 0.9639
		tcMod rotate 80
		tcMod stretch sin 0.7533 0.7466 0.189474 0.9639
	}
}

textures/runy9/zzfallscentre_19
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentre_20
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.2 0.9639
	deformvertexes move 61.3425 -14.3561 0 square 0 1 0.2 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.2 0.9639
		alphagen wave square 0 1 0.2 0.9639
		tcMod rotate 97
		tcMod stretch sin 0.7533 0.7466 0.2 0.9639
	}
}

textures/runy9/zzfallscentre_20
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentre_21
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.210526 0.9639
	deformvertexes move 57.4358 -23.348 0 square 0 1 0.210526 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.210526 0.9639
		alphagen wave square 0 1 0.210526 0.9639
		tcMod rotate -4
		tcMod stretch sin 0.7533 0.7466 0.210526 0.9639
	}
}

textures/runy9/zzfallscentre_21
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentre_22
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.221053 0.9639
	deformvertexes move -11.5539 -38.295 0 square 0 1 0.221053 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.221053 0.9639
		alphagen wave square 0 1 0.221053 0.9639
		tcMod rotate -112
		tcMod stretch sin 0.7533 0.7466 0.221053 0.9639
	}
}

textures/runy9/zzfallscentre_22
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentre_23
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.231579 0.9639
	deformvertexes move 6.93097 -68.651 0 square 0 1 0.231579 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.231579 0.9639
		alphagen wave square 0 1 0.231579 0.9639
		tcMod rotate -110
		tcMod stretch sin 0.7533 0.7466 0.231579 0.9639
	}
}

textures/runy9/zzfallscentre_23
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentre_24
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.242105 0.9639
	deformvertexes move -15.0556 -28.237 0 square 0 1 0.242105 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.242105 0.9639
		alphagen wave square 0 1 0.242105 0.9639
		tcMod rotate -41
		tcMod stretch sin 0.7533 0.7466 0.242105 0.9639
	}
}

textures/runy9/zzfallscentre_24
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentre_25
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.252632 0.9639
	deformvertexes move -0.651523 -35.9941 0 square 0 1 0.252632 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.252632 0.9639
		alphagen wave square 0 1 0.252632 0.9639
		tcMod rotate -50
		tcMod stretch sin 0.7533 0.7466 0.252632 0.9639
	}
}

textures/runy9/zzfallscentre_25
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentre_26
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.263158 0.9639
	deformvertexes move -70.2585 -19.8176 0 square 0 1 0.263158 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.263158 0.9639
		alphagen wave square 0 1 0.263158 0.9639
		tcMod rotate -105
		tcMod stretch sin 0.7533 0.7466 0.263158 0.9639
	}
}

textures/runy9/zzfallscentre_26
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentre_27
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.273684 0.9639
	deformvertexes move -6.1572 -70.7325 0 square 0 1 0.273684 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.273684 0.9639
		alphagen wave square 0 1 0.273684 0.9639
		tcMod rotate -111
		tcMod stretch sin 0.7533 0.7466 0.273684 0.9639
	}
}

textures/runy9/zzfallscentre_27
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentre_28
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.284211 0.9639
	deformvertexes move -59.2077 -42.7019 0 square 0 1 0.284211 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.284211 0.9639
		alphagen wave square 0 1 0.284211 0.9639
		tcMod rotate -38
		tcMod stretch sin 0.7533 0.7466 0.284211 0.9639
	}
}

textures/runy9/zzfallscentre_28
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentre_29
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.294737 0.9639
	deformvertexes move 15.8794 -27.7821 0 square 0 1 0.294737 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.294737 0.9639
		alphagen wave square 0 1 0.294737 0.9639
		tcMod rotate -89
		tcMod stretch sin 0.7533 0.7466 0.294737 0.9639
	}
}

textures/runy9/zzfallscentre_29
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentre_30
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.305263 0.9639
	deformvertexes move -30.518 -25.8583 0 square 0 1 0.305263 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.305263 0.9639
		alphagen wave square 0 1 0.305263 0.9639
		tcMod rotate -111
		tcMod stretch sin 0.7533 0.7466 0.305263 0.9639
	}
}

textures/runy9/zzfallscentre_30
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentre_31
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.315789 0.9639
	deformvertexes move -29.6115 -26.8916 0 square 0 1 0.315789 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.315789 0.9639
		alphagen wave square 0 1 0.315789 0.9639
		tcMod rotate -9
		tcMod stretch sin 0.7533 0.7466 0.315789 0.9639
	}
}

textures/runy9/zzfallscentre_31
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentre_32
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.326316 0.9639
	deformvertexes move -4.21952 -64.8629 0 square 0 1 0.326316 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.326316 0.9639
		alphagen wave square 0 1 0.326316 0.9639
		tcMod rotate -26
		tcMod stretch sin 0.7533 0.7466 0.326316 0.9639
	}
}

textures/runy9/zzfallscentre_32
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentre_33
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.336842 0.9639
	deformvertexes move 48.5756 -55.8248 0 square 0 1 0.336842 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.336842 0.9639
		alphagen wave square 0 1 0.336842 0.9639
		tcMod rotate -110
		tcMod stretch sin 0.7533 0.7466 0.336842 0.9639
	}
}

textures/runy9/zzfallscentre_33
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentre_34
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.347368 0.9639
	deformvertexes move 31.6887 -29.0659 0 square 0 1 0.347368 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.347368 0.9639
		alphagen wave square 0 1 0.347368 0.9639
		tcMod rotate -38
		tcMod stretch sin 0.7533 0.7466 0.347368 0.9639
	}
}

textures/runy9/zzfallscentre_34
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentre_35
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.357895 0.9639
	deformvertexes move -46.2012 -53.9115 0 square 0 1 0.357895 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.357895 0.9639
		alphagen wave square 0 1 0.357895 0.9639
		tcMod rotate 99
		tcMod stretch sin 0.7533 0.7466 0.357895 0.9639
	}
}

textures/runy9/zzfallscentre_35
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentre_36
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.368421 0.9639
	deformvertexes move -47.349 -31.7345 0 square 0 1 0.368421 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.368421 0.9639
		alphagen wave square 0 1 0.368421 0.9639
		tcMod rotate 31
		tcMod stretch sin 0.7533 0.7466 0.368421 0.9639
	}
}

textures/runy9/zzfallscentre_36
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentre_37
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.378947 0.9639
	deformvertexes move 35.1881 -11.4367 0 square 0 1 0.378947 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.378947 0.9639
		alphagen wave square 0 1 0.378947 0.9639
		tcMod rotate 36
		tcMod stretch sin 0.7533 0.7466 0.378947 0.9639
	}
}

textures/runy9/zzfallscentre_37
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentre_38
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.389474 0.9639
	deformvertexes move 38.7943 -24.7185 0 square 0 1 0.389474 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.389474 0.9639
		alphagen wave square 0 1 0.389474 0.9639
		tcMod rotate 57
		tcMod stretch sin 0.7533 0.7466 0.389474 0.9639
	}
}

textures/runy9/zzfallscentre_38
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentre_39
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.4 0.9639
	deformvertexes move -46.0831 -16.6537 0 square 0 1 0.4 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.4 0.9639
		alphagen wave square 0 1 0.4 0.9639
		tcMod rotate -60
		tcMod stretch sin 0.7533 0.7466 0.4 0.9639
	}
}

textures/runy9/zzfallscentre_39
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentre_40
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.410526 0.9639
	deformvertexes move 64.4272 -27.3703 0 square 0 1 0.410526 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.410526 0.9639
		alphagen wave square 0 1 0.410526 0.9639
		tcMod rotate -40
		tcMod stretch sin 0.7533 0.7466 0.410526 0.9639
	}
}

textures/runy9/zzfallscentre_40
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentre_41
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.421053 0.9639
	deformvertexes move -75.8928 -4.03449 0 square 0 1 0.421053 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.421053 0.9639
		alphagen wave square 0 1 0.421053 0.9639
		tcMod rotate -13
		tcMod stretch sin 0.7533 0.7466 0.421053 0.9639
	}
}

textures/runy9/zzfallscentre_41
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentre_42
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.431579 0.9639
	deformvertexes move 13.2017 -71.7963 0 square 0 1 0.431579 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.431579 0.9639
		alphagen wave square 0 1 0.431579 0.9639
		tcMod rotate -36
		tcMod stretch sin 0.7533 0.7466 0.431579 0.9639
	}
}

textures/runy9/zzfallscentre_42
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentre_43
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.442105 0.9639
	deformvertexes move 45.9699 -1.66475 0 square 0 1 0.442105 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.442105 0.9639
		alphagen wave square 0 1 0.442105 0.9639
		tcMod rotate -89
		tcMod stretch sin 0.7533 0.7466 0.442105 0.9639
	}
}

textures/runy9/zzfallscentre_43
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentre_44
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.452632 0.9639
	deformvertexes move 29.9892 -0.804684 0 square 0 1 0.452632 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.452632 0.9639
		alphagen wave square 0 1 0.452632 0.9639
		tcMod rotate 87
		tcMod stretch sin 0.7533 0.7466 0.452632 0.9639
	}
}

textures/runy9/zzfallscentre_44
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentre_45
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.463158 0.9639
	deformvertexes move -35.5323 -22.3932 0 square 0 1 0.463158 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.463158 0.9639
		alphagen wave square 0 1 0.463158 0.9639
		tcMod rotate -47
		tcMod stretch sin 0.7533 0.7466 0.463158 0.9639
	}
}

textures/runy9/zzfallscentre_45
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentre_46
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.473684 0.9639
	deformvertexes move 23.6922 -33.4616 0 square 0 1 0.473684 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.473684 0.9639
		alphagen wave square 0 1 0.473684 0.9639
		tcMod rotate 71
		tcMod stretch sin 0.7533 0.7466 0.473684 0.9639
	}
}

textures/runy9/zzfallscentre_46
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentre_47
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.484211 0.9639
	deformvertexes move -25.1647 -31.0924 0 square 0 1 0.484211 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.484211 0.9639
		alphagen wave square 0 1 0.484211 0.9639
		tcMod rotate 26
		tcMod stretch sin 0.7533 0.7466 0.484211 0.9639
	}
}

textures/runy9/zzfallscentre_47
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentre_48
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.494737 0.9639
	deformvertexes move 36.3118 -46.5022 0 square 0 1 0.494737 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.494737 0.9639
		alphagen wave square 0 1 0.494737 0.9639
		tcMod rotate 35
		tcMod stretch sin 0.7533 0.7466 0.494737 0.9639
	}
}

textures/runy9/zzfallscentre_48
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentre_49
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.505263 0.9639
	deformvertexes move -30.2405 -6.81998 0 square 0 1 0.505263 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.505263 0.9639
		alphagen wave square 0 1 0.505263 0.9639
		tcMod rotate -95
		tcMod stretch sin 0.7533 0.7466 0.505263 0.9639
	}
}

textures/runy9/zzfallscentre_49
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentre_50
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.515789 0.9639
	deformvertexes move 56.914 -3.13018 0 square 0 1 0.515789 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.515789 0.9639
		alphagen wave square 0 1 0.515789 0.9639
		tcMod rotate 20
		tcMod stretch sin 0.7533 0.7466 0.515789 0.9639
	}
}

textures/runy9/zzfallscentre_50
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentre_51
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.526316 0.9639
	deformvertexes move -32.2386 -13.6261 0 square 0 1 0.526316 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.526316 0.9639
		alphagen wave square 0 1 0.526316 0.9639
		tcMod rotate 52
		tcMod stretch sin 0.7533 0.7466 0.526316 0.9639
	}
}

textures/runy9/zzfallscentre_51
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentre_52
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.536842 0.9639
	deformvertexes move -49.5588 -49.4361 0 square 0 1 0.536842 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.536842 0.9639
		alphagen wave square 0 1 0.536842 0.9639
		tcMod rotate 8
		tcMod stretch sin 0.7533 0.7466 0.536842 0.9639
	}
}

textures/runy9/zzfallscentre_52
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentre_53
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.547368 0.9639
	deformvertexes move 39.589 -21.3941 0 square 0 1 0.547368 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.547368 0.9639
		alphagen wave square 0 1 0.547368 0.9639
		tcMod rotate -31
		tcMod stretch sin 0.7533 0.7466 0.547368 0.9639
	}
}

textures/runy9/zzfallscentre_53
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentre_54
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.557895 0.9639
	deformvertexes move -33.993 -49.4416 0 square 0 1 0.557895 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.557895 0.9639
		alphagen wave square 0 1 0.557895 0.9639
		tcMod rotate -16
		tcMod stretch sin 0.7533 0.7466 0.557895 0.9639
	}
}

textures/runy9/zzfallscentre_54
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentre_55
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.568421 0.9639
	deformvertexes move -11.1414 -51.8157 0 square 0 1 0.568421 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.568421 0.9639
		alphagen wave square 0 1 0.568421 0.9639
		tcMod rotate 20
		tcMod stretch sin 0.7533 0.7466 0.568421 0.9639
	}
}

textures/runy9/zzfallscentre_55
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentre_56
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.578947 0.9639
	deformvertexes move 31.9018 -56.6328 0 square 0 1 0.578947 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.578947 0.9639
		alphagen wave square 0 1 0.578947 0.9639
		tcMod rotate 58
		tcMod stretch sin 0.7533 0.7466 0.578947 0.9639
	}
}

textures/runy9/zzfallscentre_56
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentre_57
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.589474 0.9639
	deformvertexes move -29.9999 -0.0937244 0 square 0 1 0.589474 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.589474 0.9639
		alphagen wave square 0 1 0.589474 0.9639
		tcMod rotate -37
		tcMod stretch sin 0.7533 0.7466 0.589474 0.9639
	}
}

textures/runy9/zzfallscentre_57
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentre_58
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.6 0.9639
	deformvertexes move 23.2968 -34.9465 0 square 0 1 0.6 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.6 0.9639
		alphagen wave square 0 1 0.6 0.9639
		tcMod rotate -19
		tcMod stretch sin 0.7533 0.7466 0.6 0.9639
	}
}

textures/runy9/zzfallscentre_58
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentre_59
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.610526 0.9639
	deformvertexes move 63.1865 -42.2311 0 square 0 1 0.610526 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.610526 0.9639
		alphagen wave square 0 1 0.610526 0.9639
		tcMod rotate -103
		tcMod stretch sin 0.7533 0.7466 0.610526 0.9639
	}
}

textures/runy9/zzfallscentre_59
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentre_60
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.621053 0.9639
	deformvertexes move 8.21634 -63.4704 0 square 0 1 0.621053 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.621053 0.9639
		alphagen wave square 0 1 0.621053 0.9639
		tcMod rotate 99
		tcMod stretch sin 0.7533 0.7466 0.621053 0.9639
	}
}

textures/runy9/zzfallscentre_60
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentre_61
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.631579 0.9639
	deformvertexes move -23.0699 -63.967 0 square 0 1 0.631579 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.631579 0.9639
		alphagen wave square 0 1 0.631579 0.9639
		tcMod rotate -115
		tcMod stretch sin 0.7533 0.7466 0.631579 0.9639
	}
}

textures/runy9/zzfallscentre_61
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentre_62
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.642105 0.9639
	deformvertexes move -60.8499 -22.8538 0 square 0 1 0.642105 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.642105 0.9639
		alphagen wave square 0 1 0.642105 0.9639
		tcMod rotate 97
		tcMod stretch sin 0.7533 0.7466 0.642105 0.9639
	}
}

textures/runy9/zzfallscentre_62
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentre_63
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.652632 0.9639
	deformvertexes move -71.9636 -12.257 0 square 0 1 0.652632 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.652632 0.9639
		alphagen wave square 0 1 0.652632 0.9639
		tcMod rotate -59
		tcMod stretch sin 0.7533 0.7466 0.652632 0.9639
	}
}

textures/runy9/zzfallscentre_63
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentre_64
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.663158 0.9639
	deformvertexes move -30.4603 -67.4401 0 square 0 1 0.663158 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.663158 0.9639
		alphagen wave square 0 1 0.663158 0.9639
		tcMod rotate 97
		tcMod stretch sin 0.7533 0.7466 0.663158 0.9639
	}
}

textures/runy9/zzfallscentre_64
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentre_65
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.673684 0.9639
	deformvertexes move 50.2357 -48.7481 0 square 0 1 0.673684 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.673684 0.9639
		alphagen wave square 0 1 0.673684 0.9639
		tcMod rotate 81
		tcMod stretch sin 0.7533 0.7466 0.673684 0.9639
	}
}

textures/runy9/zzfallscentre_65
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentre_66
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.684211 0.9639
	deformvertexes move -47.8659 -10.4811 0 square 0 1 0.684211 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.684211 0.9639
		alphagen wave square 0 1 0.684211 0.9639
		tcMod rotate 16
		tcMod stretch sin 0.7533 0.7466 0.684211 0.9639
	}
}

textures/runy9/zzfallscentre_66
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentre_67
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.694737 0.9639
	deformvertexes move -76.8927 -13.0965 0 square 0 1 0.694737 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.694737 0.9639
		alphagen wave square 0 1 0.694737 0.9639
		tcMod rotate 48
		tcMod stretch sin 0.7533 0.7466 0.694737 0.9639
	}
}

textures/runy9/zzfallscentre_67
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentre_68
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.705263 0.9639
	deformvertexes move 38.3417 -17.1439 0 square 0 1 0.705263 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.705263 0.9639
		alphagen wave square 0 1 0.705263 0.9639
		tcMod rotate -37
		tcMod stretch sin 0.7533 0.7466 0.705263 0.9639
	}
}

textures/runy9/zzfallscentre_68
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentre_69
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.715789 0.9639
	deformvertexes move -42.5174 -6.42408 0 square 0 1 0.715789 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.715789 0.9639
		alphagen wave square 0 1 0.715789 0.9639
		tcMod rotate -14
		tcMod stretch sin 0.7533 0.7466 0.715789 0.9639
	}
}

textures/runy9/zzfallscentre_69
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentre_70
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.726316 0.9639
	deformvertexes move 30.0861 -63.2046 0 square 0 1 0.726316 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.726316 0.9639
		alphagen wave square 0 1 0.726316 0.9639
		tcMod rotate -8
		tcMod stretch sin 0.7533 0.7466 0.726316 0.9639
	}
}

textures/runy9/zzfallscentre_70
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentre_71
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.736842 0.9639
	deformvertexes move 61.6694 -37.1603 0 square 0 1 0.736842 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.736842 0.9639
		alphagen wave square 0 1 0.736842 0.9639
		tcMod rotate 56
		tcMod stretch sin 0.7533 0.7466 0.736842 0.9639
	}
}

textures/runy9/zzfallscentre_71
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentre_72
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.747368 0.9639
	deformvertexes move -58.3969 -43.8042 0 square 0 1 0.747368 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.747368 0.9639
		alphagen wave square 0 1 0.747368 0.9639
		tcMod rotate -21
		tcMod stretch sin 0.7533 0.7466 0.747368 0.9639
	}
}

textures/runy9/zzfallscentre_72
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentre_73
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.757895 0.9639
	deformvertexes move -4.9579 -31.6136 0 square 0 1 0.757895 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.757895 0.9639
		alphagen wave square 0 1 0.757895 0.9639
		tcMod rotate -112
		tcMod stretch sin 0.7533 0.7466 0.757895 0.9639
	}
}

textures/runy9/zzfallscentre_73
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentre_74
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.768421 0.9639
	deformvertexes move 59.4383 -13.7147 0 square 0 1 0.768421 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.768421 0.9639
		alphagen wave square 0 1 0.768421 0.9639
		tcMod rotate -69
		tcMod stretch sin 0.7533 0.7466 0.768421 0.9639
	}
}

textures/runy9/zzfallscentre_74
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentre_75
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.778947 0.9639
	deformvertexes move -65.2223 -30.4968 0 square 0 1 0.778947 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.778947 0.9639
		alphagen wave square 0 1 0.778947 0.9639
		tcMod rotate -48
		tcMod stretch sin 0.7533 0.7466 0.778947 0.9639
	}
}

textures/runy9/zzfallscentre_75
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentre_76
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.789474 0.9639
	deformvertexes move -36.1203 -37.4076 0 square 0 1 0.789474 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.789474 0.9639
		alphagen wave square 0 1 0.789474 0.9639
		tcMod rotate -33
		tcMod stretch sin 0.7533 0.7466 0.789474 0.9639
	}
}

textures/runy9/zzfallscentre_76
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentre_77
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.8 0.9639
	deformvertexes move -40.6348 -16.8764 0 square 0 1 0.8 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.8 0.9639
		alphagen wave square 0 1 0.8 0.9639
		tcMod rotate 53
		tcMod stretch sin 0.7533 0.7466 0.8 0.9639
	}
}

textures/runy9/zzfallscentre_77
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentre_78
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.810526 0.9639
	deformvertexes move -20.5178 -24.5564 0 square 0 1 0.810526 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.810526 0.9639
		alphagen wave square 0 1 0.810526 0.9639
		tcMod rotate -76
		tcMod stretch sin 0.7533 0.7466 0.810526 0.9639
	}
}

textures/runy9/zzfallscentre_78
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentre_79
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.821053 0.9639
	deformvertexes move 29.9362 -11.306 0 square 0 1 0.821053 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.821053 0.9639
		alphagen wave square 0 1 0.821053 0.9639
		tcMod rotate 42
		tcMod stretch sin 0.7533 0.7466 0.821053 0.9639
	}
}

textures/runy9/zzfallscentre_79
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentre_80
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.831579 0.9639
	deformvertexes move -48.1881 -26.5124 0 square 0 1 0.831579 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.831579 0.9639
		alphagen wave square 0 1 0.831579 0.9639
		tcMod rotate 43
		tcMod stretch sin 0.7533 0.7466 0.831579 0.9639
	}
}

textures/runy9/zzfallscentre_80
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentre_81
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.842105 0.9639
	deformvertexes move -47.9384 -40.8767 0 square 0 1 0.842105 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.842105 0.9639
		alphagen wave square 0 1 0.842105 0.9639
		tcMod rotate -106
		tcMod stretch sin 0.7533 0.7466 0.842105 0.9639
	}
}

textures/runy9/zzfallscentre_81
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentre_82
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.852632 0.9639
	deformvertexes move 39.94 -18.4608 0 square 0 1 0.852632 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.852632 0.9639
		alphagen wave square 0 1 0.852632 0.9639
		tcMod rotate -87
		tcMod stretch sin 0.7533 0.7466 0.852632 0.9639
	}
}

textures/runy9/zzfallscentre_82
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentre_83
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.863158 0.9639
	deformvertexes move 5.09376 -36.6477 0 square 0 1 0.863158 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.863158 0.9639
		alphagen wave square 0 1 0.863158 0.9639
		tcMod rotate -70
		tcMod stretch sin 0.7533 0.7466 0.863158 0.9639
	}
}

textures/runy9/zzfallscentre_83
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentre_84
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.873684 0.9639
	deformvertexes move 11.6226 -30.8855 0 square 0 1 0.873684 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.873684 0.9639
		alphagen wave square 0 1 0.873684 0.9639
		tcMod rotate -70
		tcMod stretch sin 0.7533 0.7466 0.873684 0.9639
	}
}

textures/runy9/zzfallscentre_84
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentre_85
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.884211 0.9639
	deformvertexes move -36.2013 -14.5074 0 square 0 1 0.884211 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.884211 0.9639
		alphagen wave square 0 1 0.884211 0.9639
		tcMod rotate 14
		tcMod stretch sin 0.7533 0.7466 0.884211 0.9639
	}
}

textures/runy9/zzfallscentre_85
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentre_86
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.894737 0.9639
	deformvertexes move 0.814349 -41.9921 0 square 0 1 0.894737 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.894737 0.9639
		alphagen wave square 0 1 0.894737 0.9639
		tcMod rotate -63
		tcMod stretch sin 0.7533 0.7466 0.894737 0.9639
	}
}

textures/runy9/zzfallscentre_86
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentre_87
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.905263 0.9639
	deformvertexes move -19.3105 -66.2428 0 square 0 1 0.905263 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.905263 0.9639
		alphagen wave square 0 1 0.905263 0.9639
		tcMod rotate 67
		tcMod stretch sin 0.7533 0.7466 0.905263 0.9639
	}
}

textures/runy9/zzfallscentre_87
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentre_88
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.915789 0.9639
	deformvertexes move -35.6726 -9.82184 0 square 0 1 0.915789 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.915789 0.9639
		alphagen wave square 0 1 0.915789 0.9639
		tcMod rotate 104
		tcMod stretch sin 0.7533 0.7466 0.915789 0.9639
	}
}

textures/runy9/zzfallscentre_88
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentre_89
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.926316 0.9639
	deformvertexes move 40.5761 -10.8435 0 square 0 1 0.926316 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.926316 0.9639
		alphagen wave square 0 1 0.926316 0.9639
		tcMod rotate 9
		tcMod stretch sin 0.7533 0.7466 0.926316 0.9639
	}
}

textures/runy9/zzfallscentre_89
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentre_90
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.936842 0.9639
	deformvertexes move -26.9741 -13.13 0 square 0 1 0.936842 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.936842 0.9639
		alphagen wave square 0 1 0.936842 0.9639
		tcMod rotate -15
		tcMod stretch sin 0.7533 0.7466 0.936842 0.9639
	}
}

textures/runy9/zzfallscentre_90
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentre_91
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.947368 0.9639
	deformvertexes move 57.5926 -25.536 0 square 0 1 0.947368 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.947368 0.9639
		alphagen wave square 0 1 0.947368 0.9639
		tcMod rotate -17
		tcMod stretch sin 0.7533 0.7466 0.947368 0.9639
	}
}

textures/runy9/zzfallscentre_91
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentre_92
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.957895 0.9639
	deformvertexes move -17.5418 -64.6628 0 square 0 1 0.957895 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.957895 0.9639
		alphagen wave square 0 1 0.957895 0.9639
		tcMod rotate -42
		tcMod stretch sin 0.7533 0.7466 0.957895 0.9639
	}
}

textures/runy9/zzfallscentre_92
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentre_93
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.968421 0.9639
	deformvertexes move -30.5119 -9.64495 0 square 0 1 0.968421 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.968421 0.9639
		alphagen wave square 0 1 0.968421 0.9639
		tcMod rotate -44
		tcMod stretch sin 0.7533 0.7466 0.968421 0.9639
	}
}

textures/runy9/zzfallscentre_93
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentre_94
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.978947 0.9639
	deformvertexes move -36.2013 -14.5074 0 square 0 1 0.978947 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.978947 0.9639
		alphagen wave square 0 1 0.978947 0.9639
		tcMod rotate 64
		tcMod stretch sin 0.7533 0.7466 0.978947 0.9639
	}
}

textures/runy9/zzfallscentre_94
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.989474 0.9639
	deformvertexes move 51.7165 -11.5932 0 square 0 1 0.989474 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.989474 0.9639
		alphagen wave square 0 1 0.989474 0.9639
		tcMod rotate -16
		tcMod stretch sin 0.7533 0.7466 0.989474 0.9639
	}
}

