// Generated by Frozen Sand Particle Studio
// Tue Nov 17 00:59:38 2009


textures/runy9/fallscentrepetit
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentrepetit_1
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0 0.9639
	deformvertexes move 28.6386 -4.56409 0 square 0 1 0 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0 0.9639
		alphagen wave square 0 1 0 0.9639
		tcMod rotate 112
		tcMod stretch sin 0.7533 0.7466 0 0.9639
	}
}

textures/runy9/zzfallscentrepetit_1
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentrepetit_2
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.0166667 0.9639
	deformvertexes move -38.425 -42.1013 0 square 0 1 0.0166667 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.0166667 0.9639
		alphagen wave square 0 1 0.0166667 0.9639
		tcMod rotate -83
		tcMod stretch sin 0.7533 0.7466 0.0166667 0.9639
	}
}

textures/runy9/zzfallscentrepetit_2
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentrepetit_3
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.0333333 0.9639
	deformvertexes move 50.6214 -21.5052 0 square 0 1 0.0333333 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.0333333 0.9639
		alphagen wave square 0 1 0.0333333 0.9639
		tcMod rotate -98
		tcMod stretch sin 0.7533 0.7466 0.0333333 0.9639
	}
}

textures/runy9/zzfallscentrepetit_3
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentrepetit_4
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.05 0.9639
	deformvertexes move -25.3349 -9.33499 0 square 0 1 0.05 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.05 0.9639
		alphagen wave square 0 1 0.05 0.9639
		tcMod rotate -63
		tcMod stretch sin 0.7533 0.7466 0.05 0.9639
	}
}

textures/runy9/zzfallscentrepetit_4
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentrepetit_5
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.0666667 0.9639
	deformvertexes move -9.10669 -32.7577 0 square 0 1 0.0666667 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.0666667 0.9639
		alphagen wave square 0 1 0.0666667 0.9639
		tcMod rotate 17
		tcMod stretch sin 0.7533 0.7466 0.0666667 0.9639
	}
}

textures/runy9/zzfallscentrepetit_5
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentrepetit_6
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.0833333 0.9639
	deformvertexes move -32.3579 -35.4538 0 square 0 1 0.0833333 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.0833333 0.9639
		alphagen wave square 0 1 0.0833333 0.9639
		tcMod rotate 70
		tcMod stretch sin 0.7533 0.7466 0.0833333 0.9639
	}
}

textures/runy9/zzfallscentrepetit_6
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentrepetit_7
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.1 0.9639
	deformvertexes move -18.7401 -3.13165 0 square 0 1 0.1 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.1 0.9639
		alphagen wave square 0 1 0.1 0.9639
		tcMod rotate 19
		tcMod stretch sin 0.7533 0.7466 0.1 0.9639
	}
}

textures/runy9/zzfallscentrepetit_7
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentrepetit_8
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.116667 0.9639
	deformvertexes move -37.535 -33.0322 0 square 0 1 0.116667 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.116667 0.9639
		alphagen wave square 0 1 0.116667 0.9639
		tcMod rotate 83
		tcMod stretch sin 0.7533 0.7466 0.116667 0.9639
	}
}

textures/runy9/zzfallscentrepetit_8
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentrepetit_9
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.133333 0.9639
	deformvertexes move -51.9178 -2.92265 0 square 0 1 0.133333 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.133333 0.9639
		alphagen wave square 0 1 0.133333 0.9639
		tcMod rotate 13
		tcMod stretch sin 0.7533 0.7466 0.133333 0.9639
	}
}

textures/runy9/zzfallscentrepetit_9
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentrepetit_10
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.15 0.9639
	deformvertexes move -17.8809 -25.3234 0 square 0 1 0.15 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.15 0.9639
		alphagen wave square 0 1 0.15 0.9639
		tcMod rotate -27
		tcMod stretch sin 0.7533 0.7466 0.15 0.9639
	}
}

textures/runy9/zzfallscentrepetit_10
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentrepetit_11
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.166667 0.9639
	deformvertexes move -48.6698 -11.4566 0 square 0 1 0.166667 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.166667 0.9639
		alphagen wave square 0 1 0.166667 0.9639
		tcMod rotate 86
		tcMod stretch sin 0.7533 0.7466 0.166667 0.9639
	}
}

textures/runy9/zzfallscentrepetit_11
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentrepetit_12
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.183333 0.9639
	deformvertexes move 38.5692 -19.011 0 square 0 1 0.183333 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.183333 0.9639
		alphagen wave square 0 1 0.183333 0.9639
		tcMod rotate -69
		tcMod stretch sin 0.7533 0.7466 0.183333 0.9639
	}
}

textures/runy9/zzfallscentrepetit_12
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentrepetit_13
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.2 0.9639
	deformvertexes move 51.6327 -18.949 0 square 0 1 0.2 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.2 0.9639
		alphagen wave square 0 1 0.2 0.9639
		tcMod rotate 15
		tcMod stretch sin 0.7533 0.7466 0.2 0.9639
	}
}

textures/runy9/zzfallscentrepetit_13
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentrepetit_14
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.216667 0.9639
	deformvertexes move 43.9886 -34.6554 0 square 0 1 0.216667 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.216667 0.9639
		alphagen wave square 0 1 0.216667 0.9639
		tcMod rotate -30
		tcMod stretch sin 0.7533 0.7466 0.216667 0.9639
	}
}

textures/runy9/zzfallscentrepetit_14
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentrepetit_15
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.233333 0.9639
	deformvertexes move -14.3015 -18.013 0 square 0 1 0.233333 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.233333 0.9639
		alphagen wave square 0 1 0.233333 0.9639
		tcMod rotate 80
		tcMod stretch sin 0.7533 0.7466 0.233333 0.9639
	}
}

textures/runy9/zzfallscentrepetit_15
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentrepetit_16
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.25 0.9639
	deformvertexes move 10.1946 -17.2067 0 square 0 1 0.25 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.25 0.9639
		alphagen wave square 0 1 0.25 0.9639
		tcMod rotate -78
		tcMod stretch sin 0.7533 0.7466 0.25 0.9639
	}
}

textures/runy9/zzfallscentrepetit_16
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentrepetit_17
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.266667 0.9639
	deformvertexes move 2.12972 -47.9527 0 square 0 1 0.266667 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.266667 0.9639
		alphagen wave square 0 1 0.266667 0.9639
		tcMod rotate -50
		tcMod stretch sin 0.7533 0.7466 0.266667 0.9639
	}
}

textures/runy9/zzfallscentrepetit_17
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentrepetit_18
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.283333 0.9639
	deformvertexes move -39.4214 -38.353 0 square 0 1 0.283333 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.283333 0.9639
		alphagen wave square 0 1 0.283333 0.9639
		tcMod rotate 105
		tcMod stretch sin 0.7533 0.7466 0.283333 0.9639
	}
}

textures/runy9/zzfallscentrepetit_18
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentrepetit_19
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.3 0.9639
	deformvertexes move -25.6444 -4.28542 0 square 0 1 0.3 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.3 0.9639
		alphagen wave square 0 1 0.3 0.9639
		tcMod rotate -14
		tcMod stretch sin 0.7533 0.7466 0.3 0.9639
	}
}

textures/runy9/zzfallscentrepetit_19
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentrepetit_20
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.316667 0.9639
	deformvertexes move 4.16779 -34.751 0 square 0 1 0.316667 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.316667 0.9639
		alphagen wave square 0 1 0.316667 0.9639
		tcMod rotate 27
		tcMod stretch sin 0.7533 0.7466 0.316667 0.9639
	}
}

textures/runy9/zzfallscentrepetit_20
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentrepetit_21
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.333333 0.9639
	deformvertexes move 10.1256 -58.1246 0 square 0 1 0.333333 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.333333 0.9639
		alphagen wave square 0 1 0.333333 0.9639
		tcMod rotate -84
		tcMod stretch sin 0.7533 0.7466 0.333333 0.9639
	}
}

textures/runy9/zzfallscentrepetit_21
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentrepetit_22
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.35 0.9639
	deformvertexes move -13.4487 -26.8167 0 square 0 1 0.35 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.35 0.9639
		alphagen wave square 0 1 0.35 0.9639
		tcMod rotate -88
		tcMod stretch sin 0.7533 0.7466 0.35 0.9639
	}
}

textures/runy9/zzfallscentrepetit_22
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentrepetit_23
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.366667 0.9639
	deformvertexes move 7.53273 -16.348 0 square 0 1 0.366667 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.366667 0.9639
		alphagen wave square 0 1 0.366667 0.9639
		tcMod rotate -72
		tcMod stretch sin 0.7533 0.7466 0.366667 0.9639
	}
}

textures/runy9/zzfallscentrepetit_23
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentrepetit_24
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.383333 0.9639
	deformvertexes move -28.3883 -39.9388 0 square 0 1 0.383333 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.383333 0.9639
		alphagen wave square 0 1 0.383333 0.9639
		tcMod rotate -9
		tcMod stretch sin 0.7533 0.7466 0.383333 0.9639
	}
}

textures/runy9/zzfallscentrepetit_24
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentrepetit_25
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.4 0.9639
	deformvertexes move 47.9568 -2.03682 0 square 0 1 0.4 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.4 0.9639
		alphagen wave square 0 1 0.4 0.9639
		tcMod rotate 66
		tcMod stretch sin 0.7533 0.7466 0.4 0.9639
	}
}

textures/runy9/zzfallscentrepetit_25
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentrepetit_26
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.416667 0.9639
	deformvertexes move -45.0818 -25.9159 0 square 0 1 0.416667 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.416667 0.9639
		alphagen wave square 0 1 0.416667 0.9639
		tcMod rotate 92
		tcMod stretch sin 0.7533 0.7466 0.416667 0.9639
	}
}

textures/runy9/zzfallscentrepetit_26
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentrepetit_27
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.433333 0.9639
	deformvertexes move 16.6522 -35.2662 0 square 0 1 0.433333 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.433333 0.9639
		alphagen wave square 0 1 0.433333 0.9639
		tcMod rotate -9
		tcMod stretch sin 0.7533 0.7466 0.433333 0.9639
	}
}

textures/runy9/zzfallscentrepetit_27
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentrepetit_28
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.45 0.9639
	deformvertexes move 14.3694 -29.7073 0 square 0 1 0.45 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.45 0.9639
		alphagen wave square 0 1 0.45 0.9639
		tcMod rotate -84
		tcMod stretch sin 0.7533 0.7466 0.45 0.9639
	}
}

textures/runy9/zzfallscentrepetit_28
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentrepetit_29
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.466667 0.9639
	deformvertexes move 43.6768 -22.2112 0 square 0 1 0.466667 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.466667 0.9639
		alphagen wave square 0 1 0.466667 0.9639
		tcMod rotate -67
		tcMod stretch sin 0.7533 0.7466 0.466667 0.9639
	}
}

textures/runy9/zzfallscentrepetit_29
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentrepetit_30
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.483333 0.9639
	deformvertexes move -36.801 -12.9106 0 square 0 1 0.483333 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.483333 0.9639
		alphagen wave square 0 1 0.483333 0.9639
		tcMod rotate 34
		tcMod stretch sin 0.7533 0.7466 0.483333 0.9639
	}
}

textures/runy9/zzfallscentrepetit_30
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentrepetit_31
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.5 0.9639
	deformvertexes move -12.1596 -25.2219 0 square 0 1 0.5 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.5 0.9639
		alphagen wave square 0 1 0.5 0.9639
		tcMod rotate 19
		tcMod stretch sin 0.7533 0.7466 0.5 0.9639
	}
}

textures/runy9/zzfallscentrepetit_31
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentrepetit_32
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.516667 0.9639
	deformvertexes move -23.9209 -24.1618 0 square 0 1 0.516667 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.516667 0.9639
		alphagen wave square 0 1 0.516667 0.9639
		tcMod rotate 54
		tcMod stretch sin 0.7533 0.7466 0.516667 0.9639
	}
}

textures/runy9/zzfallscentrepetit_32
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentrepetit_33
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.533333 0.9639
	deformvertexes move -56.8996 -3.38146 0 square 0 1 0.533333 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.533333 0.9639
		alphagen wave square 0 1 0.533333 0.9639
		tcMod rotate 34
		tcMod stretch sin 0.7533 0.7466 0.533333 0.9639
	}
}

textures/runy9/zzfallscentrepetit_33
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentrepetit_34
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.55 0.9639
	deformvertexes move -33.2035 -11.0692 0 square 0 1 0.55 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.55 0.9639
		alphagen wave square 0 1 0.55 0.9639
		tcMod rotate -18
		tcMod stretch sin 0.7533 0.7466 0.55 0.9639
	}
}

textures/runy9/zzfallscentrepetit_34
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentrepetit_35
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.566667 0.9639
	deformvertexes move 51.68 -11.7547 0 square 0 1 0.566667 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.566667 0.9639
		alphagen wave square 0 1 0.566667 0.9639
		tcMod rotate 4
		tcMod stretch sin 0.7533 0.7466 0.566667 0.9639
	}
}

textures/runy9/zzfallscentrepetit_35
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentrepetit_36
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.583333 0.9639
	deformvertexes move 24.9126 -31.2948 0 square 0 1 0.583333 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.583333 0.9639
		alphagen wave square 0 1 0.583333 0.9639
		tcMod rotate 87
		tcMod stretch sin 0.7533 0.7466 0.583333 0.9639
	}
}

textures/runy9/zzfallscentrepetit_36
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentrepetit_37
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.6 0.9639
	deformvertexes move -47.8984 -10.3315 0 square 0 1 0.6 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.6 0.9639
		alphagen wave square 0 1 0.6 0.9639
		tcMod rotate 78
		tcMod stretch sin 0.7533 0.7466 0.6 0.9639
	}
}

textures/runy9/zzfallscentrepetit_37
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentrepetit_38
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.616667 0.9639
	deformvertexes move -35.5168 -18.3999 0 square 0 1 0.616667 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.616667 0.9639
		alphagen wave square 0 1 0.616667 0.9639
		tcMod rotate 52
		tcMod stretch sin 0.7533 0.7466 0.616667 0.9639
	}
}

textures/runy9/zzfallscentrepetit_38
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentrepetit_39
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.633333 0.9639
	deformvertexes move -9.62525 -30.5181 0 square 0 1 0.633333 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.633333 0.9639
		alphagen wave square 0 1 0.633333 0.9639
		tcMod rotate 3
		tcMod stretch sin 0.7533 0.7466 0.633333 0.9639
	}
}

textures/runy9/zzfallscentrepetit_39
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentrepetit_40
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.65 0.9639
	deformvertexes move 33.632 -42.2479 0 square 0 1 0.65 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.65 0.9639
		alphagen wave square 0 1 0.65 0.9639
		tcMod rotate -74
		tcMod stretch sin 0.7533 0.7466 0.65 0.9639
	}
}

textures/runy9/zzfallscentrepetit_40
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentrepetit_41
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.666667 0.9639
	deformvertexes move 35.1664 -53.4727 0 square 0 1 0.666667 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.666667 0.9639
		alphagen wave square 0 1 0.666667 0.9639
		tcMod rotate -53
		tcMod stretch sin 0.7533 0.7466 0.666667 0.9639
	}
}

textures/runy9/zzfallscentrepetit_41
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentrepetit_42
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.683333 0.9639
	deformvertexes move 14.243 -11.0062 0 square 0 1 0.683333 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.683333 0.9639
		alphagen wave square 0 1 0.683333 0.9639
		tcMod rotate -58
		tcMod stretch sin 0.7533 0.7466 0.683333 0.9639
	}
}

textures/runy9/zzfallscentrepetit_42
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentrepetit_43
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.7 0.9639
	deformvertexes move 23.8434 -2.73727 0 square 0 1 0.7 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.7 0.9639
		alphagen wave square 0 1 0.7 0.9639
		tcMod rotate 49
		tcMod stretch sin 0.7533 0.7466 0.7 0.9639
	}
}

textures/runy9/zzfallscentrepetit_43
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentrepetit_44
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.716667 0.9639
	deformvertexes move 29.8719 -2.76903 0 square 0 1 0.716667 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.716667 0.9639
		alphagen wave square 0 1 0.716667 0.9639
		tcMod rotate -103
		tcMod stretch sin 0.7533 0.7466 0.716667 0.9639
	}
}

textures/runy9/zzfallscentrepetit_44
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentrepetit_45
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.733333 0.9639
	deformvertexes move -46.5614 -27.3502 0 square 0 1 0.733333 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.733333 0.9639
		alphagen wave square 0 1 0.733333 0.9639
		tcMod rotate 101
		tcMod stretch sin 0.7533 0.7466 0.733333 0.9639
	}
}

textures/runy9/zzfallscentrepetit_45
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentrepetit_46
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.75 0.9639
	deformvertexes move -7.12324 -38.344 0 square 0 1 0.75 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.75 0.9639
		alphagen wave square 0 1 0.75 0.9639
		tcMod rotate 103
		tcMod stretch sin 0.7533 0.7466 0.75 0.9639
	}
}

textures/runy9/zzfallscentrepetit_46
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentrepetit_47
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.766667 0.9639
	deformvertexes move 7.45166 -18.56 0 square 0 1 0.766667 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.766667 0.9639
		alphagen wave square 0 1 0.766667 0.9639
		tcMod rotate -18
		tcMod stretch sin 0.7533 0.7466 0.766667 0.9639
	}
}

textures/runy9/zzfallscentrepetit_47
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentrepetit_48
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.783333 0.9639
	deformvertexes move 41.3234 -20.2084 0 square 0 1 0.783333 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.783333 0.9639
		alphagen wave square 0 1 0.783333 0.9639
		tcMod rotate -23
		tcMod stretch sin 0.7533 0.7466 0.783333 0.9639
	}
}

textures/runy9/zzfallscentrepetit_48
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentrepetit_49
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.8 0.9639
	deformvertexes move -17.7546 -17.6004 0 square 0 1 0.8 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.8 0.9639
		alphagen wave square 0 1 0.8 0.9639
		tcMod rotate -101
		tcMod stretch sin 0.7533 0.7466 0.8 0.9639
	}
}

textures/runy9/zzfallscentrepetit_49
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentrepetit_50
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.816667 0.9639
	deformvertexes move -0.814404 -44.9926 0 square 0 1 0.816667 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.816667 0.9639
		alphagen wave square 0 1 0.816667 0.9639
		tcMod rotate 12
		tcMod stretch sin 0.7533 0.7466 0.816667 0.9639
	}
}

textures/runy9/zzfallscentrepetit_50
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentrepetit_51
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.833333 0.9639
	deformvertexes move 10.302 -17.1426 0 square 0 1 0.833333 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.833333 0.9639
		alphagen wave square 0 1 0.833333 0.9639
		tcMod rotate -78
		tcMod stretch sin 0.7533 0.7466 0.833333 0.9639
	}
}

textures/runy9/zzfallscentrepetit_51
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentrepetit_52
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.85 0.9639
	deformvertexes move 37.5264 -5.98053 0 square 0 1 0.85 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.85 0.9639
		alphagen wave square 0 1 0.85 0.9639
		tcMod rotate 87
		tcMod stretch sin 0.7533 0.7466 0.85 0.9639
	}
}

textures/runy9/zzfallscentrepetit_52
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentrepetit_53
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.866667 0.9639
	deformvertexes move -23.2702 -40.835 0 square 0 1 0.866667 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.866667 0.9639
		alphagen wave square 0 1 0.866667 0.9639
		tcMod rotate 13
		tcMod stretch sin 0.7533 0.7466 0.866667 0.9639
	}
}

textures/runy9/zzfallscentrepetit_53
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentrepetit_54
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.883333 0.9639
	deformvertexes move 1.20885 -15.9543 0 square 0 1 0.883333 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.883333 0.9639
		alphagen wave square 0 1 0.883333 0.9639
		tcMod rotate -83
		tcMod stretch sin 0.7533 0.7466 0.883333 0.9639
	}
}

textures/runy9/zzfallscentrepetit_54
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentrepetit_55
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.9 0.9639
	deformvertexes move -22.34 -11.2217 0 square 0 1 0.9 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.9 0.9639
		alphagen wave square 0 1 0.9 0.9639
		tcMod rotate 73
		tcMod stretch sin 0.7533 0.7466 0.9 0.9639
	}
}

textures/runy9/zzfallscentrepetit_55
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentrepetit_56
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.916667 0.9639
	deformvertexes move 11.9735 -60.8328 0 square 0 1 0.916667 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.916667 0.9639
		alphagen wave square 0 1 0.916667 0.9639
		tcMod rotate -104
		tcMod stretch sin 0.7533 0.7466 0.916667 0.9639
	}
}

textures/runy9/zzfallscentrepetit_56
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentrepetit_57
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.933333 0.9639
	deformvertexes move 11.9748 -31.8214 0 square 0 1 0.933333 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.933333 0.9639
		alphagen wave square 0 1 0.933333 0.9639
		tcMod rotate -113
		tcMod stretch sin 0.7533 0.7466 0.933333 0.9639
	}
}

textures/runy9/zzfallscentrepetit_57
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentrepetit_58
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.95 0.9639
	deformvertexes move 23.0168 -37.4997 0 square 0 1 0.95 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.95 0.9639
		alphagen wave square 0 1 0.95 0.9639
		tcMod rotate -45
		tcMod stretch sin 0.7533 0.7466 0.95 0.9639
	}
}

textures/runy9/zzfallscentrepetit_58
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallscentrepetit_59
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.966667 0.9639
	deformvertexes move 61.9168 -3.21132 0 square 0 1 0.966667 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.966667 0.9639
		alphagen wave square 0 1 0.966667 0.9639
		tcMod rotate -112
		tcMod stretch sin 0.7533 0.7466 0.966667 0.9639
	}
}

textures/runy9/zzfallscentrepetit_59
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.983333 0.9639
	deformvertexes move -30.77 -16.6796 0 square 0 1 0.983333 0.9639
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.983333 0.9639
		alphagen wave square 0 1 0.983333 0.9639
		tcMod rotate -66
		tcMod stretch sin 0.7533 0.7466 0.983333 0.9639
	}
}

