// Generated by Frozen Sand Particle Studio
// Wed Nov 18 21:50:45 2009


textures/runy9/fallcote
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallcote_1
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 330 sin 0 1 0 0.244
	deformvertexes move 10.4424 -49.9195 0 sawtooth 0 1 0 0.244
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0 0.244
		alphagen wave square 0 1 0 0.244
		tcMod rotate -264
		tcMod stretch sin 0.7 0.7466 0.7066 0.244
	}
}

textures/runy9/zzfallcote_1
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallcote_2
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 330 sin 0 1 0.0111111 0.244
	deformvertexes move 37.9444 -34.0767 0 sawtooth 0 1 0.0111111 0.244
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.0111111 0.244
		alphagen wave square 0 1 0.0111111 0.244
		tcMod rotate -125
		tcMod stretch sin 0.7 0.7466 0.717711 0.244
	}
}

textures/runy9/zzfallcote_2
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallcote_3
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 330 sin 0 1 0.0222222 0.244
	deformvertexes move 8.49116 50.2882 0 sawtooth 0 1 0.0222222 0.244
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.0222222 0.244
		alphagen wave square 0 1 0.0222222 0.244
		tcMod rotate 164
		tcMod stretch sin 0.7 0.7466 0.728822 0.244
	}
}

textures/runy9/zzfallcote_3
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallcote_4
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 330 sin 0 1 0.0333333 0.244
	deformvertexes move -7.7363 50.4098 0 sawtooth 0 1 0.0333333 0.244
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.0333333 0.244
		alphagen wave square 0 1 0.0333333 0.244
		tcMod rotate -143
		tcMod stretch sin 0.7 0.7466 0.739933 0.244
	}
}

textures/runy9/zzfallcote_4
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallcote_5
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 330 sin 0 1 0.0444444 0.244
	deformvertexes move -5.2008 50.7341 0 sawtooth 0 1 0.0444444 0.244
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.0444444 0.244
		alphagen wave square 0 1 0.0444444 0.244
		tcMod rotate -22
		tcMod stretch sin 0.7 0.7466 0.751044 0.244
	}
}

textures/runy9/zzfallcote_5
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallcote_6
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 330 sin 0 1 0.0555556 0.244
	deformvertexes move -40.8591 30.521 0 sawtooth 0 1 0.0555556 0.244
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.0555556 0.244
		alphagen wave square 0 1 0.0555556 0.244
		tcMod rotate 16
		tcMod stretch sin 0.7 0.7466 0.762156 0.244
	}
}

textures/runy9/zzfallcote_6
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallcote_7
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 330 sin 0 1 0.0666667 0.244
	deformvertexes move -50.69 -5.61503 0 sawtooth 0 1 0.0666667 0.244
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.0666667 0.244
		alphagen wave square 0 1 0.0666667 0.244
		tcMod rotate 352
		tcMod stretch sin 0.7 0.7466 0.773267 0.244
	}
}

textures/runy9/zzfallcote_7
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallcote_8
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 330 sin 0 1 0.0777778 0.244
	deformvertexes move -48.9511 14.3106 0 sawtooth 0 1 0.0777778 0.244
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.0777778 0.244
		alphagen wave square 0 1 0.0777778 0.244
		tcMod rotate 370
		tcMod stretch sin 0.7 0.7466 0.784378 0.244
	}
}

textures/runy9/zzfallcote_8
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallcote_9
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 330 sin 0 1 0.0888889 0.244
	deformvertexes move -37.3361 -34.7422 0 sawtooth 0 1 0.0888889 0.244
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.0888889 0.244
		alphagen wave square 0 1 0.0888889 0.244
		tcMod rotate -83
		tcMod stretch sin 0.7 0.7466 0.795489 0.244
	}
}

textures/runy9/zzfallcote_9
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallcote_10
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 330 sin 0 1 0.1 0.244
	deformvertexes move -50.8652 -3.70586 0 sawtooth 0 1 0.1 0.244
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.1 0.244
		alphagen wave square 0 1 0.1 0.244
		tcMod rotate 227
		tcMod stretch sin 0.7 0.7466 0.8066 0.244
	}
}

textures/runy9/zzfallcote_10
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallcote_11
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 330 sin 0 1 0.111111 0.244
	deformvertexes move 32.4111 -39.3766 0 sawtooth 0 1 0.111111 0.244
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.111111 0.244
		alphagen wave square 0 1 0.111111 0.244
		tcMod rotate 320
		tcMod stretch sin 0.7 0.7466 0.817711 0.244
	}
}

textures/runy9/zzfallcote_11
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallcote_12
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 330 sin 0 1 0.122222 0.244
	deformvertexes move 30.9083 -40.567 0 sawtooth 0 1 0.122222 0.244
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.122222 0.244
		alphagen wave square 0 1 0.122222 0.244
		tcMod rotate 234
		tcMod stretch sin 0.7 0.7466 0.828822 0.244
	}
}

textures/runy9/zzfallcote_12
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallcote_13
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 330 sin 0 1 0.133333 0.244
	deformvertexes move 16.2973 -48.326 0 sawtooth 0 1 0.133333 0.244
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.133333 0.244
		alphagen wave square 0 1 0.133333 0.244
		tcMod rotate -242
		tcMod stretch sin 0.7 0.7466 0.839933 0.244
	}
}

textures/runy9/zzfallcote_13
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallcote_14
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 330 sin 0 1 0.144444 0.244
	deformvertexes move 42.0873 -28.8038 0 sawtooth 0 1 0.144444 0.244
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.144444 0.244
		alphagen wave square 0 1 0.144444 0.244
		tcMod rotate 110
		tcMod stretch sin 0.7 0.7466 0.851044 0.244
	}
}

textures/runy9/zzfallcote_14
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallcote_15
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 330 sin 0 1 0.155556 0.244
	deformvertexes move -40.0815 31.5353 0 sawtooth 0 1 0.155556 0.244
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.155556 0.244
		alphagen wave square 0 1 0.155556 0.244
		tcMod rotate -143
		tcMod stretch sin 0.7 0.7466 0.862156 0.244
	}
}

textures/runy9/zzfallcote_15
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallcote_16
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 330 sin 0 1 0.166667 0.244
	deformvertexes move 15.9291 48.4486 0 sawtooth 0 1 0.166667 0.244
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.166667 0.244
		alphagen wave square 0 1 0.166667 0.244
		tcMod rotate 235
		tcMod stretch sin 0.7 0.7466 0.873267 0.244
	}
}

textures/runy9/zzfallcote_16
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallcote_17
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 330 sin 0 1 0.177778 0.244
	deformvertexes move 35.4583 36.6566 0 sawtooth 0 1 0.177778 0.244
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.177778 0.244
		alphagen wave square 0 1 0.177778 0.244
		tcMod rotate 366
		tcMod stretch sin 0.7 0.7466 0.884378 0.244
	}
}

textures/runy9/zzfallcote_17
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallcote_18
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 330 sin 0 1 0.188889 0.244
	deformvertexes move 44.0977 25.6202 0 sawtooth 0 1 0.188889 0.244
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.188889 0.244
		alphagen wave square 0 1 0.188889 0.244
		tcMod rotate 135
		tcMod stretch sin 0.7 0.7466 0.895489 0.244
	}
}

textures/runy9/zzfallcote_18
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallcote_19
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 330 sin 0 1 0.2 0.244
	deformvertexes move 0.861595 50.9927 0 sawtooth 0 1 0.2 0.244
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.2 0.244
		alphagen wave square 0 1 0.2 0.244
		tcMod rotate 182
		tcMod stretch sin 0.7 0.7466 0.9066 0.244
	}
}

textures/runy9/zzfallcote_19
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallcote_20
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 330 sin 0 1 0.211111 0.244
	deformvertexes move 47.5546 18.4271 0 sawtooth 0 1 0.211111 0.244
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.211111 0.244
		alphagen wave square 0 1 0.211111 0.244
		tcMod rotate -18
		tcMod stretch sin 0.7 0.7466 0.917711 0.244
	}
}

textures/runy9/zzfallcote_20
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallcote_21
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 330 sin 0 1 0.222222 0.244
	deformvertexes move -50.9981 0.445053 0 sawtooth 0 1 0.222222 0.244
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.222222 0.244
		alphagen wave square 0 1 0.222222 0.244
		tcMod rotate 225
		tcMod stretch sin 0.7 0.7466 0.928822 0.244
	}
}

textures/runy9/zzfallcote_21
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallcote_22
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 330 sin 0 1 0.233333 0.244
	deformvertexes move 22.4353 45.8002 0 sawtooth 0 1 0.233333 0.244
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.233333 0.244
		alphagen wave square 0 1 0.233333 0.244
		tcMod rotate 261
		tcMod stretch sin 0.7 0.7466 0.939933 0.244
	}
}

textures/runy9/zzfallcote_22
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallcote_23
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 330 sin 0 1 0.244444 0.244
	deformvertexes move -47.2473 -19.2015 0 sawtooth 0 1 0.244444 0.244
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.244444 0.244
		alphagen wave square 0 1 0.244444 0.244
		tcMod rotate 294
		tcMod stretch sin 0.7 0.7466 0.951044 0.244
	}
}

textures/runy9/zzfallcote_23
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallcote_24
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 330 sin 0 1 0.255556 0.244
	deformvertexes move 49.9137 10.4702 0 sawtooth 0 1 0.255556 0.244
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.255556 0.244
		alphagen wave square 0 1 0.255556 0.244
		tcMod rotate 318
		tcMod stretch sin 0.7 0.7466 0.962156 0.244
	}
}

textures/runy9/zzfallcote_24
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallcote_25
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 330 sin 0 1 0.266667 0.244
	deformvertexes move -50.6156 -6.24981 0 sawtooth 0 1 0.266667 0.244
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.266667 0.244
		alphagen wave square 0 1 0.266667 0.244
		tcMod rotate 142
		tcMod stretch sin 0.7 0.7466 0.973267 0.244
	}
}

textures/runy9/zzfallcote_25
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallcote_26
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 330 sin 0 1 0.277778 0.244
	deformvertexes move 25.8714 -43.9508 0 sawtooth 0 1 0.277778 0.244
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.277778 0.244
		alphagen wave square 0 1 0.277778 0.244
		tcMod rotate 408
		tcMod stretch sin 0.7 0.7466 0.984378 0.244
	}
}

textures/runy9/zzfallcote_26
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallcote_27
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 330 sin 0 1 0.288889 0.244
	deformvertexes move -31.7636 39.9008 0 sawtooth 0 1 0.288889 0.244
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.288889 0.244
		alphagen wave square 0 1 0.288889 0.244
		tcMod rotate -149
		tcMod stretch sin 0.7 0.7466 0.995489 0.244
	}
}

textures/runy9/zzfallcote_27
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallcote_28
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 330 sin 0 1 0.3 0.244
	deformvertexes move 49.6356 11.7178 0 sawtooth 0 1 0.3 0.244
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.3 0.244
		alphagen wave square 0 1 0.3 0.244
		tcMod rotate -214
		tcMod stretch sin 0.7 0.7466 1.0066 0.244
	}
}

textures/runy9/zzfallcote_28
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallcote_29
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 330 sin 0 1 0.311111 0.244
	deformvertexes move 47.7818 17.8297 0 sawtooth 0 1 0.311111 0.244
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.311111 0.244
		alphagen wave square 0 1 0.311111 0.244
		tcMod rotate -236
		tcMod stretch sin 0.7 0.7466 1.01771 0.244
	}
}

textures/runy9/zzfallcote_29
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallcote_30
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 330 sin 0 1 0.322222 0.244
	deformvertexes move -12.433 49.4613 0 sawtooth 0 1 0.322222 0.244
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.322222 0.244
		alphagen wave square 0 1 0.322222 0.244
		tcMod rotate -288
		tcMod stretch sin 0.7 0.7466 1.02882 0.244
	}
}

textures/runy9/zzfallcote_30
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallcote_31
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 330 sin 0 1 0.333333 0.244
	deformvertexes move -3.22187 -50.8981 0 sawtooth 0 1 0.333333 0.244
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.333333 0.244
		alphagen wave square 0 1 0.333333 0.244
		tcMod rotate 131
		tcMod stretch sin 0.7 0.7466 1.03993 0.244
	}
}

textures/runy9/zzfallcote_31
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallcote_32
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 330 sin 0 1 0.344444 0.244
	deformvertexes move -50.065 -9.72078 0 sawtooth 0 1 0.344444 0.244
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.344444 0.244
		alphagen wave square 0 1 0.344444 0.244
		tcMod rotate -187
		tcMod stretch sin 0.7 0.7466 1.05104 0.244
	}
}

textures/runy9/zzfallcote_32
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallcote_33
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 330 sin 0 1 0.355556 0.244
	deformvertexes move -18.1554 -47.659 0 sawtooth 0 1 0.355556 0.244
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.355556 0.244
		alphagen wave square 0 1 0.355556 0.244
		tcMod rotate -31
		tcMod stretch sin 0.7 0.7466 1.06216 0.244
	}
}

textures/runy9/zzfallcote_33
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallcote_34
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 330 sin 0 1 0.366667 0.244
	deformvertexes move 48.4182 16.0212 0 sawtooth 0 1 0.366667 0.244
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.366667 0.244
		alphagen wave square 0 1 0.366667 0.244
		tcMod rotate 179
		tcMod stretch sin 0.7 0.7466 1.07327 0.244
	}
}

textures/runy9/zzfallcote_34
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallcote_35
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 330 sin 0 1 0.377778 0.244
	deformvertexes move -47.0295 19.7288 0 sawtooth 0 1 0.377778 0.244
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.377778 0.244
		alphagen wave square 0 1 0.377778 0.244
		tcMod rotate 1
		tcMod stretch sin 0.7 0.7466 1.08438 0.244
	}
}

textures/runy9/zzfallcote_35
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallcote_36
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 330 sin 0 1 0.388889 0.244
	deformvertexes move -19.048 -47.3093 0 sawtooth 0 1 0.388889 0.244
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.388889 0.244
		alphagen wave square 0 1 0.388889 0.244
		tcMod rotate 24
		tcMod stretch sin 0.7 0.7466 1.09549 0.244
	}
}

textures/runy9/zzfallcote_36
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallcote_37
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 330 sin 0 1 0.4 0.244
	deformvertexes move -50.9885 1.08408 0 sawtooth 0 1 0.4 0.244
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.4 0.244
		alphagen wave square 0 1 0.4 0.244
		tcMod rotate 427
		tcMod stretch sin 0.7 0.7466 1.1066 0.244
	}
}

textures/runy9/zzfallcote_37
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallcote_38
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 330 sin 0 1 0.411111 0.244
	deformvertexes move 8.55872 -50.2767 0 sawtooth 0 1 0.411111 0.244
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.411111 0.244
		alphagen wave square 0 1 0.411111 0.244
		tcMod rotate 409
		tcMod stretch sin 0.7 0.7466 1.11771 0.244
	}
}

textures/runy9/zzfallcote_38
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallcote_39
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 330 sin 0 1 0.422222 0.244
	deformvertexes move 50.2719 8.58682 0 sawtooth 0 1 0.422222 0.244
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.422222 0.244
		alphagen wave square 0 1 0.422222 0.244
		tcMod rotate 378
		tcMod stretch sin 0.7 0.7466 1.12882 0.244
	}
}

textures/runy9/zzfallcote_39
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallcote_40
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 330 sin 0 1 0.433333 0.244
	deformvertexes move -2.90289 -50.9173 0 sawtooth 0 1 0.433333 0.244
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.433333 0.244
		alphagen wave square 0 1 0.433333 0.244
		tcMod rotate 124
		tcMod stretch sin 0.7 0.7466 1.13993 0.244
	}
}

textures/runy9/zzfallcote_40
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallcote_41
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 330 sin 0 1 0.444444 0.244
	deformvertexes move -45.9819 22.0605 0 sawtooth 0 1 0.444444 0.244
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.444444 0.244
		alphagen wave square 0 1 0.444444 0.244
		tcMod rotate 89
		tcMod stretch sin 0.7 0.7466 1.15104 0.244
	}
}

textures/runy9/zzfallcote_41
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallcote_42
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 330 sin 0 1 0.455556 0.244
	deformvertexes move -43.207 27.0953 0 sawtooth 0 1 0.455556 0.244
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.455556 0.244
		alphagen wave square 0 1 0.455556 0.244
		tcMod rotate 241
		tcMod stretch sin 0.7 0.7466 1.16216 0.244
	}
}

textures/runy9/zzfallcote_42
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallcote_43
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 330 sin 0 1 0.466667 0.244
	deformvertexes move -0.348026 -50.9988 0 sawtooth 0 1 0.466667 0.244
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.466667 0.244
		alphagen wave square 0 1 0.466667 0.244
		tcMod rotate -246
		tcMod stretch sin 0.7 0.7466 1.17327 0.244
	}
}

textures/runy9/zzfallcote_43
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallcote_44
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 330 sin 0 1 0.477778 0.244
	deformvertexes move -8.6149 -50.2671 0 sawtooth 0 1 0.477778 0.244
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.477778 0.244
		alphagen wave square 0 1 0.477778 0.244
		tcMod rotate 114
		tcMod stretch sin 0.7 0.7466 1.18438 0.244
	}
}

textures/runy9/zzfallcote_44
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallcote_45
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 330 sin 0 1 0.488889 0.244
	deformvertexes move 4.43961 -50.8064 0 sawtooth 0 1 0.488889 0.244
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.488889 0.244
		alphagen wave square 0 1 0.488889 0.244
		tcMod rotate 40
		tcMod stretch sin 0.7 0.7466 1.19549 0.244
	}
}

textures/runy9/zzfallcote_45
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallcote_46
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 330 sin 0 1 0.5 0.244
	deformvertexes move -39.4382 -32.3362 0 sawtooth 0 1 0.5 0.244
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.5 0.244
		alphagen wave square 0 1 0.5 0.244
		tcMod rotate 172
		tcMod stretch sin 0.7 0.7466 1.2066 0.244
	}
}

textures/runy9/zzfallcote_46
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallcote_47
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 330 sin 0 1 0.511111 0.244
	deformvertexes move -47.4842 -18.6079 0 sawtooth 0 1 0.511111 0.244
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.511111 0.244
		alphagen wave square 0 1 0.511111 0.244
		tcMod rotate -1
		tcMod stretch sin 0.7 0.7466 1.21771 0.244
	}
}

textures/runy9/zzfallcote_47
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallcote_48
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 330 sin 0 1 0.522222 0.244
	deformvertexes move -39.8831 31.7859 0 sawtooth 0 1 0.522222 0.244
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.522222 0.244
		alphagen wave square 0 1 0.522222 0.244
		tcMod rotate -67
		tcMod stretch sin 0.7 0.7466 1.22882 0.244
	}
}

textures/runy9/zzfallcote_48
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallcote_49
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 330 sin 0 1 0.533333 0.244
	deformvertexes move 5.64334 50.6868 0 sawtooth 0 1 0.533333 0.244
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.533333 0.244
		alphagen wave square 0 1 0.533333 0.244
		tcMod rotate -39
		tcMod stretch sin 0.7 0.7466 1.23993 0.244
	}
}

textures/runy9/zzfallcote_49
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallcote_50
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 330 sin 0 1 0.544444 0.244
	deformvertexes move -49.0398 14.0036 0 sawtooth 0 1 0.544444 0.244
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.544444 0.244
		alphagen wave square 0 1 0.544444 0.244
		tcMod rotate 143
		tcMod stretch sin 0.7 0.7466 1.25104 0.244
	}
}

textures/runy9/zzfallcote_50
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallcote_51
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 330 sin 0 1 0.555556 0.244
	deformvertexes move 40.3551 31.1844 0 sawtooth 0 1 0.555556 0.244
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.555556 0.244
		alphagen wave square 0 1 0.555556 0.244
		tcMod rotate 363
		tcMod stretch sin 0.7 0.7466 1.26216 0.244
	}
}

textures/runy9/zzfallcote_51
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallcote_52
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 330 sin 0 1 0.566667 0.244
	deformvertexes move -41.2384 30.0066 0 sawtooth 0 1 0.566667 0.244
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.566667 0.244
		alphagen wave square 0 1 0.566667 0.244
		tcMod rotate -28
		tcMod stretch sin 0.7 0.7466 1.27327 0.244
	}
}

textures/runy9/zzfallcote_52
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallcote_53
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 330 sin 0 1 0.577778 0.244
	deformvertexes move -40.2783 31.2836 0 sawtooth 0 1 0.577778 0.244
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.577778 0.244
		alphagen wave square 0 1 0.577778 0.244
		tcMod rotate 160
		tcMod stretch sin 0.7 0.7466 1.28438 0.244
	}
}

textures/runy9/zzfallcote_53
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallcote_54
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 330 sin 0 1 0.588889 0.244
	deformvertexes move 0.222529 50.9995 0 sawtooth 0 1 0.588889 0.244
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.588889 0.244
		alphagen wave square 0 1 0.588889 0.244
		tcMod rotate -44
		tcMod stretch sin 0.7 0.7466 1.29549 0.244
	}
}

textures/runy9/zzfallcote_54
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallcote_55
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 330 sin 0 1 0.6 0.244
	deformvertexes move -47.0295 19.7288 0 sawtooth 0 1 0.6 0.244
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.6 0.244
		alphagen wave square 0 1 0.6 0.244
		tcMod rotate 277
		tcMod stretch sin 0.7 0.7466 1.3066 0.244
	}
}

textures/runy9/zzfallcote_55
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallcote_56
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 330 sin 0 1 0.611111 0.244
	deformvertexes move -47.3667 -18.905 0 sawtooth 0 1 0.611111 0.244
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.611111 0.244
		alphagen wave square 0 1 0.611111 0.244
		tcMod rotate -109
		tcMod stretch sin 0.7 0.7466 1.31771 0.244
	}
}

textures/runy9/zzfallcote_56
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallcote_57
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 330 sin 0 1 0.622222 0.244
	deformvertexes move -40.4317 -31.085 0 sawtooth 0 1 0.622222 0.244
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.622222 0.244
		alphagen wave square 0 1 0.622222 0.244
		tcMod rotate -251
		tcMod stretch sin 0.7 0.7466 1.32882 0.244
	}
}

textures/runy9/zzfallcote_57
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallcote_58
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 330 sin 0 1 0.633333 0.244
	deformvertexes move 46.5995 -20.7241 0 sawtooth 0 1 0.633333 0.244
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.633333 0.244
		alphagen wave square 0 1 0.633333 0.244
		tcMod rotate 103
		tcMod stretch sin 0.7 0.7466 1.33993 0.244
	}
}

textures/runy9/zzfallcote_58
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallcote_59
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 330 sin 0 1 0.644444 0.244
	deformvertexes move 40.397 -31.1301 0 sawtooth 0 1 0.644444 0.244
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.644444 0.244
		alphagen wave square 0 1 0.644444 0.244
		tcMod rotate 166
		tcMod stretch sin 0.7 0.7466 1.35104 0.244
	}
}

textures/runy9/zzfallcote_59
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallcote_60
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 330 sin 0 1 0.655556 0.244
	deformvertexes move -11.5011 49.6863 0 sawtooth 0 1 0.655556 0.244
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.655556 0.244
		alphagen wave square 0 1 0.655556 0.244
		tcMod rotate -262
		tcMod stretch sin 0.7 0.7466 1.36216 0.244
	}
}

textures/runy9/zzfallcote_60
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallcote_61
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 330 sin 0 1 0.666667 0.244
	deformvertexes move 19.8183 46.9919 0 sawtooth 0 1 0.666667 0.244
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.666667 0.244
		alphagen wave square 0 1 0.666667 0.244
		tcMod rotate 372
		tcMod stretch sin 0.7 0.7466 1.37327 0.244
	}
}

textures/runy9/zzfallcote_61
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallcote_62
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 330 sin 0 1 0.677778 0.244
	deformvertexes move 32.4111 -39.3766 0 sawtooth 0 1 0.677778 0.244
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.677778 0.244
		alphagen wave square 0 1 0.677778 0.244
		tcMod rotate 315
		tcMod stretch sin 0.7 0.7466 1.38438 0.244
	}
}

textures/runy9/zzfallcote_62
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallcote_63
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 330 sin 0 1 0.688889 0.244
	deformvertexes move -39.4382 -32.3362 0 sawtooth 0 1 0.688889 0.244
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.688889 0.244
		alphagen wave square 0 1 0.688889 0.244
		tcMod rotate 157
		tcMod stretch sin 0.7 0.7466 1.39549 0.244
	}
}

textures/runy9/zzfallcote_63
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallcote_64
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 330 sin 0 1 0.7 0.244
	deformvertexes move 48.7108 15.1083 0 sawtooth 0 1 0.7 0.244
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.7 0.244
		alphagen wave square 0 1 0.7 0.244
		tcMod rotate 138
		tcMod stretch sin 0.7 0.7466 1.4066 0.244
	}
}

textures/runy9/zzfallcote_64
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallcote_65
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 330 sin 0 1 0.711111 0.244
	deformvertexes move -44.9381 -24.1158 0 sawtooth 0 1 0.711111 0.244
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.711111 0.244
		alphagen wave square 0 1 0.711111 0.244
		tcMod rotate -2
		tcMod stretch sin 0.7 0.7466 1.41771 0.244
	}
}

textures/runy9/zzfallcote_65
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallcote_66
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 330 sin 0 1 0.722222 0.244
	deformvertexes move 12.3112 -49.4918 0 sawtooth 0 1 0.722222 0.244
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.722222 0.244
		alphagen wave square 0 1 0.722222 0.244
		tcMod rotate 292
		tcMod stretch sin 0.7 0.7466 1.42882 0.244
	}
}

textures/runy9/zzfallcote_66
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallcote_67
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 330 sin 0 1 0.733333 0.244
	deformvertexes move 48.5387 -15.6523 0 sawtooth 0 1 0.733333 0.244
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.733333 0.244
		alphagen wave square 0 1 0.733333 0.244
		tcMod rotate 78
		tcMod stretch sin 0.7 0.7466 1.43993 0.244
	}
}

textures/runy9/zzfallcote_67
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallcote_68
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 330 sin 0 1 0.744444 0.244
	deformvertexes move 27.9838 42.6369 0 sawtooth 0 1 0.744444 0.244
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.744444 0.244
		alphagen wave square 0 1 0.744444 0.244
		tcMod rotate -243
		tcMod stretch sin 0.7 0.7466 1.45104 0.244
	}
}

textures/runy9/zzfallcote_68
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallcote_69
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 330 sin 0 1 0.755556 0.244
	deformvertexes move 39.9612 31.6876 0 sawtooth 0 1 0.755556 0.244
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.755556 0.244
		alphagen wave square 0 1 0.755556 0.244
		tcMod rotate 120
		tcMod stretch sin 0.7 0.7466 1.46216 0.244
	}
}

textures/runy9/zzfallcote_69
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallcote_70
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 330 sin 0 1 0.766667 0.244
	deformvertexes move 8.80609 50.234 0 sawtooth 0 1 0.766667 0.244
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.766667 0.244
		alphagen wave square 0 1 0.766667 0.244
		tcMod rotate -35
		tcMod stretch sin 0.7 0.7466 1.47327 0.244
	}
}

textures/runy9/zzfallcote_70
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallcote_71
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 330 sin 0 1 0.777778 0.244
	deformvertexes move 50.5591 6.69125 0 sawtooth 0 1 0.777778 0.244
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.777778 0.244
		alphagen wave square 0 1 0.777778 0.244
		tcMod rotate -99
		tcMod stretch sin 0.7 0.7466 1.48438 0.244
	}
}

textures/runy9/zzfallcote_71
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallcote_72
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 330 sin 0 1 0.788889 0.244
	deformvertexes move 49.2442 13.2668 0 sawtooth 0 1 0.788889 0.244
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.788889 0.244
		alphagen wave square 0 1 0.788889 0.244
		tcMod rotate 381
		tcMod stretch sin 0.7 0.7466 1.49549 0.244
	}
}

textures/runy9/zzfallcote_72
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallcote_73
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 330 sin 0 1 0.8 0.244
	deformvertexes move -19.9338 -46.943 0 sawtooth 0 1 0.8 0.244
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.8 0.244
		alphagen wave square 0 1 0.8 0.244
		tcMod rotate 233
		tcMod stretch sin 0.7 0.7466 1.5066 0.244
	}
}

textures/runy9/zzfallcote_73
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallcote_74
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 330 sin 0 1 0.811111 0.244
	deformvertexes move 2.20768 -50.9522 0 sawtooth 0 1 0.811111 0.244
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.811111 0.244
		alphagen wave square 0 1 0.811111 0.244
		tcMod rotate -207
		tcMod stretch sin 0.7 0.7466 1.51771 0.244
	}
}

textures/runy9/zzfallcote_74
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallcote_75
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 330 sin 0 1 0.822222 0.244
	deformvertexes move 37.9444 -34.0767 0 sawtooth 0 1 0.822222 0.244
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.822222 0.244
		alphagen wave square 0 1 0.822222 0.244
		tcMod rotate 5
		tcMod stretch sin 0.7 0.7466 1.52882 0.244
	}
}

textures/runy9/zzfallcote_75
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallcote_76
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 330 sin 0 1 0.833333 0.244
	deformvertexes move -42.1195 -28.7567 0 sawtooth 0 1 0.833333 0.244
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.833333 0.244
		alphagen wave square 0 1 0.833333 0.244
		tcMod rotate 345
		tcMod stretch sin 0.7 0.7466 1.53993 0.244
	}
}

textures/runy9/zzfallcote_76
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallcote_77
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 330 sin 0 1 0.844444 0.244
	deformvertexes move -45.2683 23.4899 0 sawtooth 0 1 0.844444 0.244
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.844444 0.244
		alphagen wave square 0 1 0.844444 0.244
		tcMod rotate 207
		tcMod stretch sin 0.7 0.7466 1.55104 0.244
	}
}

textures/runy9/zzfallcote_77
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallcote_78
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 330 sin 0 1 0.855556 0.244
	deformvertexes move 29.6224 -41.5152 0 sawtooth 0 1 0.855556 0.244
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.855556 0.244
		alphagen wave square 0 1 0.855556 0.244
		tcMod rotate 180
		tcMod stretch sin 0.7 0.7466 1.56216 0.244
	}
}

textures/runy9/zzfallcote_78
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallcote_79
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 330 sin 0 1 0.866667 0.244
	deformvertexes move 18.6982 -47.4487 0 sawtooth 0 1 0.866667 0.244
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.866667 0.244
		alphagen wave square 0 1 0.866667 0.244
		tcMod rotate 422
		tcMod stretch sin 0.7 0.7466 1.57327 0.244
	}
}

textures/runy9/zzfallcote_79
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallcote_80
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 330 sin 0 1 0.877778 0.244
	deformvertexes move -50.9591 2.04227 0 sawtooth 0 1 0.877778 0.244
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.877778 0.244
		alphagen wave square 0 1 0.877778 0.244
		tcMod rotate -91
		tcMod stretch sin 0.7 0.7466 1.58438 0.244
	}
}

textures/runy9/zzfallcote_80
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallcote_81
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 330 sin 0 1 0.888889 0.244
	deformvertexes move -27.0712 43.2221 0 sawtooth 0 1 0.888889 0.244
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.888889 0.244
		alphagen wave square 0 1 0.888889 0.244
		tcMod rotate 105
		tcMod stretch sin 0.7 0.7466 1.59549 0.244
	}
}

textures/runy9/zzfallcote_81
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallcote_82
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 330 sin 0 1 0.9 0.244
	deformvertexes move -6.08544 -50.6356 0 sawtooth 0 1 0.9 0.244
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.9 0.244
		alphagen wave square 0 1 0.9 0.244
		tcMod rotate 282
		tcMod stretch sin 0.7 0.7466 1.6066 0.244
	}
}

textures/runy9/zzfallcote_82
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallcote_83
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 330 sin 0 1 0.911111 0.244
	deformvertexes move 28.5727 -42.2445 0 sawtooth 0 1 0.911111 0.244
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.911111 0.244
		alphagen wave square 0 1 0.911111 0.244
		tcMod rotate 336
		tcMod stretch sin 0.7 0.7466 1.61771 0.244
	}
}

textures/runy9/zzfallcote_83
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallcote_84
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 330 sin 0 1 0.922222 0.244
	deformvertexes move 15.3207 48.6444 0 sawtooth 0 1 0.922222 0.244
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.922222 0.244
		alphagen wave square 0 1 0.922222 0.244
		tcMod rotate -39
		tcMod stretch sin 0.7 0.7466 1.62882 0.244
	}
}

textures/runy9/zzfallcote_84
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallcote_85
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 330 sin 0 1 0.933333 0.244
	deformvertexes move -38.8679 33.0195 0 sawtooth 0 1 0.933333 0.244
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.933333 0.244
		alphagen wave square 0 1 0.933333 0.244
		tcMod rotate 315
		tcMod stretch sin 0.7 0.7466 1.63993 0.244
	}
}

textures/runy9/zzfallcote_85
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallcote_86
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 330 sin 0 1 0.944444 0.244
	deformvertexes move -48.3786 16.1403 0 sawtooth 0 1 0.944444 0.244
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.944444 0.244
		alphagen wave square 0 1 0.944444 0.244
		tcMod rotate -196
		tcMod stretch sin 0.7 0.7466 1.65104 0.244
	}
}

textures/runy9/zzfallcote_86
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallcote_87
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 330 sin 0 1 0.955556 0.244
	deformvertexes move -18.1554 -47.659 0 sawtooth 0 1 0.955556 0.244
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.955556 0.244
		alphagen wave square 0 1 0.955556 0.244
		tcMod rotate -277
		tcMod stretch sin 0.7 0.7466 1.66216 0.244
	}
}

textures/runy9/zzfallcote_87
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallcote_88
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 330 sin 0 1 0.966667 0.244
	deformvertexes move -40.6671 30.7764 0 sawtooth 0 1 0.966667 0.244
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.966667 0.244
		alphagen wave square 0 1 0.966667 0.244
		tcMod rotate -209
		tcMod stretch sin 0.7 0.7466 1.67327 0.244
	}
}

textures/runy9/zzfallcote_88
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	q3map_cloneshader textures/runy9/zzfallcote_89
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 330 sin 0 1 0.977778 0.244
	deformvertexes move -47.9356 -17.4121 0 sawtooth 0 1 0.977778 0.244
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.977778 0.244
		alphagen wave square 0 1 0.977778 0.244
		tcMod rotate 143
		tcMod stretch sin 0.7 0.7466 1.68438 0.244
	}
}

textures/runy9/zzfallcote_89
{
	qer_editorimage textures/runy9/raidersparticule01.tga
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 330 sin 0 1 0.988889 0.244
	deformvertexes move 48.5176 15.7175 0 sawtooth 0 1 0.988889 0.244
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/runy9/raidersparticule01.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave square 0 1 0.988889 0.244
		alphagen wave square 0 1 0.988889 0.244
		tcMod rotate 280
		tcMod stretch sin 0.7 0.7466 1.69549 0.244
	}
}

